---
permalink: cloud-connector/install-intro-concept.html
sidebar: sidebar
keywords: Cloud Connector installation, install Cloud Connector
summary: The SANtricity Cloud Connector packaged solution (.bin file) is available for RedHat and SUSE Linux platforms only.
---
= Install SANtricity Cloud Connector
:icons: font
:imagesdir: ../media/

[.lead]
The SANtricity Cloud Connector packaged solution (.bin file) is available for RedHat and SUSE Linux platforms only.

You can install the SANtricity Cloud Connector application through graphical mode or console mode on a compatible Linux operating system. During the installation process, you must specify the non-SSL and SSL port numbers for the SANtricity Cloud Connector. When installed, the SANtricity Cloud Connector runs as a daemon process.

.Before you begin
Review the following notes:

* If SANtricity Web Services Proxy is already installed on the same server as the SANtricity Cloud Connector, conflicts will occur between non-SSL port numbers and SSL port numbers conflicts. In this case, choose appropriate numbers for the non-SSL port and the SSL port during the SANtricity Cloud Connector installation.
* If any hardware changes are performed on your host, re-install the SANtricity Cloud Connector application to ensure encryption consistency.
* Backups created through version 3.1 of the SANtricity Cloud Connector application are not compatible with version 4.0 of the SANtricity Cloud Connector application. If you intend to maintain these backups, you must continue to use your previous version of the SANtricity Cloud Connector. To ensure successful installation of separate 3.1 and 4.0 releases of the SANtricity Cloud Connector, unique port numbers must be assigned for each version of the application.

== Install Device Mapper Multipath (DM-MP)

Any host running the SANtricity Cloud Connector also must run Linux Device Mapper Multipath (DM-MP) and have the multipath-tools package installed.

The SANtricity Cloud Connector discovery process relies on the multipath tools package for discovery and recognition of the volumes and files to backup or restore. For more information on how to set up and configure the Device Mapper, see the _SANtricity Storage Manager Multipath Drivers Guide_ for the release of SANtricity you are using under the https://mysupport.netapp.com/info/web/ECMP1658252.html[E-Series and SANtricity Document Resources^].

== Install Cloud Connector

You can install SANtricity Cloud Connector on Linux operating systems in either graphical mode or console mode.

=== Graphical mode

You can use graphical mode to install the SANtricity Cloud Connector on a Linux operating system.

.Before you begin

Designate a host location for the SANtricity Cloud Connector installation.

.Steps

. Download the SANtricity Cloud Connector installation file to the desired host location.
. Open a terminal window.
. Navigate to the directory file containing the SANtricity Cloud Connector installation file.
. Start the SANtricity Cloud Connector installation process:
+
----
./cloudconnector-xxxx.bin –i gui
----
+
In this command, `xxxx` designates the version number of the application.
+
The Installer window is displayed.

. Review the Introduction statement, and then click *Next*.
+
The License Agreement for NetApp, Inc. Software is displayed within the installer window.

. Accept the terms of the License Agreement, and then click *Next*.
+
The Backups created with previous releases of SANtricity Cloud Connector page is displayed.

. To acknowledge the Backups created with previous releases of SANtricity Cloud Connector message, click *Next*.
+
NOTE: To install version 4.0 of the SANtricity Cloud Connector while maintaining a previous version, unique port numbers must be assigned for each version of the application.
+
The Choose Install page is displayed within the Installer window. The Where Would You Like to Install field displays the following default install folder: `opt/netapp/santricity_cloud_connector4/`

. Choose one of the following options:
 ** To accept the default location, click *Next*.
 ** To change the default location, enter a new folder location.
An Enter the Non SSL Jetty Port Number page is displayed. A default value of 8080 is assigned to the non-SSL port.
. Choose one of the following options:
 ** To accept the default SSL port number, click *Next*.
 ** To change the default SSL port number, enter the new desired port number value.
. Choose one of the following options:
 ** To accept the default Non SSL port number, click *Next*.
 ** To change the default Non SSL port number, enter the new desired port number value.
The Pre-Installation Summary page is displayed.
. Review the displayed Pre-Installation Summary, and then click *Install*.
+
The installation of the SANtricity Cloud Connector begins and a Webserver Daemon Setup prompt is displayed.

. Click *OK* to acknowledge the Webserver Daemon Setup prompt.
+
The Installation Complete message is displayed.

. Click *Done* to exit the SANtricity Cloud Connecter installer.

=== Console mode

You can use the console mode to install the SANtricity Cloud Connector on a Linux operating system.

.Before you begin

Designate a host location for the SANtricity Cloud Connector installation.

.Steps

. Download the SANtricity Cloud Connector installation file to the desired IO host location.
. Open a terminal window.
. Navigate to the directory file containing the SANtricity Cloud Connector installation file.
. Start the SANtricity Cloud Connector installation process:
+
----
./cloudconnector-xxxx.bin –i console
----
+
In this command, `xxxx` indicates the version number of the application.
+
The installation process for the SANtricity Cloud Connector is initialized.

. Press *Enter* to proceed with the installation process.
+
The End User License Agreement for NetApp, Inc. Software is displayed within the installer window.
+
NOTE: To cancel the installation process at any time, type `quit` under the installer window.

. Press *Enter* to proceed through each portion of the End User License Agreement.
+
The License Agreement acceptance statement is displayed under the installer window.

. To accept the terms of the End User License Agreement and proceed with the installation of the SANtricity Cloud Connector, enter `Y` and press *Enter* under the installer window.
+
The Backups created with previous releases of SANtricity Cloud Connector page is displayed.
+
NOTE: If you do not accept the terms of the End User Agreement, type `N` and press *Enter* to terminate the installation process for the SANtricity Cloud Connector.

. To acknowledge the Backups created with previous releases of SANtricity Cloud Connector message, press *Enter*.
+
NOTE: To install version 4.0 of the SANtricity Cloud Connector while maintaining a previous version, unique port numbers must be assigned for each version of the application.
+
A Choose Install Folder message with the following default install folder for the SANtricity Cloud Connector is displayed:``/opt/netapp/santricity_cloud_connector4/``.

. Choose one of the following options:
 ** To accept the default install location, press *Enter*.
 ** To change the default install location, enter the new folder location.
An Enter the Non SSL Jetty Port Number message is displayed. A default value of 8080 is assigned to the Non SSL port.
. Choose one of the following options:
 ** To accept the default SSL port number, press *Next*.
 ** To change the default SSL port number, enter the new desired port number value.
. Choose one of the following options:
 ** To accept the default Non SSL port number, press *Enter*.
 ** To change the default Non SSL port number, enter the new port number value.
The Pre-Installation Summary for the SANtricity Cloud Connector is displayed.
. Review the displayed Pre-Installation Summary, and press *Enter*.
. Press *Enter* to acknowledge the Webserver Daemon Setup prompt.
+
The Installation Complete message is displayed.

. Press *Enter* to exit the SANtricity Cloud Connecter installer.

== Add server certificate and CA certificate into a keystore

To use a secure https connection from the browser to the SANtricity Cloud Connector host, you can accept the self-signed certificate from the SANtricity Cloud Connector host or add a certificate and a trust chain recognized by both the browser and the SANtricity Cloud Connector application.

.Before you begin

The SANtricity Cloud Connector application must be installed on a host.

.Steps

. Stop the service using the `systemctl` command.
. From the default install location, access the working directory.
+
NOTE: The default install location for the SANtricity Cloud Connector is `/opt/netapp/santricity_cloud_connector4`.

. Using the `keytool` command, create your server certificate, and certificate signing request (CSR).
+
*EXAMPLE*
+
----
keytool -genkey -dname "CN=host.example.com, OU=Engineering, O=Company, L=<CITY>, S=<STATE>, C=<COUNTRY>" -alias cloudconnect -keyalg "RSA" -sigalg SHA256withRSA -keysize 2048 -validity 365 -keystore keystore_cloudconnect.jks -storepass changeit
keytool -certreq -alias cloudconnect -keystore keystore_cloudconnect.jks -storepass changeit -file cloudconnect.csr
----

. Send the generated CSR to the certificate authority (CA) of your choosing.
+
The certificate authority signs the certificate request and returns a signed certificate. In addition, you receive a certificate from the CA itself. This CA certificate must be imported into your keystore.

. Import the certificate and the CA certificate chain into the application keystore: `/<install Path>/working/keystore`
+
*EXAMPLE*
+
----
keytool -import -alias ca-root -file root-ca.cer -keystore keystore_cloudconnect.jks -storepass <password> -noprompt
keytool -import -alias ca-issuing-1 -file issuing-ca-1.cer -keystore keystore_cloudconnect.jks -storepass <password> -noprompt
keytool -import -trustcacerts -alias cloudconnect -file certnew.cer -keystore keystore_cloudconnect.jks -storepass <password>
----

. Restart the service.

== Add StorageGRID certificate into a keystore

If you are configuring StorageGRID as the target type for the SANtricity Cloud Connector application, you must first add a StorageGRID certificate into the SANtricity Cloud Connector keystore.

.Before you begin

* You have a signed StorageGRID certificate.
* You have the SANtricity Cloud Connector application installed on a host.

.Steps

. Stop the service using the `systemctl` command.
. From the default install location, access the working directory.
+
NOTE: The default install location for the SANtricity Cloud Connector is `/opt/netapp/santricity_cloud_connector4`.

. Import the StorageGRID certificate into the application keystore: `/<install Path>/working/keystore`
+
*EXAMPLE*
+
----
opt/netapp/santricity_cloud_connector4/jre/bin/keytool -import -trustcacerts -storepass changeit -noprompt -alias StorageGrid_SSL -file /home/ictlabsg01.cer -keystore /opt/netapp/santricity_cloud_connector/jre/lib/security/cacerts
----

. Restart the service.
