---
permalink: cloud-connector/learn_intro_concept.html
sidebar: sidebar
keywords: learn, general, concept, setup, installation, configuration, job, santricity, cloud, connector, application
summary: Learn about general concepts, setup, installation, configuration, and jobs associated with the SANtricity Cloud Connector application.
---
= Learn about Cloud Connector
:icons: font
:imagesdir: ../media/

[.lead]
Learn about general concepts, setup, installation, configuration, and jobs associated with the SANtricity Cloud Connector application.

* Configuration and backup/restore job procedures apply to the graphical user interface version of the SANtricity Cloud Connector.
* REST API workflows for the SANtricity Cloud Connector application are not described.
* For experienced developers, endpoints are available for each SANtricity Cloud Connector operation under the API documentation. The API documentation is accessible by navigating to h``ttp://<hostname.domain>:<port>/docs`` through a browser.

== Understand the SANtricity Cloud Connector

[.lead]
The SANtricity Cloud Connector is a host-based Linux application that enables you to perform full block-based and file-based backup and recovery of E-Series volumes to S3 complaint accounts (for example, Amazon Simple Storage Service and NetApp StorageGRID) and NetApp AltaVault appliance.

Available for installation on RedHat and SUSE Linux platforms, the SANtricity Cloud Connector is a packaged solution (.bin file). After you install SANtricity Cloud Connector, you can configure the application to perform backup and restore jobs for E-Series volumes to an AltaVault appliance or to your existing Amazon S3 or StorageGRID accounts. All jobs performed through the SANtricity Cloud Connector use REST-based APIs.

=== Types of backup

[.lead]
The SANtricity Cloud Connector provides two types of backups, image-based and file-based backups.

* *Image-based backup*
+
An image-based backup reads the raw data blocks from a snapshot volume and backs them up to a file known as an image. All of the data blocks on the snapshot volume are backed up, including empty blocks, blocks occupied by deleted files, blocks associated with partitioning, and filesystem metadata. Image backups have the advantage of storing all information with the snapshot volume regardless of the partitioning scheme or filesystems on it.
+
The image is not stored on the Backup Target as a single file but is instead broken up into a series of Data Chunks, which are 64MB in size. The data chunks allow SANtricity Cloud Connector to use multiple connections to the backup target, thereby improving the performance of the backup process.
+
For backups to StorageGRID and Amazon Web Services (S3), each data chunk uses a separate encryption key to encrypt the chunk. The key is a SHA256 hash consisting of the combination of a user supplied passphrase and the SHA256 hash of the user data. For backups to AltaVault, SANtricity Cloud Connector does not encrypt the data chunks as AltaVault performs this operation.

* *File-based backup*
+
A file-based backup reads the files contained with a filesystem partition and backs them up into a series of data chunks that are 64MB in size. A file-based backup does not back up deleted files or partitioning and filesystem metadata. As with image-based backups, the data chunks allow SANtricity Cloud Connector to use multiple connections to the backup target, thereby improving performance of the backup process.
+
For backups to StorageGRID and Amazon Web Services, each data chunk uses a separate encryption key to encrypt the chunk. The key is a SHA256 hash consisting of the combination of user-supplied pass phrase and the SHA256 hash of the user data. For backups to AltaVault, the data chunks are not encrypted by SANtricity Cloud Connector because AltaVault performs this operation.

== System requirements

[.lead]
Your system must meet compatibility requirements for the SANtricity Cloud Connector.

=== Host hardware requirements

[.lead]
Before installing the SANtricity Cloud Connector, you must make sure that your system meets the following host hardware requirements.

Your hardware must meet the following minimum requirements:

* At least 5 GB of memory - 4 GB for the maximum configured heap size
* At least 5 GB of free disk space is required from the software installation

You must install the SANtricity Web Services Proxy to use the SANtricity Cloud Connector. You can install the Web Services Proxy locally or you can run the application remotely on a different sever. For information on installing the SANtricity Web Services Proxy, see the NetApp SANtricity Web Services Proxy Installing and Using guide under the https://docs.netapp.com/ess-11/index.jsp[E-Series Documentation Center].

=== Supported browsers

[.lead]
You must use only supported browsers with the SANtricity Cloud Connector application.

The following browsers are supported with the SANtricity Cloud Connector application (minimum versions noted):

* Firefox v31
* Google Chrome v47
* Microsoft Internet Explorer v11
* Microsoft Edge, EdgeHTML 12
* Safari v9

NOTE: API documentation for the SANtricity Cloud Connector application will not load when using the Compatibility View setting within the Microsoft Internet Explorer v11 browser. To ensure the API documentation displays properly under the Microsoft Internet Explorer v11 browser, it is recommended that the Compatibility View setting is disabled.

=== Compatible storage arrays and controller firmware

[.lead]
You should verify the compatibility of your storage arrays and firmware before using the SANtricity Cloud Connector application.

For a complete and up-to-date listing of all compatible storage arrays and firmware for the SANtricity Cloud Connector, see the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool].

=== Compatible operating systems

[.lead]
You must have a compatible operating system to use the SANtricity Cloud Connector application.

The SANtricity Cloud Connector 4.0 application is compatible with and supported on the following operating systems:

[options="header"]
|===
| Operating System| Version| Architecture
a|
Red Hat Enterprise Linux (RHEL)
a|
7.x
a|
64 bit
a|
SUSE Linux Enterprise Server (SLES)
a|
12.x
a|
64 bit
|===

=== Supported file systems

[.lead]
You must use supported file systems to perform backups and restores through the SANtricity Cloud Connector application.

The following file systems are supported for backup and restore operations under the SANtricity Cloud Connector application:

* ext2
* ext3
* ext4
