---
permalink: cloud-connector/uninstall_intro_concept.html
sidebar: sidebar
keywords: 
summary: ''
---
= Uninstall the SANtricity Cloud Connector
:icons: font
:imagesdir: ../media/

[.lead]
You can uninstall the SANtricity Cloud Connector through the graphical uninstaller or console.

== Uninstall the SANtricity Cloud Connector through graphical mode

[.lead]
You can use the graphical mode to uninstall the SANtricity Cloud Connector on a Linux operating system.

. From a terminal window, navigate to the directory containing the SANtricity Cloud Connector uninstall file.
+
The uninstall file for the SANtricity Cloud Connector is available at the following default directory location:
+
----
/opt/netapp/santricity_cloud_connector4/uninstall_cloud_connector4
----

. From the directory containing the SANtricity Cloud Connector uninstall file, run the following command:
+
----
./uninstall_cloud_connector4 –i gui
----
+
The uninstall process for the SANtricity Cloud Connector is initialized.

. In the uninstall window, click *Uninstall* to proceed with uninstalling the SANtricity Cloud Connector.
+
The uninstall process is completed, and the SANtricity Cloud Connector application is uninstalled in the Linux operating system.

== Uninstall the SANtricity Cloud Connector through console mode

[.lead]
You can use the console mode to uninstall the SANtricity Cloud Connector on a Linux operating system.

. From a terminal window, navigate to the directory containing the SANtricity Cloud Connector uninstall file.
+
The uninstall file for the SANtricity Cloud Connector is available at the following default directory location:
+
----
/opt/netapp/santricity_cloud_connector4/uninstall_cloud_connector4
----

. From the directory containing the SANtricity Cloud Connector uninstall file, run the following command:
+
----
./uninstall_cloud_connector4 –i console
----
+
The uninstall process for the SANtricity Cloud Connector is initialized.

. In the uninstall window, press *Enter* to proceed with uninstalling the SANtricity Cloud Connector.
+
The uninstall process is completed, and the SANtricity Cloud Connector application is uninstalled in the Linux operating system.
