---
permalink: config-linux/fc-access-sam-setup-wizard-task.html
sidebar: sidebar
keywords: access System Manager Linux, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: You use the Setup wizard in SANtricity System Manager to configure your storage array.
---
= Access SANtricity System Manager and use the Setup wizard
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
You use the Setup wizard in SANtricity System Manager to configure your storage array.

.Before you begin

* You must use out-of-band management.
* Ensure that the device from which you will access SANtricity System Manager contains one of the following browsers:
+
[options="header"]
|===
| Browser| Minimum version
a|
Google Chrome
a|
79
a|
Microsoft Internet Explorer
a|
11
a|
Microsoft Edge
a|
79
a|
Mozilla Firefox
a|
70
a|
Safari
a|
12
|===


.About this task

The wizard automatically relaunches when you open System Manager or refresh your browser and _at least one_ of the following conditions is met:

* No pools and volume groups are detected.
* No workloads are detected.
* No notifications are configured.

.Steps

. From your browser, enter the following URL: `+https://<DomainNameOrIPAddress>+`
+
`IPAddress` is the address for one of the storage array controllers.
+
The first time SANtricity System Manager is opened on an array that has not been configured, the Set Administrator Password prompt appears. Role-based access management configures four local roles: admin, support, security, and monitor. The latter three roles have random passwords that cannot be guessed. After you set a password for the admin role, you can change all of the passwords using the admin credentials. For more information about the four local user roles, see the online help available in the SANtricity System Manager user interface.

. Enter the System Manager password for the admin role in the Set Administrator Password and Confirm Password fields, and then click *Set Password*.
+
The Setup wizard launches if there are no pools, volumes groups, workloads, or notifications configured.

. Use the Setup wizard to perform the following tasks:
 ** *Verify hardware (controllers and drives)* -- Verify the number of controllers and drives in the storage array. Assign a name to the array.
 ** *Verify hosts and operating systems* -- Verify the host and operating system types that the storage array can access.
 ** *Accept pools* -- Accept the recommended pool configuration for the express installation method. A pool is a logical group of drives.
 ** *Configure alerts* -- Allow System Manager to receive automatic notifications when a problem occurs with the storage array.
 ** *Enable AutoSupport* -- Automatically monitor the health of your storage array and have dispatches sent to technical support.
. If you have not already created a volume, create one by going to menu:Storage[Volumes > Create > Volume].
+
For more information, see the online help for SANtricity System Manager.
