---
permalink: config-linux/fc-configure-switches-task.html
sidebar: sidebar
keywords: FC switches, zoning, express linux configuration, software configuration, linux host,
summary: Configure the Fibre Channel switches to enable the hosts to connect to the storage array and limit the number of paths.
---
= Configure the FC switches
:icons: font
:imagesdir: ../media/

[.lead]
Configuring (zoning) the Fibre Channel (FC) switches enables the hosts to connect to the storage array and limits the number of paths. You zone the switches using the management interface for the switches.

.Before you begin

Make sure you have the following:

* Administrator credentials for the switches.
* The WWPN of each host initiator port and of each controller target port connected to the switch. (Use your HBA utility for discovery.)

.About this task

Each initiator port must be in a separate zone with all of its corresponding target ports. For details about zoning your switches, see the switch vendor's documentation.

.Steps

. Log in to the FC switch administration program, and then select the zoning configuration option.
. Create a new zone that includes the first host initiator port and that also includes all of the target ports that connect to the same FC switch as the initiator.
. Create additional zones for each FC host initiator port in the switch.
. Save the zones, and then activate the new zoning configuration.
