---
permalink: config-linux/fc-configure-multipath-software-task.html
sidebar: sidebar
keywords: multipath software for Linux, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: Configure multipath software, which  provides a redundant path to the storage array in case one of the physical paths is disrupted.
---
= Configure the multipath software
:icons: font
:imagesdir: ../media/

[.lead]
To provide a redundant path to the storage array, you can configure multipath software.

.Before you begin

You have installed the required packages on your system.

* For Red Hat (RHEL) hosts, verify the packages are installed by running `rpm -q device-mapper-multipath`.
* For SLES hosts, verify the packages are installed by running `rpm -q multipath-tools`.

If you have not already installed the operating system, use the media supplied by your operating system vendor.

.About this task

Multipath software provides a redundant path to the storage array in case one of the physical paths is disrupted. The multipath software presents the operating system with a single virtual device that represents the active physical paths to the storage. The multipath software also manages the failover process that updates the virtual device.

You use the device mapper multipath (DM-MP) tool for Linux installations. By default, DM-MP is disabled in RHEL and SLES. Complete the following steps to enable DM-MP components on the host.

.Steps

. If a multipath.conf file is not already created, run the `# touch /etc/multipath.conf` command.
. Use the default multipath settings by leaving the multipath.conf file blank.
. Start the multipath service.
+
----
# systemctl start multipathd
----

. Save your kernel version by running the `uname -r` command.
+
----
# uname -r
3.10.0-327.el7.x86_64
----
+
You will use this information when you assign volumes to the host.

. Do one of the following to enable the multipathd daemon on boot.
+
[options="header"]
|===
| If you are using....| Do this...
a|
RHEL 7.x and 8.x systems:
a|
`systemctl enable multipathd`
a|
SLES 12.x and 15.x systems:
a|
`systemctl enable multipathd`
|===

. Rebuild the `initramfs` image or the `initrd` image under /boot directory:
+
[options="header"]
|===
| If you are using....| Do this...
a|
RHEL 7.x and 8.x systems:
a|
`dracut --force --add multipath`
a|
SLES 12.x and 15.x systems:
a|
`dracut --force --add multipath`
|===

. Make sure that the newly created /boot/initrams-* image or /boot/initrd-* image is selected in the boot configuration file.
+
For example, for grub it is `/boot/grub/menu.lst` and for grub2 it is `/boot/grub2/menu.cfg`.

. Use the "Create host manually" procedure in the online help to check whether the hosts are defined. Verify that each host type is either *Linux DM-MP (Kernel 3.10 or later)* if you enable the Automatic Load Balancing feature, or *Linux DM-MP (Kernel 3.9 or earlier)* if you disable the Automatic Load Balancing feature. If necessary, change the selected host type to the appropriate setting.
. Reboot the host.
