---
permalink: config-linux/fc-verify-linux-config-support-task.html
sidebar: sidebar
keywords: express linux configuration, software configuration, linux host,
summary: Verify that the Linux configuration is supported.
---
= Verify Linux configuration support in E-Series (FC)
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
To ensure reliable operation, you create an implementation plan and then use the NetApp Interoperability Matrix Tool (IMT) to verify that the entire configuration is supported.

.Steps

. Go to the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].
. Click on the *Solution Search* tile.
. In the menu:Protocols[SAN Host] area, click the *Add* button next to *E-Series SAN Host*.
. Click *View Refine Search Criteria*.
+
The Refine Search Criteria section is displayed. In this section you may select the protocol that applies, as well as other criteria for the configuration such as Operating System, NetApp OS, and Host Multipath driver.
. Select the criteria you know you want for your configuration, and then see what compatible configuration elements apply.
. As necessary, make the updates for your operating system and protocol that are prescribed in the tool.
+
Detailed information for your chosen configuration is accessible on the View Supported Configurations page by clicking the right page arrow.
