---
permalink: config-linux/index.html
sidebar: sidebar
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: Use the express configuration for a Linux host with an E-Series system.
---
= Linux express configuration overview
:icons: font
:imagesdir: ../media/

[.lead]
The Linux express method for installing your storage array and accessing SANtricity System Manager is appropriate for setting up a standalone Linux host to an E-Series storage system. It is designed to get the storage system up and running as quickly as possible with minimal decision points.

== Procedure overview

The Linux express method includes the following steps.

. Set up one of the following communication environments:
 ** Fibre Channel (FC)
 ** iSCSI
 ** SAS
 ** iSER over Infiniband
 ** SRP over Infiniband
 ** NVMe over Infiniband
 ** NVMe over RoCE
 ** NVMe over Fibre Channel
. Create logical volumes on the storage array.
. Make the volumes available to the data host.

== Find more information

* Online help -- Describes how to use SANtricity System Manager to complete configuration and storage management tasks. It is available within the product.
* https://kb.netapp.com/[NetApp Knowledgebase^] (a database of articles)
 -- Provides troubleshooting information, FAQs, and instructions for a wide range of NetApp products and technologies.
 * http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^] -- Enables you to search for configurations of NetApp products and components that meet the standards and requirements specified by NetApp.
  * https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html#recommended-driver-settings-with-linux-kernel[Install Linux Unified Host Utilities 7.1^] -- Describes how to install the Linux Unified Host Utilities 7.1.
