---
permalink: config-linux/iscsi-configure-array-side-network-task.html
sidebar: sidebar
keywords: configure iSCSI networking, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: Configure iSCSI networking on the array side.
---
= Configure array-side networking
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
You use the SANtricity System Manager GUI to configure iSCSI networking on the array side.

.Before you begin

* The IP address or domain name for one of the storage array controllers.
* A password for the System Manager GUI, or Role-Based Access Control (RBAC) or LDAP and a directory service configured for the appropriate security access to the storage array. See the SANtricity System Manager online help for more information about Access Management.

.About this task

This task describes how to access the iSCSI port configuration from System Manager's Hardware page. You can also access the configuration from menu:System[Settings > Configure iSCSI ports].

.Steps

. From your browser, enter the following URL: `+https://<DomainNameOrIPAddress>+`
+
`IPAddress` is the address for one of the storage array controllers.
+
The first time SANtricity System Manager is opened on an array that has not been configured, the Set Administrator Password prompt appears. Role-based access management configures four local roles: admin, support, security, and monitor. The latter three roles have random passwords that cannot be guessed. After you set a password for the admin role, you can change all of the passwords using the admin credentials. For more information about the four local user roles, see the online help available in the SANtricity System Manager user interface.

. Enter the System Manager password for the admin role in the Set Administrator Password and Confirm Password fields, and then click *Set Password*.
+
The Setup wizard launches if there are no pools, volumes groups, workloads, or notifications configured.

. Close the Setup wizard.
+
You will use the wizard later to complete additional setup tasks.

. Select *Hardware*.
. If the graphic shows the drives, click *Show back of shelf*.
+
The graphic changes to show the controllers instead of the drives.

. Click the controller with the iSCSI ports you want to configure.
+
The controller's context menu appears.

. Select *Configure iSCSI ports*.
+
The Configure iSCSI Ports dialog box opens.

. In the drop-down list, select the port you want to configure, and then click *Next*.
. Select the configuration port settings, and then click *Next*.
+
To see all port settings, click the *Show more port settings* link on the right of the dialog box.
+
[options="header"]
|===
| Port Setting| Description
a|
Configured ethernet port speed
a|
Select the desired speed.    The options that appear in the drop-down list depend on the maximum speed that your network can support (for example, 10 Gbps).

NOTE: The optional 25Gb iSCSI host interface cards available on the controllers do not auto-negotiate speeds. You must set the speed for each port to either 10 Gb or 25 Gb. All ports must be set to the same speed.

a|
Enable IPv4 / Enable IPv6
a|
Select one or both options to enable support for IPv4 and IPv6 networks.
a|
TCP listening port     (Available by clicking *Show more port settings*.)
a|
If necessary, enter a new port number.

The listening port is the TCP port number that the controller uses to listen for iSCSI logins from host iSCSI initiators. The default listening port is 3260. You must enter 3260 or a value between 49152 and 65535.
a|
MTU size     (Available by clicking *Show more port settings*.)
a|
If necessary, enter a new size in bytes for the Maximum Transmission Unit (MTU).

The default Maximum Transmission Unit (MTU) size is 1500 bytes per frame. You must enter a value between 1500 and 9000.
a|
Enable ICMP PING responses
a|
Select this option to enable the Internet Control Message Protocol (ICMP). The operating systems of networked computers use this protocol to send messages. These ICMP messages determine whether a host is reachable and how long it takes to get packets to and from that host.
|===
If you selected *Enable IPv4*, a dialog box opens for selecting IPv4 settings after you click *Next*. If you selected *Enable IPv6*, a dialog box opens for selecting IPv6 settings after you click *Next*. If you selected both options, the dialog box for IPv4 settings opens first, and then after you click *Next*, the dialog box for IPv6 settings opens.

. Configure the IPv4 and/or IPv6 settings, either automatically or manually. To see all port settings, click the *Show more settings* link on the right of the dialog box.
+
[options="header"]
|===
| Port setting| Description
a|
Automatically obtain configuration
a|
Select this option to obtain the configuration automatically.
a|
Manually specify static configuration
a|
Select this option, and then enter a static address in the fields. For IPv4, include the network subnet mask and gateway. For IPv6, include the routable IP address and router IP address.
|===

. Click *Finish*.
. Close System Manager.
