---
permalink: config-linux/iscsi-configure-host-side-network-task.html
sidebar: sidebar
keywords: configure iSCSI networking, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: Configure iSCSI networking on the host side.
---
= Configure host-side networking
:icons: font
:imagesdir: ../media/

[.lead]
To configure host-side networking, you must perform several steps.

.About this task

You configure iSCSI networking on the host side by setting the number of node sessions per physical path, turning on the appropriate iSCSI services, configuring the network for the iSCSI ports, creating iSCSI face bindings, and establishing the iSCSI sessions between initiators and targets.

In most cases, you can use the inbox software-initiator for iSCSI CNA/NIC. You do not need to download the latest driver, firmware, and BIOS. Refer to the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^] to determine code requirements.

.Steps

. Install the iSCSI package:
+
*RHEL 7, RHEL 8, or RHEL 9*
+
----
# yum install iscsi-initiator-utils
----
+
*SLES 12 or SLES 15*
+
----
# zypper install open-iscsi
----
. Check the `node.session.nr_sessions` variable in the `/etc/iscsi/iscsid.conf` file to see the default number of sessions per physical path. If necessary, change the default number of sessions to one session.
+
----
node.session.nr_sessions = 1
----

. Edit the iSCSI settings in `/etc/iscsi/iscsid.conf`.
+
----
node.startup = automatic
node.session.timeo.replacement_timeout = 20
----

. Enable and start iSCSI services on the host(s):
+
----
# systemctl start iscsi
# systemctl start iscsid
# systemctl enable iscsi
# systemctl enable iscsid
----
+

. Get the host IQN initiator name, which will be used to configure the host to an array.
+
----
# cat /etc/iscsi/initiatorname.iscsi
----

. Configure the network for iSCSI ports.
+
NOTE: In addition to the public network port, iSCSI initiators should use two or more NICs on separate private segments or vLANs.

 .. Determine the iSCSI port names using the `ifconfig -a` command.
 .. (Optional) Configure persistent names for the iSCSI ports in the event the interface moves around.
 .. Set the IP address for each iSCSI initiator port. The initiator ports should be present on the same subnet as the iSCSI target ports.
+
*Red Hat Enterprise Linux 7 and 8 (RHEL 7 and RHEL 8)*
+
Create the example file `/etc/sysconfig/network-scripts/ifcfg-<NIC port #>` with the following contents.
+
----
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=static
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
NAME=<NIC port #>
UUID=<unique UUID>
DEVICE=<NIC port #>
ONBOOT=yes
IPADDR=192.168.xxx.xxx
PREFIX=24
NETMASK=255.255.255.0
NM_CONTROLLED=no
MTU=
----
+
Optional additions with regards to IPv6:
+
----
IPV6INIT=yes
IPV6_AUTOCONF=no
IPV6ADDR=fdxx::192:168:xxxx:xxxx/32
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=eui64
----
+
*Red Hat Enterprise Linux 9 (RHEL 9)*
+
Use the `nmtui` tool to activate and edit a connection. The tool will generate a `<NIC port #>.nmconnection` file within `/etc/NetworkManager/system-connections/`.
+
*SUSE Linux Enterprise Server 12 and 15 (SLES 12 and SLES 15)*
+
Create the example file `/etc/sysconfig/network/ifcfg-<NIC port #>` with the following contents.
+
----
IPADDR='192.168.xxx.xxx/24'
BOOTPROTO='static'
STARTMODE='auto'
----
Optional addition with regards to IPv6:
+
----
IPADDR_0='fdxx::192:168:xxxx:xxxx/32'
----
+
NOTE: Be sure to set the address for all iSCSI initiator ports.

 .. Restart network services.
+
----
# systemctl restart network
----

 .. Make sure the Linux server can ping _all_ of the iSCSI target ports.
 . (Optional) Create iSCSI iface bindings for each iSCSI interface.
+
----
# iscsiadm -m iface -I iface-<NIC port #> -o new
# iscsiadm -m iface -I iface-eth2 -o new
# iscsiadm -m iface -I iface-<NIC port #> -o update -n iface.net_ifacename -v <NIC port #>
# iscsiadm -m iface -I iface-eth2 -o update -n iface.net_ifacename -v eth2
----
+
NOTE: To list the interfaces, use `iscsiadm -m iface`.
+
. Establish the iSCSI sessions between initiators and targets by one of two methods.
+
The preferred method to create the sessions is to use the SendTargets discovery method. However, this method does not work on some operating system releases.
+
NOTE: Use *Method 2* for RHEL 6.x or SLES 11.3 or earlier.

 .. Discover iSCSI targets. Save the target IQN (it will be the same with each discovery) in the worksheet for the next step.
 ... *Method 1 (without ifaces) - SendTargets discovery:* Use the SendTargets discovery mechanism to one of the target portal IP addresses. This will create sessions for each of the target portals.
+
----
# iscsiadm -m discovery -t st -p <target_ip_address>:<target_tcp_listening_port if changed from the default of 3260>
# iscsiadm -m discovery -t st -p 192.168.0.1
----
+
 ... *Method 2 (with ifaces) - Manual creation:* For each target portal IP address, create a session using the appropriate host interface iface configuration.
+
----
# iscsiadm -m discovery -t st -p <target_ip_address>:<target_tcp_listening_port if changed from default of 3260> -I iface-<NIC port#>
# iscsiadm -m discovery -t st -p 192.168.0.1 -I iface-eth2
----
NOTE: The target IQN looks like the following:
+
----
iqn.1992-01.com.netapp:2365.60080e50001bf1600000000531d7be3
----
 .. Log in to the iSCSI sessions.
+
*Method 1 (without ifaces) - SendTargets*
+
----
# iscsiadm -m node -L all
----
+
*Method 2 (with ifaces) - Manual creation*
+
----
# iscsiadm -m node -T <target_iqn> -p <target_ip_address>:<target_tcp_listening_port if changed from default> -I iface-<NIC port #> -l
# iscsiadm -m node -T iqn.1992-01.com.netapp:2365.60080e50001bf1600000000531d7be3 -p 192.168.0.1 -I iface-eth2 -l
----
+
 .. List the iSCSI sessions established on the host.
+
----
# iscsiadm -m session
----
