---
permalink: config-linux/iser_ib_configure_network_connections_task.html
sidebar: sidebar
keywords: 
summary: 'If your configuration uses the iSER over Infiniband protocol, perform the steps in this section.'
---
= Configure network connections--iSER over Infiniband
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
If your configuration uses the iSER over Infiniband protocol, perform the steps in this section.

When you are using a 56-Gbps HIC with the iSER over Infiniband protocol, additional array configuration is required.

. From the *Setup* tab, select *Configure iSCSI Host Ports* to set the storage array iSCSI addresses.
+
Put the array iSCSI addresses on the same subnet as the host port(s) you will use to create iSCSI sessions. For addresses, see xref:iser_ib_worksheet_concept.adoc[iSER worksheet].

. From the *Devices* tab, select the storage array and go to menu:iSER[Manage Settings] to find the IQN.
+
This information might be necessary when you create iSER sessions from operating systems that do not support send targets discovery. Enter this information in the worksheet, in xref:iser_ib_worksheet_concept.adoc[iSER worksheet].
