---
permalink: config-linux/nvme-fc-setup-failover-host-task.html
sidebar: sidebar
keywords: failover, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: Configure the host to run failover.
---
= Set up failover on the host in E-Series - Linux (NVMe over FC)
:icons: font
:imagesdir: ../media/

[.lead]
To provide a redundant path to the storage array, you can configure the host to run failover.

.Before you begin

You must install the required packages on your system.

* For Red Hat (RHEL) hosts, verify the packages are installed by running `rpm -q device-mapper-multipath`
* For SLES hosts, verify the packages are installed by running `rpm -q multipath-tools`

.About this task

 SLES 12 use Device Mapper Multipath (DMMP) for multipathing when using NVMe over Fibre Channel. RHEL 8, RHEL 9, RHEL 10, SLES 15 and SLES 16 use a built-in Native NVMe Failover. Depending on which OS you are running, some additional configuration of multipath is required to get it running properly.

== Enable Device Mapper Multipath (DMMP) for SLES 12
By default, DM-MP is disabled in SLES. Complete the following steps to enable DM-MP components on the host.

.Steps

. Add the NVMe E-Series device entry to the devices section of the /etc/multipath.conf file, as shown in the following example:
+
----

devices {
        device {
                vendor "NVME"
                product "NetApp E-Series*"
                path_grouping_policy group_by_prio
                failback immediate
                no_path_retry 30
        }
}
----

. Configure `multipathd` to start at system boot.
+
----
# systemctl enable multipathd
----

. Start `multipathd` if it is not currently running.
+
----
# systemctl start multipathd
----

. Verify the status of `multipathd` to make sure it is active and running:
+
----
# systemctl status multipathd
----

== Set up Native NVMe Multipathing for RHEL 8

.About this task
Native NVMe Multipathing is disabled by default in RHEL 8 and must be enabled using the steps below.

.Steps

. Setup `modprobe` rule to turn on Native NVMe Multipathing.
+
----
# echo "options nvme_core multipath=y" >> /etc/modprobe.d/50-nvme_core.conf
----

. Remake `initramfs` with new modprobe parameter.
+
----
# dracut -f
----

. Reboot server to bring it up with the Native NVMe Multipathing enabled
+
----
# reboot
----

. Verify Native NVMe Multipathing has been enabled after the host boots back up.
+
----
# cat /sys/module/nvme_core/parameters/multipath
----

.. If the command output is `N`, then Native NVMe Multipathing is still disabled.
.. If the command output is `Y`, then Native NVMe Multipathing is enabled and any NVMe devices you discover will use it.

NOTE: For SLES 15, SLES 16, RHEL 9 and RHEL 10, Native NVMe Multipathing is enabled by default and no additional configuration is required.
