---
permalink: config-linux/nvme-roce-verify-linux-config-support-task.html
sidebar: sidebar
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: To ensure reliable operation, you create an implementation plan and then use the NetApp Interoperability Matrix Tool (IMT) to verify that the entire configuration is supported.
---
= Verify Linux support and review restrictions
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
As a first step, you should verify that your Linux configuration is supported and also review the controller, switch, host, and recovery restrictions.

== Verify the Linux configuration is supported

To ensure reliable operation, you create an implementation plan and then use the NetApp Interoperability Matrix Tool (IMT) to verify that the entire configuration is supported.

.Steps

. Go to the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].
. Click on the *Solution Search* tile.
. In the menu:Protocols[SAN Host] area, click the *Add* button next to *E-Series SAN Host*.
. Click *View Refine Search Criteria*.
+
The Refine Search Criteria section is displayed. In this section you may select the protocol that applies, as well as other criteria for the configuration such as Operating System, NetApp OS, and Host Multipath driver.
. Select the criteria you know you want for your configuration, and then see what compatible configuration elements apply.
. As necessary, make the updates for your operating system and protocol that are prescribed in the tool.
+
Detailed information for your chosen configuration is accessible on the View Supported Configurations page by clicking the right page arrow.

== Verify NVMe over RoCE restrictions

Before using NVMe over RoCE, see the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^] to review the latest controller, host, and recovery restrictions.

=== Switch restrictions

NOTE: *RISK OF DATA LOSS.* You must enable Priority Flow Control or Global Pause Control on the switch to eliminate the risk of data loss in an NVMe over RoCE environment.

=== Storage and disaster recovery restrictions

* Asynchronous and synchronous mirroring are not supported.
* Thin provisioning (the creation of thin volumes) is not supported.
