---
permalink: config-linux/nvme-ib-configure-subnet-manager-task.html
sidebar: sidebar
keywords: configure subnet manager Linux, path loss, subnet manager, opensm, express linux configuration, linux host,
summary: Using an InfiniBand switch to run subnet manager might cause unexpected path loss during high loads. To avoid path loss, configure the subnet manager on one or more of your hosts using opensm.
---
= Configure subnet manager
:icons: font
:imagesdir: ../media/

[.lead]
A subnet manager must be running in your environment on your switch or on your hosts. If you are running it host-side, use the following procedure to set it up.

.Steps

. Install the `opensm` package on any hosts that will be running the subnet manager.
. Use the `ibstat -p` command to find `GUID0` and `GUID1` of the HCA ports. For example:
+
----
# ibstat -p
 0x248a070300a80a80
 0x248a070300a80a81
----

. Enable Subnet Manager on each port of the connected HCA on the host:

+
*SLES example*
+
** Add the following two lines to /etc/rc.d/rc.after. Substitute the values you found in step 2 for `GUID0` and `GUID1`. For `P0` and `P1`, use the subnet manager priorities, with 1 being the lowest and 15 the highest:
+
----
 opensm -B -g GUID0 -p P0 -f /var/log/opensm-ib0.log
 opensm -B -g GUID1 -p P1 -f /var/log/opensm-ib1.log
----
+
An example of the command with value substitutions:
+
----
# cat /etc/rc.d/rc.local
 opensm -B -g 0x248a070300a80a80 -p 15 -f /var/log/opensm-ib0.log
 opensm -B -g 0x248a070300a80a81 -p 1 -f /var/log/opensm-ib1.log
----

+
*RHEL example*
** Add the following two lines to /etc/rc.d/rc.local. Substitute the values you found in step 2 for `GUID0` and `GUID1`. For `P0` and `P1`, use the subnet manager priorities, with 1 being the lowest and 15 the highest:
+
----
opensm -B -g GUID0 -p P0 -f /var/log/opensm-ib0.log
opensm -B -g GUID1 -p P1 -f /var/log/opensm-ib1.log
----
+
An example of the command with value substitutions:
+
----
# cat /etc/rc.d/rc.local
 opensm -B -g 0x248a070300a80a80 -p 15 -f /var/log/opensm-ib0.log
 opensm -B -g 0x248a070300a80a81 -p 1 -f /var/log/opensm-ib1.log
----
