---
permalink: config-linux/nvme-ib-install-smcli-11-53-task.html
sidebar: sidebar
keywords: install Storage Manager Linux, install CLI Windows, install command line interface, install Host Context Agent, install HCA, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: Install Storage Manager for CLI and HCA in Linux express method.
---
= Install SANtricity Storage Manager for SMcli (SANtricity software version 11.53 or earlier)
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
If you are using SANtricity software 11.53 or earlier, you can install the SANtricity Storage Manager software on your management station to help manage the array.

SANtricity Storage Manager includes the command line interface (CLI) for additional management tasks, and also the Host Context Agent for pushing host configuration information to the storage array controllers through the I/O path.

NOTE: If you are using SANtricity software 11.60 and newer, you do not need to follow these steps. The SANtricity Secure CLI (SMcli) is included in the SANtricity OS and downloadable through the SANtricity System Manager. For more information on how to download the SMcli through the SANtricity System Manager, refer to the link:https://docs.netapp.com/us-en/e-series-santricity/sm-settings/download-cli.html[Download command line interface (CLI)_ topic under the SANtricity System Manager Online Help^]
 
NOTE: Starting with SANtricity software version 11.80.1, the Host Context Agent is no longer supported.

.Before you begin

Make sure you have the following:

* SANtricity software 11.53 or earlier.
* Correct administrator or superuser privileges.
* A system for the SANtricity Storage Manager client with the following minimum requirements:
 ** *RAM*: 2 GB for Java Runtime Engine
 ** *Disk space*: 5 GB
 ** *OS/Architecture*: For guidance on determining the supported operating system versions and architectures, go to http://mysupport.netapp.com[NetApp Support^]. From the *Downloads* tab, go to menu:Downloads[E-Series SANtricity Storage Manager].

.About this task

This task describes how to install SANtricity Storage Manager on both the Windows and Linux OS platforms, because both Windows and Linux are common management station platforms when Linux is used for the data host.

.Steps

. Download the SANtricity software release at http://mysupport.netapp.com[NetApp Support^]. From the *Downloads* tab, go to menu:Downloads[E-Series SANtricity Storage Manager].
. Run the SANtricity installer.
+
[options="header"]
|===
| Windows| Linux
a|
Double-click the SMIA*.exe installation package to start the installation.
a|

 .. Go to the directory where the SMIA*.bin installation package is located.
 .. If the temp mount point does not have execute permissions, set the `IATEMPDIR` variable. Example: `IATEMPDIR=/root ./SMIA-LINUXX64-11.25.0A00.0002.bin`
 .. Run the `chmod +x SMIA*.bin` command to grant execute permission to the file.
 .. Run the `./SMIA*.bin` command to start the installer.

+
|===

. Use the installation wizard to install the software on the management station.
