---
permalink: config-linux/nvme_roce_setup_failover_host_task.html
sidebar: sidebar
keywords: multipath, software, provide, redundant, path, storage, array, case, physical, disrupt, multipath, nvme, dependent, os, version, sles, device, map, dmmp, rhel, sles, native, solution, failover, host, configure, host, run
summary: Multipath software provides a redundant path to the storage array in case one of the physical paths is disrupted. There are currently two methods of multipathing available for NVMe, and which you will be using is going to be dependent on which OS version you are running. For SLES 12, device mapper multipath (DMMP) will be used. For RHEL 7 and SLES 15, a native NVMe multipathing solution will be used.
---
= Set up failover on the host
:icons: font
:imagesdir: ../media/

[.lead]
To provide a redundant path to the storage array, you can configure the host to run failover

===== Before you begin

* You have installed the required packages on your system.
* For Red Hat (RHEL) hosts, verify the packages are installed by running `rpm -q device-mapper-multipath`
* For SLES hosts, verify the packages are installed by running `rpm -q multipath-tools`

===== About this task

Multipath software provides a redundant path to the storage array in case one of the physical paths is disrupted. You can use one of two methods of multipathing for NVMe, depending on which OS version you are running. For SLES 12, use device mapper multipath (DMMP). For RHEL 7 and SLES 15, use a native NVMe multipathing solution.

By default, DM-MP is disabled in RHEL and SLES. Complete the following steps to enable DM-MP components on the host.

===== Steps

. Add the NVMe E-Series device entry to the devices section of the `/etc/multipath.conf` file, as shown in the following example:
+
----

devices {
        device {
                vendor "NVME"
                product "NetApp E-Series*"
                path_grouping_policy group_by_prio
                failback immediate
                no_path_retry 30
        }
}
----

. Configure `multipathd` to start at system boot.
+
----
# systemctl enable multipathd
----

. Start `multipathd` if it is not currently running.
+
----
# systemctl start multipathd
----

. Verify the status of `multipathd` to make sure it is active and running:
+
----
# systemctl status multipathd
----
