---
permalink: config-linux/nvme-roce-create-filesystems-sles-15-task.html
sidebar: sidebar
keywords: file systems, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: For RHEL 9, RHEL 10, SLES 15, and SLES 16, you create a filesystem on the native nvme device and mount the filesystem.
---
= Create filesystems in E-Series - Linux (NVMe over RoCE)
:icons: font
:imagesdir: ../media/

[.lead]
For RHEL 9, RHEL 10, SLES 15, and SLES 16, you create a filesystem on the native nvme device and mount the filesystem.

.Before you begin

Make sure you have completed the link:nvme-roce-access-physical-targets-concept.html[accessing NVMe volumes for an E-Series target from the host] task to ensure the NVMe devices are properly configured and accessible.

.Steps

. Create a file system on the partition for the desired nvme device using the location `/dev/disk/by-id/nvme-eui.[id#]`.
+
The method for creating a file system varies depending on the file system chosen. This example shows creating an `ext4` file system.
+
----
# mkfs.ext4 /dev/disk/by-id/nvme-eui.000082dd5c05d39300a0980000a52225
mke2fs 1.42.11 (22-Oct-2019)
Creating filesystem with 2620928 4k blocks and 655360 inodes
Filesystem UUID: 97f987e9-47b8-47f7-b434-bf3ebbe826d0
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables: done
Writing inode tables: done
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done
----

. Create a folder to mount the new device.
+
----
# mkdir /mnt/ext4
----

. Mount the device.
+
----
# mount /dev/disk/by-id/nvme-eui.000082dd5c05d39300a0980000a52225 /mnt/ext4
----

.What's next?
After you create the filesystems, link:nvme-roce-worksheet-for-concept.html[record your NVMr over RoCE configuration information].