---
permalink: config-linux/nvme-fc-configure-fc-switches-task.html
sidebar: sidebar
keywords: FC switch, zoning, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: Configuring \(zoning\) the Fibre Channel \(FC\) switches enables the hosts to connect to the storage array and limits the number of paths. You zone the switches using the management interface for the switches.
---
= Configure the FC switches
:icons: font
:imagesdir: ../media/

[.lead]
Configuring (zoning) the Fibre Channel (FC) switches enables the hosts to connect to the storage array and limits the number of paths. You zone the switches using the management interface for the switches.

=.Before You Begin

* You must have administrator credentials for the switches.
* You must have used your HBA utility to discover the WWPN of each host initiator port and of each controller target port connected to the switch.

=.About this task

For details about zoning your switches, see the switch vendor's documentation.

Each initiator port must be in a separate zone with all of its corresponding target ports.

=.Steps

. Log in to the FC switch administration program, and then select the zoning configuration option.
. Create a new zone that includes the first host initiator port and that also includes all of the target ports that connect to the same FC switch as the initiator.
. Create additional zones for each FC host initiator port in the switch.
. Save the zones, and then activate the new zoning configuration.
