---
permalink: config-linux/nvme-roce-define-host-task.html
sidebar: sidebar
keywords: use, using, santricity, system, manager, define, host, send, data, storage, array, defining, attach, i/o, volume
summary: Using SANtricity System Manager, you define the hosts that send data to the storage array. Defining a host is one of the steps required to let the storage array know which hosts are attached to it and to allow I/O access to the volumes.
---
= Define a host
:icons: font
:imagesdir: ../media/

[.lead]
Using SANtricity System Manager, you define the hosts that send data to the storage array. Defining a host is one of the steps required to let the storage array know which hosts are attached to it and to allow I/O access to the volumes.

.Before you begin

Keep these guidelines in mind when you define a host:

* You must define the host identifier ports that are associated with the host.
* Make sure that you provide the same name as the host's assigned system name.
* This operation does not succeed if the name you choose is already in use.
* The length of the name cannot exceed 30 characters.

.Steps

. Select *Storage* > *Hosts*.
. Click *Create* > *Host*.
+
The Create Host dialog box appears.

. Select the settings for the host as appropriate.
+
Field details
+
[options="header"]
|===
| Setting| Description
a|
Name
a|
Type a name for the new host.
a|
Host operating system type
a|
Select one of the following options from the drop-down list:

 ** *SANtricity 11.60 and newer*
+
`Linux`

 ** *Pre SANtricity 11.60*
+
`Linux DM-MP (Kernel 3.10 or later)`

a|
Host interface type
a|
Select the host interface type that you want to use. If the array you configure only has one available host interface type, this setting may not be available to select.
a|
Host ports
a|
Do one of the following:

 ** *Select I/O Interface*
+
If the host ports have logged in, you can select host port identifiers from the list. This is the recommended method.

 ** *Manual add*
+
If the host ports have not logged in, look at `/etc/nvme/hostnqn` on the host to find the hostnqn identifiers and associate them with the host definition.
+
You can manually enter the host port identifiers or copy/paste them from the `/etc/nvme/hostnqn` file (one at a time) into the *Host ports* field.
+
You must add one host port identifier at a time to associate it with the host, but you can continue to select as many identifiers that are associated with the host. Each identifier is displayed in the *Host ports* field. If necessary, you also can remove an identifier by selecting the *X* next to it.

+
|===

. Click *Create*.

.Result

After the host is successfully created, SANtricity System Manager creates a default name for each host port configured for the host.

The default alias is ``<Hostname_Port Number>``. For example, the default alias for the first port created for `host IPT is IPT_1`.
