---
permalink: config-linux/nvme-ib-configure-subnet-manager-task.html
sidebar: sidebar
keywords: infiniband, switch, subnet, manager, high, load, avoid, path, loss, opensm, configure
summary: Using an InfiniBand switch to run subnet manager might cause unexpected path loss during high loads. To avoid path loss, configure the subnet manager on one or more of your hosts using opensm.
---
= Configure subnet manager
:icons: font
:imagesdir: ../media/

[.lead]
Using an InfiniBand switch to run subnet manager might cause unexpected path loss during high loads. To avoid path loss, configure the subnet manager on one or more of your hosts using opensm.

.Before you begin

You must be running the latest compatible RHEL 7, SUSE Linux Enterprise Server 12 or 15 service pack operating system. See the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^] for a complete list of the latest requirements.

.Steps

. Use the `ibstat -p` command to find `GUID0` and `GUID1` of the HCA ports. For example:
+
----
# ibstat -p
 0x248a070300a80a80
 0x248a070300a80a81
----

. Depending on your configuration, follow the appropriate steps below:

* *Single switch*. If you are using a single switch, start and enable the `opensm` service, and then add the HCA port identifier values you found in step 1 to the `opensm.conf` file on each port. Repeat for the other port.
+
Edit the /etc/rdma/opensm.conf file to add the identifier for that port:
+
----
opensm -c /etc/rdma/opensm.conf

# The port GUID on which the OpenSM is running
guid 0x248a070300a80a80
----

* *Direct connect method or mulitple switches*. If you are using the direct connect method, or if you have multiple switches, enable subnet manager on each port of the connected HCA on the host:
** Add the following two lines to /etc/rc.d/after.local (for SUSE Linux Enterprise Server 12 and SLES 15 service pack ). Substitute the values you found in step 1 for `GUID0` and `GUID1`. For `P0` and `P1`, use the subnet manager priorities, with 1 being the lowest and 15 the highest:
+
*SLES example*
+
----
 opensm -B -g GUID0 -p P0 -f /var/log/opensm-ib0.log
 opensm -B -g GUID1 -p P1 -f /var/log/opensm-ib1.log
----
+
An example of the command with value substitutions:
+
----
# cat /etc/rc.d/rc.local
 opensm -B -g 0x248a070300a80a80 -p 15 -f /var/log/opensm-ib0.log
 opensm -B -g 0x248a070300a80a81 -p 1 -f /var/log/opensm-ib1.log
----

** Add the following two lines to /etc/rc.d/rc.local (for RHEL 7 ). Substitute the values you found in step 1 for `GUID0` and `GUID1`. For `P0` and `P1`, use the subnet manager priorities, with 1 being the lowest and 15 the highest:
+
*RHEL example*
+
----
 opensm -B -g GUID0 -p P0 -f /var/log/opensm-ib0.log
 opensm -B -g GUID1 -p P1 -f /var/log/opensm-ib1.log
----
+
An example of the command with value substitutions:
+
----
# cat /etc/rc.d/rc.local
 opensm -B -g 0x248a070300a80a80 -p 15 -f /var/log/opensm-ib0.log
 opensm -B -g 0x248a070300a80a81 -p 1 -f /var/log/opensm-ib1.log
----
