---
permalink: config-linux/nvme_ib_configure_storage_connections_task.html
sidebar: sidebar
keywords: controller, nvme, inifniband, port, configure, ip, address, santricity, system, manager, storage, array, connection
summary: If your controller includes an NVMe over InfiniBand port, you can configure the IP address of each port using SANtricity System Manager.
---
= Configure storage array NVMe over InfiniBand connections
:icons: font
:imagesdir: ../media/

[.lead]
If your controller includes an NVMe over InfiniBand port, you can configure the IP address of each port using SANtricity System Manager.

. Select *Hardware*.
. If the graphic shows the drives, click *Show back of shelf*.
+
The graphic changes to show the controllers instead of the drives.

. Click the controller with the NVMe over InfiniBand ports you want to configure.
+
The controller's context menu appears.

. Select *Configure NVMe over InfiniBand ports*.
+
NOTE: The Configure NVMe over InfiniBand ports option appears only if System Manager detects NVMe over InfiniBand ports on the controller.
+
The *Configure NVMe over InfiniBand Ports* dialog box opens.

. In the drop-down list, select the HIC port you want to configure, and then enter the IP address of the port.
. Click *Configure*.
. Repeat steps 5 and 6 for the other HIC ports that will be used.
