---
permalink: config-linux/nvme-roce-assign-volume-task.html
sidebar: sidebar
keywords: assign, volume, namespace, host, cluster, i/o, operation, assignment, access, storage, array
summary: You must assign a volume \(namespace\) to a host or host cluster so it can be used for I/O operations. This assignment grants a host or host cluster access to one or more namespaces in a storage array.
---
= Assign a volume
:icons: font
:imagesdir: ../media/

[.lead]
You must assign a volume (namespace) to a host or host cluster so it can be used for I/O operations. This assignment grants a host or host cluster access to one or more namespaces in a storage array.

=.About this task

Keep these guidelines in mind when you assign volumes:

* You can assign a volume to only one host or host cluster at a time.
* Assigned volumes are shared between controllers in the storage array.
* The same namespace ID (NSID) cannot be used twice by a host or a host cluster to access a volume. You must use a unique NSID.

Assigning a volume fails under these conditions:

* All volumes are assigned.
* The volume is already assigned to another host or host cluster.

The ability to assign a volume is unavailable under these conditions:

* No valid hosts or host clusters exist.
* All volume assignments have been defined.

All unassigned volumes are displayed, but functions for hosts with or without Data Assurance (DA) apply as follows:

* For a DA-capable host, you can select volumes that are either DA-enabled or not DA-enabled.
* For a host that is not DA-capable, if you select a volume that is DA-enabled, a warning states that the system must automatically turn off DA on the volume before assigning the volume to the host.

=.Steps

. Select *Storage* > *Hosts*.
. Select the host or host cluster to which you want to assign volumes, and then click *Assign Volumes*.
+
A dialog box appears that lists all the volumes that can be assigned. You can sort any of the columns or type something in the *Filter* box to make it easier to find particular volumes.

. Select the checkbox next to each volume that you want to assign or select the checkbox in the table header to select all volumes.
. Click *Assign* to complete the operation.

===== Result

After successfully assigning a volume or volumes to a host or a host cluster, the system performs the following actions:

* The assigned volume receives the next available NSID. The host uses the NSID to access the volume.
* The user-supplied volume name appears in volume listings associated to the host.
