---
permalink: config-linux/nvme_fc_setup_host_side_task.html
sidebar: sidebar
keywords: nvme, initiator, configuration, fibre, channel, environment, install, configure, configuring, nvme-cli, package, nvme/fc, host, side, set, up
summary: NVMe initiator configuration in a Fibre Channel environment includes installing and configuring the nvme-cli package, and enabling the NVMe/FC initiator on the host.
---
= Set up NVMe over Fibre Channel on the host side
:icons: font
:imagesdir: ../media/

[.lead]
NVMe initiator configuration in a Fibre Channel environment includes installing and configuring the nvme-cli package, and enabling the NVMe/FC initiator on the host.

These are the instructions for SUSE Linux Enterprise Server 12 SP4 and 32GB FC HBAs.

. Install the nvme-cli package:
+
----

# zypper install nvme-cli
----

. Enable and start the nvmefc-boot-connections service.
+
----
systemctl enable nvmefc-boot-connections.service
----
+
----
systemctl start nvmefc-boot-connections.service
----

. Set `lpfc_enable_fc4_type` to `3` to enable SLES12 SP4 as an NVMe/FC initiator.
+
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_enable_fc4_type=3
----

. Re-build the initrd to get the Emulex change and the boot parameter change.
+
----
# dracut --force
----

. Reboot the host to reconfigure the `Ipfc` driver.
+
----
# reboot
----
+
The host is rebooted and the NVMe/FC initiator is enabled on the host.
+
NOTE: After completing the host side setup, configuration of the NVMe over Fibre Channel ports occur automatically.
