---
permalink: config-linux/overview-concept.html
sidebar: sidebar
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: Review requirements for using the express method to set up an E-Series array and Linux host.
---
= Assumptions
:icons: font
:imagesdir: ../media/

[.lead]
The Linux express method is based on the following assumptions:

[options="header"]
|===
| Component| Assumptions
a|
Hardware
a|

* You have used the Installation and Setup Instructions included with the controller shelves to install the hardware.
* You have connected cables between the optional drive shelves and the controllers.
* You have applied power to the storage system.
* You have installed all other hardware (for example, management station, switches) and made the necessary connections.
* If you are using NVMe over Infiniband, NVMe over RoCE, or NVMe over Fibre Channel, each EF300, EF600, EF570, or E5700 controller contains at least 32 GB of RAM.

a|
Host
a|

* You have made a connection between the storage system and the data host.
* You have installed the host operating system.
* You are not using Linux as a virtualized guest.
* You are not configuring the data (I/O attached) host to boot from SAN.
* You have installed any OS updates as listed under the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool].

a|
Storage management station
a|

* You are using a 1 Gbps or faster management network.
* You are using a separate station for management rather than the data (I/O attached) host.
* You are using out-of-band management, in which a storage management station sends commands to the storage system through the Ethernet connections to the controller.
* You have attached the management station to the same subnet as the storage management ports.

a|
IP addressing
a|

* You have installed and configured a DHCP server.
* You have *not* yet made an Ethernet connection between the management station and the storage system.

a|
Storage provisioning
a|

* You will not use shared volumes.
* You will create pools rather than volume groups.

a|
Protocol: FC
a|

* You have made all host-side FC connections and activated switch zoning.
* You are using NetApp-supported FC HBAs and switches.
* You are using FC HBA driver and firmware versions as listed in the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool].

a|
Protocol: iSCSI
a|

* You are using Ethernet switches capable of transporting iSCSI traffic.
* You have configured the Ethernet switches according to the vendor's recommendation for iSCSI.

a|
Protocol: SAS
a|

* You are using NetApp-supported SAS HBAs.
* You are using SAS HBA driver and firmware versions as listed in the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool].

a|
Protocol: iSER over InfiniBand
a|

* You are using an InfiniBand fabric.
* You are using IB-iSER HBA driver and firmware versions as listed in the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool].

a|
Protocol: SRP over InfiniBand
a|

* You are using an InfiniBand fabric.
* You are using IB-SRP driver and firmware versions as listed in the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool].

a|
Protocol: NVMe over InfiniBand
a|

* You have received the 100G or 200G host interface cards in an EF300, EF600, EF570, or E5700 storage system pre-configured with the NVMe over InfiniBand protocol or the controllers were ordered with standard IB ports and need to be converted to NVMe-oF ports.
* You are using an InfiniBand fabric.
* You are using NVMe/IB driver and firmware versions as listed in the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool].

a|
Protocol: NVMe over RoCE
a|

* You have received the 100G or 200G host interface cards in an EF300, EF600, EF570, or E5700 storage system pre-configured with the NVMe over RoCE protocol or the controllers were ordered with standard IB ports and need to be converted to NVMe-oF ports.
* You are using NVMe/RoCE driver and firmware versions as listed in the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool].

a|
Protocol: NVMe over Fibre Channel
a|

* You have received the 32G host interface cards in an EF300, EF600, EF570, or E5700 storage system pre-configured with the NVMe over Fibre Channel protocol or the controllers were ordered with standard FC ports and need to be converted to NVMe-oF ports.
* You are using NVMe/FC driver and firmware versions as listed in the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool].

|===
*Note:* These express method instructions include examples for SUSE Linux Enterprise Server (SLES) and for Red Hat Enterprise Linux (RHEL). Examples for RHEL are specific to RHEL7.
