---
permalink: config-linux/srp-ib-determine-host-port-guids-task.html
sidebar: sidebar
keywords: host port GUIDs, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: Determine host port GUIDs.
---
= Determine host port GUIDs and making the recommended settings--SRP over Infiniband
:icons: font
:imagesdir: ../media/

[.lead]
The `InfiniBand-diags` package includes commands to display the globally unique ID (GUID) of each InfiniBand (IB) port. Most Linux distributions with OFED/RDMA supported through the included packages also have the `InfiniBand-diags` package, which includes commands to display information about the HCA.

.Steps

. Install the `InfiniBand-diags` package using the operating system's package management commands.
. Run the `ibstat` command to display the port information.
. Record the initiator's GUIDs on the xref:srp-ib-worksheet-concept.adoc[SRP worksheet].
. Select the appropriate settings in the HBA utility.
+
Appropriate settings for your configuration are listed in the Notes column of the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].
