---
permalink: config-linux/srp-ib-configure-network-connections-task.html
sidebar: sidebar
keywords: configure network SRP over IB, configure Linux network, OFED, RDMA, express linux configuration, linux host,
summary: If your configuration uses the SRP over Infiniband protocol, follow the steps in this section.
---
= Configure network connections--SRP over Infiniband
:icons: font
:imagesdir: ../media/

[.lead]
If your configuration uses the SRP over Infiniband protocol, follow the steps in this section.

.What you'll need

To connect the Linux host to the storage array, you must enable the InfiniBand driver stack with the appropriate options. Specific settings might vary between Linux distributions. Check the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^] for specific instructions and additional recommended settings specific to your solution.

.Steps

. Install the OFED/RDMA driver stack for your OS.
+
*SLES*
+
----
# zypper install rdma-core
----
+
*RHEL*
+
----
# yum install rdma-core
----

. Configure OFED/RDMA to load the SRP module.
+
*SLES*
+
----
# zypper install srp_daemon
----
+
*RHEL*
+
----
 # yum install srp_daemon
----
+

. For RHEL 7, set `SRP_LOAD=yes` in the `/etc/rdma/rdma.conf`.

. Create `/etc/modprobe.d/ib_srp.conf` and add the following.
+
----
options ib_srp cmd_sg_entries=255 allow_ext_sg=y indirect_sg_entries=2048
----

 . Add the following to `/etc/srp_daemon.conf`.
+
----
a    max_sect=4096
----

. Edit the following in `/usr/sbin/srp_daemon.sh`.
+
----
rescan_interval=30
----

. For RHEL 7, enable and start the OFED/RDMA service.
+
----
# systemctl enable rdma
# systemctl start rdma
----
+

. Enable and start the SRP daemon.

+
----
# systemctl enable srp_daemon
# systemctl start srp_daemon
----
