---
permalink: config-linux/srp-ib-install-configure-host-utilities-task.html
sidebar: sidebar
keywords: Unified Host Utilities, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries, SMcli, SMdevices
summary: Linux Unified Host Utilities 7.1 includes tools to manage NetApp storage, including failover policies and physical paths.
---
= Install and configure Linux Unified Host Utilities in E-Series (SRP over InfiniBand)
:icons: font
:imagesdir: ../media/

[.lead]
The Linux Unified Host Utilities package includes tools to manage NetApp storage, including failover policies and physical paths.

.Steps

. Use the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^] to determine the appropriate version of Unified Host Utilities to install.
+
The versions are listed in a column within each supported configuration.

. Download the Unified Host Utilities from https://mysupport.netapp.com/site/[NetApp Support^].
+
NOTE: Alternatively, you can use the SMcli command `-identifyDevices` to perform the same functions as the Unified Host Utility tool. The SMcli is included in the SANtricity OS and downloadable through the SANtricity System Manager. For more information on how to download the SMcli through the SANtricity System Manager, refer to the https://docs.netapp.com/us-en/e-series-santricity/sm-settings/download-cli.html[Download command line interface (CLI) topic under the SANtricity System Manager Online Help^].
