---
permalink: config-linux/srp_ib_configure_network_connections_task.html
sidebar: sidebar
keywords: configuration, srp, infiniband, protocol, section, configure, network, connection
summary: If your configuration uses the SRP over Infiniband protocol, follow the steps in this section.
---
= Configure network connections--SRP over Infiniband
:icons: font
:imagesdir: ../media/

[.lead]
If your configuration uses the SRP over Infiniband protocol, follow the steps in this section.

===== Before You Begin

To connect the Linux host to the storage array, you must enable the InfiniBand driver stack with the appropriate options. Specific settings might vary between Linux distributions. Check the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool] for specific instructions and additional recommended settings specific to your solution.

===== Steps

. Install the OFED/RDMA driver stack for your OS.
+
*SLES*
+
----
zypper install rdma-core
----
+
*RHEL*
+
----
yum install rdma-core
----

. Configure OFED/RDMA to load the SRP module.
+
*SLES*
+
----
zypper install srp_daemon
----
+
*RHEL*
+
----
 yum install srp_daemon
----

. In the OFED/RDMA configuration file, set `SRP_LOAD=yes` and `SRP_DAEMON_ENABLE=yes`.
+
The RDMA configuration file is located at the following location:
+
----
/etc/rdma/rdma.conf
----

. Enable and start the OFED/RDMA service.
+
*RHEL 7.x and SLES 12.x or greater*

 ** To enable the InfiniBand modules to load on boot:
+
----
systemctl enable rdma
----

 ** To load the InfiniBand modules immediately:
+
----
systemctl start rdma
----

. Enable the SRP daemon.
+
*RHEL 7.x and SLES 12 or greater*

 ** To enable the SRP daemon to start on boot:
+
----
systemctl enable srp_daemon
----

 ** To start the SRP daemon immediately:
+
----
systemctl start srp_daemon
----

. If you need to modify the SRP configuration, enter the following command to create `/etc/modprobe.d/ib_srp.conf` .
+
----
options ib_srp cmd_sg_entries=255 allow_ext_sg=y indirect_sg_entries=2048
----

 .. Under the `/etc/srp_daemon.conf`, add the following line.
+
----
a
    max_sect=4096
----
