---
permalink: config-linux/task_determine_host_port_guids_srp_over_infiniband_srp_ib.html
sidebar: sidebar
keywords: 
summary: 'The InfiniBand-diags package includes commands to display the globally unique ID \(GUID\) of each InfiniBand \(IB\) port. Most Linux distributions with OFED/RDMA supported through the included packages also have the InfiniBand-diags package, which includes commands to display information about the HCA.'
---
= Determining host port GUIDs and making the recommended settings--SRP over Infiniband
:icons: font
:imagesdir: ../media/

[.lead]
The `InfiniBand-diags` package includes commands to display the globally unique ID (GUID) of each InfiniBand (IB) port. Most Linux distributions with OFED/RDMA supported through the included packages also have the `InfiniBand-diags` package, which includes commands to display information about the HCA.

. Install the `InfiniBand-diags` package using the operating system's package management commands.
. Run the ibstat command to display the port information.
. Record the initiator's GUIDs on the xref:concept_worksheet_srp_over_infiniband.adoc[SRP worksheet].
. Select the appropriate settings in the HBA utility.
+
Appropriate settings for your configuration are listed in the Notes column of the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool].
