---
permalink: maintenance-e2800/batteries_overview_requirements_concept.html
sidebar: sidebar
keywords: E2800 battery fail, E2800 battery, E2800 battery replacement, replace E2800 battery, replacing E2800 battery, E2800, E-Series, eseries
summary: Review E2800 battery replacement requirements and considerations.
---
= Requirements for E2800 battery replacement
:icons: font
:imagesdir: ../media/

[.lead]
Before you replace an E2800 battery, review the requirements and considerations.

== Procedure overview

Each controller canister includes a battery that preserves cached data if the AC power fails. To protect your data, you must replace a failed battery as soon as possible.

. Prepare for replacement, following the appropriate steps for a duplex or simplex configuration.
. Remove the controller canister.
. Remove the failed battery.
. Install the new battery.
. Re-install the controller canister.
. Complete the replacement, following the appropriate steps for a duplex or simplex configuration.

== Requirements

If you plan to replace a failed battery, keep the following requirements in mind.

* You must have installed SANtricity Storage Manager on a management station, so you can use the storage array's command line interface (CLI).
+
If this software has not yet been installed, follow the instructions in the link:../config-linux/index.html[Linux express configuration], link:../config-windows/index.html[Windows express configuration], or link:../config-vmware/index.html[VMware express configuration] to download and install it.

* You must have a replacement battery.
* You must have an ESD wristband, or you have taken other antistatic precautions.
* You should use labels to identify each cable that is connected to the controller canister.

== Recovery Guru alerts

If the Recovery Guru in SANtricity System Manager reports one of following statuses, you must replace the affected battery:

* Battery Failed
* Battery Replacement Required

From SANtricity System Manager, review the details in the Recovery Guru to confirm that there is an issue with a battery and to ensure no other items must be addressed first.

== Duplex or simplex configuration

The steps to replace a battery depend on whether you have one or two controllers, as follows:

[options="header"]
|===
| If your storage array has...| You must...
a|
Two controllers (duplex)
a|

. Take the controller offline.
. Remove the controller canister.
. Replace the battery.
. Replace the controller canister.
. Bring the controller online.

a|
One controller (simplex)
a|

. Stop host I/O operations.
. Power down the controller shelf.
. Remove the controller canister.
. Replace the battery.
. Replace the controller canister.
. Apply power to the controller shelf.

|===
