---
permalink: maintenance-e2800/batteries-prepare-replace-task.html
sidebar: sidebar
keywords: E2800 battery fail, E2800 battery, E2800 battery replacement, replace E2800 battery, replacing E2800 battery, E2800, E-Series, eseries
summary: Prepare for E2800 battery replacement, following the appropriate steps for duplex or simplex.
---
= Prepare to replace E2800 battery
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
The steps to prepare for battery replacement depend on whether you have a duplex configuration (two controllers) or a simplex configuration (one controller).

* For duplex configurations, see <<Place controller offline (duplex)>>.
* For simplex configurations, see <<Power down the controller shelf (simplex)>>.

.What you'll need

* A multipath driver installed on all hosts where volumes are in use; otherwise, ensure that no volumes are in use.

In addition, you should review the link:batteries-overview-requirements-concept.html[Requirements for E2800 battery replacement] before you begin this procedure.

== Place controller offline (duplex)

If you have a duplex configuration, you must place the affected controller offline so you can safely remove the failed battery. The controller that you are not placing offline must be online (in the optimal state).

NOTE: Perform this task only if your storage array has two controllers (duplex configuration).

.Steps


. From SANtricity System Manager, review the details in the Recovery Guru to confirm that there is an issue with a battery and to ensure no other items must be addressed first.
. From the Details area of the Recovery Guru, determine which battery to replace.
. Collect support data for your storage array using either SANtricity System Manager or the Enterprise Management Window's (EMW) script editor.
+
If a problem occurs when you remove a controller, you can use the saved file to restore your configuration.

* To use SANtricity System Manager:
 .. Select menu:Support[Support Center > Diagnostics].
 .. Select *Collect Support Data*.
 .. Click *Collect*.
+
The file is saved in the Downloads folder for your browser with the name, *support-data.7z*.

 * To use SANtricity Storage Manager:

 .. Open the Enterprise Management Window (EMW) for SANtricity Storage Manager on your management station.
 .. Select the storage array.
 .. Select menu:Tools[Execute Script].
 .. Type the following command in the text box.
+
----
save storageArray dbmDatabase sourceLocation=onboard contentType=all file="filename";
----
+
In this command, filename is the file path and file name to which you want to save the database. Enclose the file name in double quotation marks (" "). For example:
+
----
 file="C:\Program Files\CLI\logs\dbmdata.zip"
----
+
This command does not automatically append a file extension to the saved file. You must specify a file extension when entering the file name.

 .. Select menu:Tools[Verify and Execute].

. If the controller is not already offline, take it offline now using either SANtricity System Manager or the Enterprise Management Window's (EMW) script editor:
+
* To use SANtricity System Manager:

  .. Select *Hardware*.
  .. If the graphic shows the drives, select *Show back of shelf* to show the controllers.
  .. Select the controller that you want to place offline.
  .. From the context menu, select *Place offline*, and confirm that you want to perform the operation.
+
NOTE: If you are accessing SANtricity System Manager using the controller you are attempting to take offline, a SANtricity System Manager "Unavailable" message is displayed. Select *Connect to an alternate network connection* to automatically access SANtricity System Manager using the other controller.

* To use script editor in the EMW:

  .. Open the Enterprise Management Window (EMW) in SANtricity Storage Manager on your local host.
  .. Select the storage array.
  .. Select menu:Tools[Execute Script].
  .. Type one of the following commands in the text box.
+
*For controller A:* `set controller [a] availability=offline`
+
*For controller B:* `set controller [b] availability=offline`
+
  .. Select menu:Tools[Verify and Execute].
The system attempts to take the controller offline.

. Wait for SANtricity System Manager to update the controller's status to offline.
. Go to  link:batteries-remove-controller-canister-task.html[Remove E2800 controller canister].
+
CAUTION: Do not begin any other operations until after the status has been updated.

== Power down the controller shelf (simplex)

If you have a simplex configuration, power down the controller shelf so you can safely remove the failed battery.

NOTE: Perform this task only if your storage array has one controller (simplex configuration).

.Steps

. Review link:batteries-overview-requirements-concept.html[Requirements for E2800 battery replacement].
. Collect support data for your storage array using either SANtricity System Manager or the Enterprise Management Window's (EMW) script editor.
+
If a problem occurs when you remove a controller, you can use the saved file to restore your configuration.

* To use SANtricity System Manager:
 .. Select menu:Support[Support Center > Diagnostics].
 .. Select *Collect Support Data*.
 .. Click *Collect*.
+
The file is saved in the Downloads folder for your browser with the name, *support-data.7z*.

 * To use SANtricity Storage Manager:

 .. Open the Enterprise Management Window (EMW) for SANtricity Storage Manager on your management station.
 .. Select the storage array.
 .. Select menu:Tools[Execute Script].
 .. Type the following command in the text box.
+
----
save storageArray dbmDatabase sourceLocation=onboard contentType=all file="filename";
----
+
In this command, filename is the file path and file name to which you want to save the database. Enclose the file name in double quotation marks (" "). For example:
+
----
 file="C:\Program Files\CLI\logs\dbmdata.zip"
----
+
This command does not automatically append a file extension to the saved file. You must specify a file extension when entering the file name.

 .. Select menu:Tools[Verify and Execute].

. Ensure that no I/O operations are occurring between the storage array and all connected hosts. For example, you can perform these steps:
 .. Stop all processes that involve the LUNs mapped from the storage to the hosts.
 .. Ensure that no applications are writing data to any LUNs mapped from the storage to the hosts.
 .. Unmount all file systems associated with volumes on the array.
+
NOTE: The exact steps to stop host I/O operations depend on the host operating system and the configuration, which are beyond the scope of these instructions. If you are not sure how to stop host I/O operations in your environment, consider shutting down the host.
+
CAUTION: *Possible data loss* -- If you continue this procedure while I/O operations are occurring, you might lose data.
. Wait for any data in cache memory to be written to the drives.
+
The green Cache Active LED on the back of the controller is on when cached data needs to be written to the drives. You must wait for this LED to turn off.

. From the home page of SANtricity System Manager, select *View Operations in Progress*.
. Confirm that all operations have completed before continuing with the next step.
. Turn off both power switches on the controller shelf.
. Wait for all LEDs on the controller shelf to turn off.
. Go to link:batteries-remove-controller-canister-task.html[Remove E2800 controller canister].
