---
permalink: maintenance-e2800/batteries_prepare_replace_task.html
sidebar: sidebar
keywords: 
summary: ''
---
= Prepare to replace battery
:icons: font
:imagesdir: ../media/

[.lead]
The steps to prepare for battery replacement depend on whether you have a duplex configuration (two controllers) or a simplex configuration (one controller). If you have a duplex configuration, you must take the affected controller offline or, if you have a simplex configuration, you must stop host I/O operations and power down the controller shelf.

== Place controller offline (duplex)

[.lead]
If you have a duplex configuration, you must place the affected controller offline so you can safely remove the failed battery. You must back up the configuration and collect support data first. Then, you can take the affected controller offline.

* Your storage array must have two controllers. The controller that you are not placing offline must be online (in the optimal state).
* Make sure that no volumes are in use or that you have a multipath driver installed on all hosts using these volumes.

Perform this task only if your storage array has two controllers (duplex configuration).

. From SANtricity System Manager, review the details in the Recovery Guru to confirm that there is an issue with a battery and to ensure no other items must be addressed first.
. From the Details area of the Recovery Guru, determine which battery to replace.
. Back up the storage array's configuration database.
+
If a problem occurs when you remove a controller, you can use the saved file to restore your configuration.

 .. Open the Enterprise Management Window (EMW) for SANtricity Storage Manager on your management station.
 .. Select the storage array.
 .. Select *Tools* > *Execute Script*.
 .. Type the following command in the text box.
+
----
save storageArray dbmDatabase sourceLocation=onboard contentType=all file="filename";
----
+
In this command, filename is the file path and file name to which you want to save the database. Enclose the file name in double quotation marks (" "). For example:
+
----
 file="C:\Program Files\CLI\logs\dbmdata.zip"
----
+
This command does not automatically append a file extension to the saved file. You must specify a file extension when entering the file name.

 .. Select *Tools* > *Verify and Execute*.

. Collect support data for your storage array using SANtricity System Manager.
 .. Select *Support* > *Support Center* > *Diagnostics*.
 .. Select *Collect Support Data*.
 .. Click *Collect*.
The file is saved in the Downloads folder for your browser with the name support-data.7z.
. If the controller is not already offline, take it offline now using either SANtricity System Manager or the Enterprise Management Window's (EMW) script editor:
 ** To use SANtricity System Manager:
  ... Select *Hardware*.
  ... If the graphic shows the drives, select *Show back of shelf* to show the controllers.
  ... Select the controller that you want to place offline.
  ... From the context menu, select *Place offline*, and confirm that you want to perform the operation.
*Note:* If you are accessing SANtricity System Manager using the controller you are attempting to take offline, a SANtricity System Manager Unavailable message is displayed. Select *Connect to an alternate network connection* to automatically access SANtricity System Manager using the other controller.
 ** To use script editor in the EMW:
  ... Open the Enterprise Management Window (EMW) in SANtricity Storage Manager on your local host.
  ... Select the storage array.
  ... Select *Tools* > *Execute Script*.
  ... Type one of the following commands in the text box.
+
----
**For controller A:** set controller [a] availability=offline
----
+
----
**For controller B:** set controller [b] availability=offline
----

  ... Select *Tools* > *Verify and Execute*.
The system attempts to take the controller offline.
. Wait for SANtricity System Manager to update the controller's status to offline.
+
IMPORTANT: Do not begin any other operations until after the status has been updated.

Go to .

== Power down the controller shelf (simplex)

[.lead]
If you have a simplex configuration, you power down the controller shelf so you can safely remove the failed battery. You must back up the configuration and collect support data first. Then, you can stop host I/O operations and power down the controller shelf.

* You have reviewed the details in the Recovery Guru to confirm that there is an issue with a battery and to ensure no other items must be addressed first.

Perform this task only if your storage array has one controller (simplex configuration).

. Back up the storage array's configuration database.
+
If a problem occurs when you remove a controller, you can use the saved file to restore your configuration.

 .. Open the Enterprise Management Window (EMW) for SANtricity Storage Manager on your management station.
 .. Select the storage array.
 .. Select *Tools* > *Execute Script*.
 .. Type the following command in the text box.
+
----
save storageArray dbmDatabase sourceLocation=onboard contentType=all file="filename";
----
+
In this command, filename is the file path and file name to which you want to save the database. Enclose the file name in double quotation marks (" "). For example:
+
----
 file="C:\Program Files\CLI\logs\dbmdata.zip"
----
+
This command does not automatically append a file extension to the saved file. You must specify a file extension when entering the file name.

 .. Select *Tools* > *Verify and Execute*.

. Collect support data for your storage array using SANtricity System Manager.
 .. Select *Support* > *Support Center* > *Diagnostics*.
 .. Select *Collect Support Data*.
 .. Click *Collect*.
The file is saved in the Downloads folder for your browser with the name support-data.7z.
. Ensure that no I/O operations are occurring between the storage array and all connected hosts. For example, you can perform these steps:
 ** Stop all processes that involve the LUNs mapped from the storage to the hosts.
 ** Ensure that no applications are writing data to any LUNs mapped from the storage to the hosts.
 ** Unmount all file systems associated with volumes on the array.
*Note:* The exact steps to stop host I/O operations depend on the host operating system and the configuration, which are beyond the scope of these instructions. If you are not sure how to stop host I/O operations in your environment, consider shutting down the host.

+
IMPORTANT: *Possible data loss* -- If you continue this procedure while I/O operations are occurring, you might lose data.
. Wait for any data in cache memory to be written to the drives.
+
The green Cache Active LED on the back of the controller is on when cached data needs to be written to the drives. You must wait for this LED to turn off.

. From the home page of SANtricity System Manager, select *View Operations in Progress*.
. Confirm that all operations have completed before continuing with the next step.
. Turn off both power switches on the controller shelf.
. Wait for all LEDs on the controller shelf to turn off.

Go to .
