---
permalink: maintenance-e2800/how-to-send-comments-concept.html
sidebar: sidebar
keywords: improve, quality, documentation, send, feedback, automatic, notification, production-level, ga, fcs, release, exist, document
summary: You can help us to improve the quality of our documentation by sending us your feedback. You can receive automatic notification when production-level \(GA/FCS\) documentation is initially released or important changes are made to existing production-level documents.
---
= How to send comments about documentation and receive update notifications
:icons: font
:imagesdir: ../media/

[.lead]
You can help us to improve the quality of our documentation by sending us your feedback. You can receive automatic notification when production-level (GA/FCS) documentation is initially released or important changes are made to existing production-level documents.

If you have suggestions for improving this document, send us your comments by email.

link:mailto:doccomments@netapp.com[doccomments@netapp.com]

To help us direct your comments to the correct division, include in the subject line the product name, version, and operating system.

If you want to be notified automatically when production-level documentation is released or important changes are made to existing production-level documents, follow Twitter account @NetAppDoc.

You can also contact us in the following ways:

* NetApp, Inc., 1395 Crossman Ave., Sunnyvale, CA 94089 U.S.
* Telephone: +1 (408) 822-6000
* Fax: +1 (408) 822-4501
* Support telephone: +1 (888) 463-8277
