---
sidebar: sidebar
permalink: manage-storage.html
keywords: online help, System Manager, Unified Manager
summary: Manage storage
---

= Manage E-Series storage systems
:icons: font
:imagesdir: ./media/

[.lead]
Use the links below to access documentation that describes how to configure, manage, and monitor storage objects and E-Series storage systems. The links take you to a different documentation site.

== Online help for System Manager
Access the https://docs.netapp.com/us-en/e-series-santricity/system-manager/index.html[SANtricity System Manager online help^], where you can find information about how to plan, configure, manage, and troubleshoot your storage array.

== Online help for Unified Manager
Access the https://docs.netapp.com/us-en/e-series-santricity/unified-manager/index.html[SANtricity Unified Manager online help^], where you can learn how to execute storage management commands on multiple network storage arrays.

== Command reference
Access the https://docs.netapp.com/us-en/e-series-cli/index.html[Command reference^], where you can learn how to configure and monitor your storage arrays using command line interface (CLI) commands.
