---
permalink: getting-started/learn_terms_concept.html
sidebar: sidebar
keywords: learn, term, e-series, terminology
summary: 'Learn more about the terms used in E-Series.'
---
= E-Series terminology
:icons: font
:imagesdir: ../media/

[.lead]
Learn more about the terms used in E-Series.

[options="header"]
|===
| Term| Description
a|
controller
a|
A controller consists of a board, firmware, and software. It controls the drives and implements the functions.
a|
duplex/simplex configurations
a|
Duplex is a two-controller module configuration within the storage array. Simplex is a single-controller module configuration.

a|
HDD
a|
Hard disk drives (HDDs) are data storage devices that use rotating metal platters with a magnetic coating.
a|
HIC
a|
A host interface card (HIC) connects the array to the host. It can optionally be installed within a controller canister.

a|
IB
a|
InfiniBand (IB) is a communications standard for data transmission between high-performance servers and storage systems.
a|
IOPS
a|
IOPS is input/output operations per second.
a|
mirroring
a|
Mirroring is the replication of data volumes onto separate storage arrays to ensure continuous availability.
a|
pool
a|
A pool is a set of drives that is logically grouped. You can use a pool to create one or more volumes accessible to a host.
a|
power/fan canister
a|
A power/fan canister is an assembly that slides into a shelf. It includes a power supply and an integrated fan.
a|
rack unit (U)
a|
A rack unit (abbreviated U) is a unit of measure defined as 44.50 millimetres (1.75 in).
a|
SAS
a|
Serial Attached SCSI (SAS) is a point-to-point serial protocol that links controllers directly to disk drives.
a|
RoCE
a|
RDMA over Converged Ethernet (RoCE) is a network protocol that allows remote direct memory access (RDMA) over an Ethernet network.
a|
shelf
a|
A shelf is an enclosure installed in a cabinet or rack. It contains the hardware components for the storage array. There are two types of shelves: a controller shelf and a drive shelf. A controller shelf includes controllers and drives. A drive shelf includes input/output modules (IOMs) and drives.
a|
snapshot
a|
A snapshot image is a logical copy of volume data, captured at a particular point-in-time. Like a restore point, snapshot images allow you to roll back to a known good data set.
a|
SSD
a|
Solid-state disks (SSDs) are data storage devices that use solid state memory (flash) to store data persistently. SSDs emulate conventional hard drives, and are available with the same interfaces that hard drives use.
a|
storage array
a|
A storage array includes shelves, controllers, drives, software, and firmware.
a|
volume
a|
A volume is a container in which applications, databases, and file systems store data. It is the logical component created for the host to access storage on the storage array.
a|
workload
a|
A workload is a storage object that supports an application. For some applications, System Manager configures the workload to contain volumes with similar underlying volume characteristics. These volume characteristics are optimized based on the type of application the workload supports.

|===
