---
permalink: config-vmware/concept_overview.html
sidebar: sidebar
keywords: 
summary: 'The "express method" for installing your storage array and accessing SANtricity System Manager is appropriate for setting up a standalone VMware host to an E-Series storage system. It is designed to get the storage system up and running as quickly as possible with minimal decision points.'
---
= Overview
:icons: font
:imagesdir: ../media/

[.lead]
The "express method" for installing your storage array and accessing SANtricity System Manager is appropriate for setting up a standalone VMware host to an E-Series storage system. It is designed to get the storage system up and running as quickly as possible with minimal decision points.

NOTE: The configuration that the express method provides might not meet the needs of your production environment. For advanced options regarding installation and configuration of the storage system for VMware usage with the iSCSI protocol, see thehttps://www.netapp.com/us/media/tr-4789.pdf[VMware Configuration Guide for E-Series SANtricity iSCSI Integration with ESXi 6.X Technical Report].

The express method includes the following steps:

. Setting up one of the following communication environments:
 ** NVMe over Fibre Channel
 ** Fibre Channel (FC)
 ** iSCSI
 ** SAS
. Creating logical volumes on the storage array.
. Making the volumes available to the data host.

This guide is based on the following assumptions:

|===
| Component| Assumptions
a|
Hardware
a|

* You have used the Installation and Setup Instructions included with the controller shelves to install the hardware.
* You have connected cables between the optional drive shelves and the controllers.
* You have applied power to the storage system.
* You have installed all other hardware (for example, management station, switches) and made the necessary connections.

a|
Host
a|

* You have made a connection between the storage system and the data host.
* You have installed the host operating system.
* You are not using VMware as a virtualized guest.
* You are not configuring the data (I/O attached) host to boot from SAN.

a|
Storage management station
a|

* You are using a 1 Gbps or faster management network.
* You are using a separate station for management rather than the data (I/O attached) host.
* You are using out-of-band management, in which a storage management station sends commands to the storage system through the Ethernet connections to the controller.
* You have attached the management station to the same subnet as the storage management ports.

a|
IP addressing
a|

* You have installed and configured a DHCP server.
* You have *not* yet made an Ethernet connection between the management station and the storage system.

a|
Storage provisioning
a|

* You will not use shared volumes.
* You will create pools rather than volume groups.

a|
Protocol: FC
a|

* You have made all host-side FC connections and activated switch zoning.
* You are using NetApp-supported FC HBAs and switches.
* You are using FC HBA driver and firmware versions as listed in the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool].

a|
Protocol: NVMe over Fibre Channel
a|

* You have made all host-side FC connections and activated switch zoning.
* You are using NetApp-supported FC HBAs and switches.
* You are using FC HBA driver and firmware versions as listed in the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool].

a|
Protocol: iSCSI
a|

* You are using Ethernet switches capable of transporting iSCSI traffic.
* You have configured the Ethernet switches according to the vendor's recommendation for iSCSI.

a|
Protocol: SAS
a|

* You are using NetApp-supported SAS HBAs.
* You are using SAS HBA driver and firmware versions as listed in the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool].

|===
If these assumptions are not correct for your installation, or if you want more conceptual background information, see the https://www.netapp.com/us/media/tr-4789.pdf[VMware Configuration Guide for E-Series SANtricity iSCSI Integration with ESXi 6.X Technical Report]
