---
permalink: config-vmware/discover_storage_host_task.html
sidebar: sidebar
keywords: discover storage ESXi, express vmware configuration, software configuration, vmware host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: After assigning volumes to the host, you perform a rescan so that the host detects and configures the volumes for multipathing.
---
= Discover storage on the host
:icons: font
:imagesdir: ../media/

[.lead]
After assigning volumes to the host, you perform a rescan so that the host detects and configures the volumes for multipathing.

===== Before you begin

By default, an ESXi host automatically performs a rescan every five minutes. A volume might appear between the time you create it and assign it to a host, before you perform a manual rescan. Regardless, you can perform a manual rescan to ensure all volumes are configured properly.

===== Steps

. Create one or more volumes and assign them to the ESXi host.
. If using a vCenter Server, add the host to the server's inventory.
. Use the vSphere Client or the vSphere Web Client to connect directly to the vCenter Server or to the ESXi host.
. For instructions on how to perform a rescan of the storage on an ESXi host, search for the VMware Knowledge Base article on this topic.
