---
permalink: config-vmware/index.html
sidebar: sidebar
keywords: express vmware configuration, software configuration, vmware host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: Use the express configuration for a VMware host with an E-Series system.
---
= VMware express configuration overview
:icons: font
:imagesdir: ../media/

[.lead]
The VMware express method for installing your storage array and accessing SANtricity System Manager is appropriate for setting up a standalone VMware host to an E-Series storage system. It is designed to get the storage system up and running as quickly as possible with minimal decision points.

=== Procedure overview

The express method includes the following steps.

. Setting up one of the following communication environments:
 ** NVMe over Fibre Channel
 ** Fibre Channel (FC)
 ** iSCSI
 ** SAS
. Creating logical volumes on the storage array.
. Making the volumes available to the data host.

=== Find more information

* Online help -- Describes how to use SANtricity System Manager to complete configuration and storage management tasks. It is available within the product.
* https://kb.netapp.com/app/[NetApp Knowledgebase] (a database of articles) -- Provides troubleshooting information, FAQs, and instructions for a wide range of NetApp products and technologies.
* VMware Configuration Maximums -- Describes how to configure virtual and physical storage to stay within the allowed maximums that ESX/ESXi supports.
+
** vSphere 6._x_ - search vmware.com for "vsphere 6._x_ configuration maximums."
+
** vSphere 7._x_ - search vmware.com for "vsphere 7._x_ configuration maximums."

* vmware Docs -- https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-9AEE5F4D-0CB8-4355-BF89-BB61C5F30C70.html[Requirements and limitations of VMware NVMe storage].
* vmware.com -- Search for ESXi vCenter Server documentation.
