---
permalink: config-vmware/overview-concept.html
sidebar: sidebar
keywords: express vmware configuration, software configuration, vmware host, E2800, E5700, EF300, EF600, EF50, EF80, E4000, E-Series, eseries
summary: Review requirements for using the express method to set up an E-Series array and VMware host.
---
= Assumptions (E-Series and VMware)
:icons: font
:imagesdir: ../media/

[.lead]
The VMware express method is based on the following assumptions:

[options="header"]
|===
| Component| Assumptions
a|
Hardware
a|

* You have used the Installation and Setup Instructions included with the controller shelves to install the hardware.
* You have connected cables between the optional drive shelves and the controllers.
* You have applied power to the storage system.
* You have installed all other hardware (for example, management station, switches) and made the necessary connections.

a|
Host
a|

* You have made a connection between the storage system and the data host.
* You have installed the host operating system.
* You are not using VMware as a virtualized guest.
* You are not configuring the data (I/O attached) host to boot from SAN.

a|
Storage management station
a|

* You are using a 1 Gbps or faster management network.
* You are using a separate station for management rather than the data (I/O attached) host.
* You are using out-of-band management, in which a storage management station sends commands to the storage system through the Ethernet connections to the controller.
* You have attached the management station to the same subnet as the storage management ports.

a|
IP addressing
a|

* You have installed and configured a DHCP server.
* You have *not* yet made an Ethernet connection between the management station and the storage system.

a|
Storage provisioning
a|

* You will not use shared volumes.
* You will create pools rather than volume groups.
* Volumes must be set to utilize 512 byte emulation (512e) when using 4096 byte drives to ensure compatibility with VMware. Refer to the SANtricity System Manager online help for more information on setting a volume to use 512-byte emulation (512e).

a|
Protocol: Fibre Channel (FCP)
a|

* You have made all host-side FC connections and activated switch zoning.
* You are using NetApp-supported FC HBAs and switches.
* You are using FC HBA driver and firmware versions as listed in the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].

a|
Protocol: NVMe over Fibre Channel
a|

* You have made all host-side FC connections and activated switch zoning.
* You are using NetApp-supported FC HBAs and switches.
* You are using FC HBA driver and firmware versions as listed in the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].

a|
Protocol: iSCSI
a|

* You are using Ethernet switches capable of transporting iSCSI traffic.
* You have configured the Ethernet switches according to the vendor's recommendation for iSCSI.

a|
Protocol: SAS
a|

* You are using NetApp-supported SAS HBAs.
* You are using SAS HBA driver and firmware versions as listed in the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].

a|
Protocol: NVMe over RoCE (RDMA over Converged Ethernet)
a|

* You are using Ethernet switches capable of RDMA traffic
* You have configured the Ethernet switches for lossless networking using Differentiated Services Code Point (DSCP) based Priority Flow Control (PFC)
* You are using RDMA driver and firmware versions as listed in the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].

a|
Protocol: NVMe over TCP
a|

* You are using Ethernet switches capable of TCP traffic
* You have configured the Ethernet switches according to the vendor's recommendation for TCP.
* You are using network driver and firmware versions as listed in the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].

|===
If these assumptions are not correct for your installation, or if you want more conceptual background information, see the following technical report: https://www.netapp.com/pdf.html?item=/media/17017-tr4789.pdf[VMware Configuration Guide for E-Series SANtricity iSCSI Integration with ESXi 6.X^]
