---
permalink: config-vmware/reference_where_to_find_additional_information_vmware.html
sidebar: sidebar
keywords: resource, list, additional, information, online, help, santricity, system, manager,
summary: Use the resources listed here if you need additional information. You can also use the online help for SANtricity System Manager.
---
= Where to find additional information
:icons: font
:imagesdir: ../media/

[.lead]
Use the resources listed here if you need additional information. You can also use the online help for SANtricity System Manager.

* Online help describes how to use SANtricity System Manager to complete configuration and storage management tasks. It is available within the product.
* https://kb.netapp.com/app/[NetApp Knowledgebase] (a database of articles) provides troubleshooting information, FAQs, and instructions for a wide range of NetApp products and technologies.
* *VMware Configuration Maximums* describe how to configure virtual and physical storage to stay within the allowed maximums that ESX/ESXi supports.
+
vSphere 6._x_ - search vmware.com for "vsphere 6._x_ configuration maximums."
+
vSphere 7._x_ - search vmware.com for "vsphere 7._x_ configuration maximums."

* https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-9AEE5F4D-0CB8-4355-BF89-BB61C5F30C70.html[Requirements and limitations of VMware NVMe storage]
* Other VMware Publications. Search vmware.com for ESXi vCenter Server documentation.
