---
permalink: config-vmware/verify-vmware-config-support-task.html
sidebar: sidebar
keywords: express vmware configuration, software configuration, vmware host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: Verify that the VMware configuration is supported.
---
= Verify the VMware configuration is supported
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
To ensure reliable operation, you create an implementation plan and then use the NetApp Interoperability Matrix Tool (IMT) to verify that the entire configuration is supported.

=.Steps

. Go to the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool].
. Click the *Solution Search* tile.
. In the menu:Protocols[SAN Host] area, click the *Add* button next to *E-Series SAN Host*.
. Click *View Refine Search Criteria*.
+
The Refine Search Criteria section is displayed. In this section you may select the protocol that applies, as well as other criteria for the configuration such as Operating System, NetApp OS, and Host Multipath driver. Select the criteria you know you want for your configuration, and then see what compatible configuration elements apply. As necessary, make the updates for your operating system and protocol that are prescribed in the tool. Detailed information for your chosen configuration is accessible on the View Supported Configurations page by clicking the right page arrow.

. As necessary, make the updates for your operating system and protocol as listed in the table.
+
[options="header"]
|===
| Operating system updates| Protocol| Protocol-related updates
.3+a|

 ** You might need to install out-of-box drivers to ensure proper functionality and supportability. You can install HBA drivers using the ESXi shell or a remote SSH connection to the ESXi host. To access the host using either of those methods, you must enable the ESXi shell and SSH access. For more information about the ESXi shell, refer to the VMware Knowledge Base regarding using the ESXi shell in ESXi. For installation commands, refer to the instructions that accompany the HBA drivers.
 ** Each HBA vendor has specific methods for updating boot code and firmware. Some of these methods could include the use of a vCenter plugin or the installation of CIM provider on the ESXi host. vCener plugins can be used to obtain information about the a vendor's specific HBA. Refer to the support section of the vendor's website to obtain the instructions and software necessary to update the HBA boot code or firmware. Refer to the _VMware Compatibility Guide_ or the HBA vendor's website to obtain the correct boot code or firmware.

a|
FC
a|
Host bus adapter (HBA) driver, firmware, and bootcode
a|
iSCSI
a|
Network interface card (NIC) driver, firmware and bootcode
a|
SAS
a|
Host bus adapter (HBA) driver, firmware, and bootcode
|===
