---
sidebar: sidebar
permalink: san-spvc-ic_overview.html
keywords:
summary:
---

= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-06-30 09:58:12.255053
//

[.lead]
The Plugin for vCenter provides integrated management of E-Series storage arrays from within a VMware vSphere Client session. The vSphere Client is a single management interface that you can use to manage the VMware infrastructure and all your day-to-day storage needs.

The following functions are available in the Plugin for vCenter:

* View and manage discovered storage arrays in the network.
* Perform batch operations on groups of multiple storage arrays.
* Perform upgrades on the software OS.
* Import settings from one storage array to another.
* Configure volumes, SSD cache, hosts, host clusters, pools, and volume groups.
* Launch the System Manager interface for additional management tasks on an array.

[NOTE]
The plugin is not a direct replacement for the SANtricity System Manager software. System Manager is still required for performing certain storage administration tasks on a single array.

The plugin requires a VMware vCenter Server Appliance deployed in the VMware environment and an application host to install and run the plugin webserver.

Refer to the following figure for more information on communications in the vCenter environment.
