---
sidebar: sidebar
permalink: san-spvc-ic_login_and_navigation.html
keywords:
summary:
---

= Login and Navigation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-06-30 09:58:12.295268
//

[.lead]
Follow the instructions in this section to log in to the plugin and to navigate the user interface.

. Before you log in to the plugin, make sure you are using one of the following browsers:

** Google Chrome 75 or later
** Mozilla Firefox 60 or later
** Microsoft Edge 44 or later

. Log in to the vSphere Client under the user account that has read/write privileges for the plugin. 
. From the vSphere Client Home page, click *SANtricity Storage Plugin for vCenter*. 
+
The plugin opens within a vSphere Client window. The plugin's main page opens to Manage-All.

. Access storage management tasks from the navigation sidebar on the left:

** Manage – Discover storage arrays in your network, open System Manager for an array, import settings from one array to multiple arrays, manage array groups, upgrade the OS software, and provision storage.
** Certificate Management – Manage certificates to authenticate between browsers and clients.
** Operations – View the progress of batch operations, such as importing settings from one array to another.
** Support – View technical support options, resources, and contacts.
