---
sidebar: sidebar
permalink: san-spvc-ic_storage_array_discovery.html
keywords: E-Series, eseries, vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter, VMware vSphere Client, vCenter plugin array discovery
summary: Use the Plugin for vCenter interface to discover the IP addresses of arrays in your network.
---

= Storage array discovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-06-30 09:58:12.302428
//

[.lead]
To display and manage storage resources, you must use the plugin interface to discover the IP addresses of arrays in your network.

=== Enter network addresses for discovery

. Before you begin, make sure that:

** You know the network IP addresses (or range of addresses) of the array controllers.
** The storage arrays are correctly set up and configured, and you know the storage array login credentials (user name and password).

. From the Manage page, select *Add/Discover*.
+
The Enter Network Address Range dialog box appears.

. Do one of the following:

** To discover one array, select the *Discover a single storage array* radio button, and then enter the IP address for one of the controllers in the storage array.
** To discover multiple storage arrays, select the *Discover all storage arrays within a network range* radio button, and then enter the starting network address and ending network address to search across your local sub-network.

. Click *Start Discovery*.
+
As the discovery process begins, the dialog box displays the storage arrays as they are discovered. The discovery process might take several minutes to complete.
+
If no manageable arrays are discovered, verify that the storage arrays are properly connected to your network and their assigned addresses are within range. Click *New Discovery Parameters* to return to the Add/Discover page.

. Select the checkbox next to any storage array that you want to add to your management domain.
+
The system performs a credential check on each array that you are adding to the management domain. You might need to resolve any issues with untrusted certificates before proceeding.

. Click *Next* to proceed to the next step in the wizard.
+
If the storage arrays have valid certificates, go to “Provide passwords” on page 9.
+
If any storage arrays do not have valid certificates, the Step 2: Resolve Self-Signed Certificates dialog box appears. Go to the section <xref>, “Resolve untrusted certificates during discovery.”
+
If you want to import CA-signed certificates, cancel out of the discovery wizard and click *Certificate Management* from the left panel. Refer to the online help for further instructions.

=== Resolve untrusted certificates during discovery

You must resolve any certificate issues before proceeding with the discovery process.

. If the Resolve Self-Signed Certificates dialog box opens, review the information displayed for the untrusted certificates. For more information, you can also click the ellipses at the far end of the table and select *View* from the pop-up menu.
. Do one of the following:

** If you trust the connections to the discovered storage arrays, click *Next* and then click *Yes* to confirm and continue to the next dialog in the wizard. The self-signed certificates are marked as trusted and the storage arrays will be added to the plugin.
** If you do not trust the connections to the storage arrays, select *Cancel* and validate each storage array's security certificate strategy before adding any of them.

. Click *Next* to proceed to the next step in the wizard.

=== Provide passwords

As the last step for discovery, you must enter the passwords for the storage arrays that you want to add to your management domain.

. For each discovered array, enter its admin password in the fields.
. Click *Finish*.
+
It can take several minutes for the system to connect to the specified storage arrays. When the process is finished, the storage arrays are added to your management domain and associated with the selected group (if specified).
