---
sidebar: sidebar
permalink: vcenter-plugin/san-spvc-ic-installation.html
keywords: install vCenter plugin, installing vCenter plugin, vCenter plugin,
summary: Install or upgrade the SANtricity Storage Plugin for vCenter.
---

= Install or upgrade the SANtricity Storage Plugin for vCenter
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/


[.lead]
Follow these steps to install the Storage Plugin for vCenter and verify the plugin registration. You can also upgrade the plugin using these instructions.

== Review installation prerequisites

Be sure that your systems meet the requirements in link:san-spvc-ic-reqs.html[Review installation and upgrade requirements].

NOTE: The upgrade process does not preserve the *vcenter.properties* files. If you are upgrading, you must unregister the plugin prior to the upgrade. Once the upgrade is successful, you can then register the plugin again to the vCSA.

== Install the plugin software

To install the plugin software:

. Copy the installer file to the host that will be used as the application server, and then access the folder where you downloaded the installer.
. Double-click the installation file:
+
`santricity_storage_vcenterplugin-windows_x64-- nn.nn.nn.nnnn.exe`
+
In the above filename, `nn.nn.nn.nnnn` represents the version number.

. When the installation starts, follow the on-screen prompts to enable several features and enter some configuration parameters. If necessary, you can change any of these selections later in the configuration files.
+
NOTE: During an upgrade, you are not prompted for configuration parameters.
+
NOTE: During installation, you are prompted for certificate validation. Keep the checkbox selected if you want to enforce certificate validation between the plugin and the storage arrays. With this enforcement, the storage array certificates are checked to be trusted against the plugin. If the certificates are not trusted, then they are not allowed to be added to the plugin. If you want to override certificate validation, deselect the checkbox so that all storage arrays can be added to the plugin using self-signed certificates. To learn more about certificates, refer to the online help available from the plugin interface. 
+
. When the Webserver Started message appears, click *OK* to complete the installation, and then click *Done*.
+
. Verify that the application server was installed successfully by running the *services.msc* command.
. Verify that the Application Server (vCP) service, *NetApp SANtricity Storage Plugin for vCenter*,  was installed and the service has started.
+
NOTE: If necessary, you can change the Certificate Validation and Web Service Port settings after installation. From the installation directory, open the wsconfig.xml file. To remove the Certificate Validation on storage arrays, change the `env` key, `trust.all.arrays`, to `true`. To change the Web Services port, modify the `sslport` value to the desired port value ranging from 0-65535. Ensure that the port number used is not binding to another process. When you are done, save the changes and restart the plugin webserver. If the port value of the plugin webserver is changed after registering the plugin to a vCSA, then you must unregister and re-register the plugin so the vCSA is communicating on the changed port to the plugin webserver.


== Register the plugin with a vCenter Server Appliance

After the plugin software is installed, register the plugin with a vCSA.

[NOTE]
The plugin can only be registered to one vCSA at a time. To register to a different vCSA, you must unregister the plugin from the current vCSA and uninstall it from the application host. You can then re-install the plugin and register it to the other vCSA.

. Open a prompt through the command line and navigate to the following directory:
+
`<install directory>\vcenter-register\bin`

. Execute the *vcenter-register.bat* file:
`vcenter-register.bat ^
    -action registerPlugin ^
    -vcenterHostname <vCenter FQDN> ^
    -username <Administrator username> ^`

. Verify that the script was successful.

The logs are saved to `%install_dir%/working/logs/vc-registration.log`.

== Verify the plugin registration

After the plugin is installed and the registration script has executed, verify that the plugin successfully registered with the vCenter Server Appliance.

. Open the vSphere Client to the vCenter Server Appliance.
. On the menu bar, select menu:Administrator[Client Plugins].
. Make sure the Storage Plugin for vCenter is listed as *Enabled*.
+
If the plugin is listed as Disabled with an error message stating that it cannot communicate with the application server, verify that the port number defined for the application server is enabled to pass through any firewalls that might be in use. The default application server Transmission Control Protocol (TCP) port number is 8445.
