---
sidebar: sidebar
permalink: vcenter-plugin/vc-olh-array-management-overview.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: Use the Add/Discover feature to find and add the storage arrays you want to manage in your organization's network.
---

= Learn about managing storage arrays in SANtricity Storage Plugin for vCenter
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Use the Add/Discover feature to find and add the storage arrays you want to manage in the Storage plugin for vCenter. From the Manage page, you can also rename, remove, and provide new passwords for these discovered arrays.

== Considerations for discovering arrays

For the plugin to display and manage storage resources, you must discover the storage arrays you want to manage in your organization's network. You can discover and then add a single array or multiple arrays.

=== Multiple storage arrays

If you choose to discover multiple arrays, you enter a network IP address range and then the system attempts individual connections to each IP address in that range. Any storage array successfully reached appears in the plugin and you can then add them to your management domain.

=== Single storage array

If you choose to discover a single array, you enter the single IP address for one of the controllers in the storage array and then add that array to your management domain.

[NOTE]
The plugin discovers and displays only the single IP address or IP address within a range assigned to a controller. If there are alternate controllers or IP addresses assigned to these controllers that fall outside of this single IP address or IP address range, then the plugin will not discover or display them. However, once you add the storage array, all associated IP addresses will be discovered and displayed in the Manage view.

=== User credentials

You must supply the administrator password for each storage array you want to add.

=== Certificates

As part of the discovery process, the system verifies that the discovered storage arrays are using certificates by a trusted source. The system uses two types of certificate-based authentication for all connections that it establishes with the with the browser:

* *Trusted certificates* -- You might need to install additional trusted certificates supplied by the Certificate Authority if one or both controller certificates are expired, revoked, or missing a certificate in its chain.
* *Self-signed certificates* -- Arrays can also use self-signed certificates. If you attempt to discover arrays without importing signed certificates, the plugin provides an additional step that allows you to accept the self-signed certificate. The storage array's self-signed certificate will be marked as trusted and the storage array will be added to the plugin. If you do not trust the connections to the storage array, select *Cancel* and validate the storage array's security certificate strategy before adding the storage array to the plugin.

== Storage array status

When you open the Storage Plugin for vCenter, communication with each storage array is established and the status for each storage array is displayed.

From the *Manage - All* page, you can view the status of the storage array and the status of the storage array connection.

|===
|Status |Indicates

|Optimal
|The storage array is in an optimal state. There are no certificate issues and the password is valid.
|Invalid Password
|An invalid storage array password was provided.
|Untrusted Certificate
|One or more connections with the storage array is untrusted because the HTTPS certificate is either self-signed and has not been imported, or the certificate is CA-signed and the root and intermediate CA certificates have not been imported.
|Needs Attention
|There is a problem with the storage array that requires your intervention to correct it.
|Lockdown
|The storage array is in a locked-down state.
|Unknown
|The storage array has never been contacted. This can happen when the plugin is starting up and has not yet made contact with the storage array, or the storage array is offline and has never been contacted since the plugin was started.
|Offline
|The plugin had previously contacted the storage array, but now has lost all connection to it.
|===

== Plugin interface compared to System Manager

You can use Storage Plugin for vCenter for basic operating tasks on your storage array; however, there might be times when you need to launch System Manager to perform tasks not available in the plugin.

System Manager is an embedded application on the storage array's controller, which is connected to the network through an Ethernet management port. System Manager includes all array-based functions.

The following table helps you decide whether you can use the plugin interface or the System Manager interface for a particular storage array task.

|===
|Function |Plugin interface |System Manager interface

|Batch operations on groups of multiple storage arrays
|Yes
|No. Operations are performed on a single array.
|Upgrades for the SANtricity OS firmware
|Yes. One or more arrays in a batch operation.
|Yes. Single array only.
|Import settings from one array to multiple arrays
|Yes
|No
|Host and host cluster management (create, assign volumes, update, and delete)
|Yes
|Yes
|Pools and volume group management (create, update, enable security, and delete)
|Yes
|Yes
|Volume management (create, resize, update, and delete)
|Yes
|Yes
|SSD Cache management (create, update, and delete)
|Yes
|Yes
|Mirroring and snapshot management
|No
|Yes
|Hardware management (view controller status, configure port connections, take controller offline, enable hot spares, erase drives, etc.)
|No
|Yes
|Manage alerts (email, SNMP, and syslog)
|No
|Yes
|Security key management
|No
|Yes
|Certificate management for controllers
|No
|Yes
|Access management for controllers (LDAP, SAML, etc.)
|No
|Yes
|AutoSupport management
|No
|Yes
|===
