---
sidebar: sidebar
permalink: vc-olh-reset-management-certificates.html
keywords:
summary:
---

= Reset management certificates
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-03-25 16:38:47.943197
//

[.lead]
You can revert the management certificate to the original, factory self-signed state.

*About this task*

This task deletes the current management certificate from the host system where the SANtricity Storage Plugin for vCenter is running. After the certificate is reset, the host system reverts to using the self-signed certificate.

*Steps*

. Select *Certificate Management*.
. From the *Management* tab, select *Reset*.A Confirm Reset Management Certificate dialog box opens.

. Type reset in the field, and then click *Reset*.After your browser refreshes, the browser might block access to the destination site and report that the site is using HTTP Strict Transport Security. This condition arises when you switch back to self-signed certificates. To clear the condition that is blocking access to the destination, you must clear the browsing data from the browser.

*Result*

The system reverts to using the self-signed certificate from the server. As a result, the system prompts users to manually accept the self-signed certificate for their sessions.
