---
sidebar: sidebar
permalink: vc-olh-why-can-i-not-increase-my-preservation-capacity.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: If you have created volumes on all available usable capacity, you might not be able to increase preservation capacity.
---

= Why can I not increase my preservation capacity?
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
If you have created volumes on all available usable capacity, you might not be able to increase preservation capacity.

Preservation capacity is the amount of capacity (number of drives) that is reserved on a pool to support potential drive failures. When a pool is created, the system automatically reserves a default amount of preservation capacity depending on the number of drives in the pool. If you have created volumes on all available usable capacity, you cannot increase preservation capacity without adding capacity to the pool by either adding drives or deleting volumes.

You can change the preservation capacity from Pools & Volume Groups. Select the pool that you want to edit. Click *View/Edit Settings*, and then select the *Settings* tab.

[NOTE]
Preservation capacity is specified as a number of drives, even though the actual preservation capacity is distributed across the drives in the pool.
