---
sidebar: sidebar
permalink: vcenter-plugin/vc-olh-upgrade-overview.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: You can manage SANtricity software and NVSRAM upgrades for multiple storage arrays of the same type.
---

= Upgrade overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can manage SANtricity software and NVSRAM upgrades for multiple storage arrays of the same type.

== Upgrade workflow

The following steps provide a high-level workflow for performing software upgrades:

. You download the latest SANtricity OS file from the support site (a link is available from the Support page). Save the file on the management host system (the host where you access the plugin in a browser), and then unzip the file.
. In the plugin, you can load the SANtricity OS software file and the NVSRAM file into the repository (an area of the server where files are stored).
. After the files are loaded in the repository, you can then select the file to be used in the upgrade. From the Upgrade SANtricity OS Software page, you select the OS software file and the NVSRAM file. After you select a software file, a list of compatible storage arrays appear on this page. You then select the storage arrays that you want to upgrade with the new software. (You cannot select incompatible arrays.)
. You can then begin an immediate software transfer and activation, or you can choose to stage the files for activation at a later time. During the upgrade process, the plugin performs the following tasks:

** Performs a health check on the storage arrays to determine if any conditions exist that might prevent the upgrade from completing. If any arrays fail the health check, you can skip that particular array and continue the upgrade for the others, or you can stop the entire process and troubleshoot the arrays that did not pass.
** Transfers the upgrade files to each controller.
** Reboots the controllers and activates the new OS software, one controller at a time. During activation, the existing OS file is replaced with the new file.

[NOTE]
You can also specify that the software is activated at a later time.

== Upgrade considerations

Before you upgrade multiple storage arrays, review the key considerations as part of your planning.

=== Current versions

You can view the current SANtricity OS software versions from the Manage page of the Storage Plugin for vCenter for each discovered storage array. The version is shown in the SANtricity OS Software column. The controller firmware and NVSRAM information is available in a pop-up dialog box when you click on the OS version in each row.

=== Other components requiring upgrade

As part of the upgrade process, you might also need to upgrade the host's multipath/failover driver or the HBA driver so that the host can interact with the controllers correctly. For compatibility information, refer to the link:https://imt.netapp.com/matrix/[Interoperability Matrix Tool^].

=== Dual controllers

If a storage array contains two controllers and you have a multipath driver installed, the storage array can continue to process I/O while the upgrade occurs. During the upgrade, the following process occurs:

. Controller A fails over all its LUNs to controller B.
. Upgrade occurs on controller A.
. Controller A takes back its LUNs and all of controller B's LUNs.
. Upgrade occurs on controller B.

After the upgrade completes, you might need to manually redistribute volumes between the controllers to ensure volumes return to the correct owning controller.
