---
sidebar: sidebar
permalink: vcenter-plugin/vc-olh-activate-staged-os-software.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: You can choose to activate the software file at a more convenient time.
---

= Activate staged OS software
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
You can choose to activate the software file immediately or wait until a more convenient time. This procedure assumes you chose to activate the software file at a later time.

.About this task

You can transfer the firmware files without activating them. You might choose to activate later for these reasons:

* *Time of day* -- Activating the software can take a long time, so you might want to wait until I/O loads are lighter. The controllers reboot and fail over during activation so performance might be lower than usual until the upgrade completes.
* *Type of package* -- You might want to test the new software and firmware on one storage array before upgrading the files on other storage arrays.

NOTE: You cannot stop the activation process after it starts.

.Steps

. From the main view, select *Manage*. If necessary, click the *Status* column to sort, at the top of the page, all storage arrays with a status of "OS Upgrade (awaiting activation)."
. Select one or more storage arrays that you want to activate software for, and then select menu:Upgrade Center[Activate Staged SANtricity Software].
+
The following actions occur during the upgrade operation:

** A pre-upgrade health check runs as part of the activate process. The pre-upgrade health check assesses all storage array components to make sure that the activation can proceed.
** If any health check fails for a storage array, the activation stops. You can click the ellipsis (…) and select *Save Log* to review the errors. You can also choose to override the health check error and then click *Continue* to proceed with the activation.
** You can cancel the activate operation after the pre-upgrade health check.
+
On successful completion of the pre-upgrade health check, activation occurs. The time it takes to activate depends on your storage array configuration and the components that you are activating.

. (Optional) After the activation is complete, you can see a list of what was activated for a specific storage array by clicking the ellipsis (…) and then selecting *Save Log*.
+
The file is saved in the Downloads folder for your browser with the name `activate_log-<date>. json`.
