---
sidebar: sidebar
permalink: vcenter-plugin/vc-olh-import-directory-services-settings.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: Import a directory services configuration from one storage array to other storage arrays.
---

= Import directory services settings
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
You can import a directory services configuration from one storage array to other storage arrays. This batch operation saves time when you need to configure multiple arrays in the network.

.Before you begin

Make sure that:

* Directory services are configured in System Manager (menu:Settings[Access Management]) for the storage array you want to use as the source.
* The existing configuration for the target storage arrays are backed up in System Manager (menu:Settings[System > Save Storage Array Configuration]).
* You have reviewed the requirements for replicating storage configurations in link:vc-olh-import-settings-overview.html[Import settings overview].

.About this task

Imported settings include the domain name and URL of an LDAP (Lightweight Directory Access Protocol) server, along with the mappings for the LDAP server's user groups to the storage array's predefined roles.

.Steps

. From the *Manage* page, click menu:Actions[Import Settings].
+
The Import Settings wizard opens.

. In the *Select Settings* dialog, select *Directory services* and then click *Next*.
+
A dialog box opens for selecting the source array.

. In the Select Source dialog, select the array with the settings you want to import, and then click *Next*.
. In the Select Targets dialog, select one or more arrays to receive the new settings.
+
[NOTE]
Storage arrays with firmware below 8.50 are not available for selection. In addition, an array does not appear in this dialog if the plugin cannot communicate with that array (for example, if it is offline or if it has certificate, password, or networking problems).

. Click *Finish*.
+
The Operations page displays the results of the import operation. If the operation fails, you can click on its row to see more information.

.Result

The target storage arrays are now configured with the same directory services as the source array.
