---
sidebar: sidebar
permalink: vcenter-plugin/vc-olh-import-certificates-for-arrays.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: Import certificates for the storage arrays so they can authenticate with the system hosting the Storage Plugin for vCenter.
---

= Import certificates for arrays
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If necessary, you can import certificates for the storage arrays so they can authenticate with the system hosting the Storage Plugin for vCenter. Certificates can be signed by a certificate authority (CA) or can be self-signed.

.Before you begin

If you are importing trusted certificates, the certificates must be imported for the storage array controllers using System Manager.

.Steps

. Select *Certificate Management*.
. Select the *Trusted* tab.
+
This page shows all certificates reported for the storage arrays.

. Select either menu:Import[Certificates] to import a CA certificate or menu:Import[Self-signed storage array certificates] to import a self-signed certificate.
. To limit the view, you can use the *Show certificates that are...* filtering field or you can sort the certificate rows by clicking one of the column heads.
. In the dialog box, select the certificate and then click *Import*.
+
The certificate is uploaded and validated.
