---
sidebar: sidebar
permalink: vcenter-plugin/vc-olh-consolidate-free-capacity-for-a-volume-group.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: Use the Consolidate Free Capacity option to consolidate existing free extents on a selected volume group. By performing this action, you can create additional volumes from the maximum amount of free capacity in a volume group.
---

= Consolidate free capacity for a volume group
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
Use the Consolidate Free Capacity option to consolidate existing free extents on a selected volume group. By performing this action, you can create additional volumes from the maximum amount of free capacity in a volume group.

.Before you begin

* The volume group must contain at least one free capacity area.
* All of the volumes in the volume group must be online and in Optimal status.
* Volume modification operations must not be in progress, such as changing the segment size of a volume.

.About this task

You cannot cancel the operation after it begins. Your data remains accessible during the consolidation operation.

You can launch the Consolidate Free Capacity dialog box using any of the following methods:

* When at least one free capacity area is detected for a volume group, the Consolidate free capacity recommendation appears on the Home page in the Notification area. Click the *Consolidate free capacity* link to launch the dialog box.
* You can also launch the Consolidate Free Capacity dialog box from the Pools & Volume Groups page as described in the following task.


.More about free capacity areas
[%collapsible]
====
A free capacity area is the free capacity that can result from deleting a volume or from not using all available free capacity during volume creation. When you create a volume in a volume group that has one or more free capacity areas, the volume's capacity is limited to the largest free capacity area in that volume group. For example, if a volume group has a total of 15 GiB free capacity, and the largest free capacity area is 10 GiB, the largest volume you can create is 10 GiB.

You consolidate free capacity on a volume group to improve write performance. Your volume group's free capacity will become fragmented over time as the host writes, modifies, and deletes files. Eventually, the available capacity will not be located in a single contiguous block, but will be scattered in small fragments across the volume group. This causes further file fragmentation, since the host must write new files as fragments to fit them into the available ranges of free clusters.

By consolidating free capacity on a selected volume group, you will notice improved file system performance whenever the host writes new files. The consolidation process will also help prevent new files from being fragmented in the future.
====


.Steps

. From the Manage page, select the storage array with the volume group.
. Select menu:Provisioning[Configure Pools and Volume Groups].
. Select the volume group with free capacity that you want to consolidate, and then select menu:Uncommon Tasks[Consolidate volume group free capacity].
+
The Consolidate Free Capacity dialog box appears.
. Type `consolidate` to confirm you want to perform this operation.
. Click *Consolidate*.

.Result

The system begins consolidating (defragmenting) the volume group’s free capacity areas into one contiguous amount for subsequent storage configuration tasks.

.After you finish

From the navigation sidebar, select *Operations* to view the progress of the Consolidate Free Capacity operation. This operation can be lengthy and could affect system performance.
