---
sidebar: sidebar
summary:
permalink: vcenter-plugin/vc-olh-change-cache-settings-for-a-volume.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: You can change read cache and write cache settings to impact the overall I/O performance of a volume.
---

= Change cache settings for a volume
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
You can change read cache and write cache settings to impact the overall I/O performance of a volume.

.About this task

Keep these guidelines in mind when you change cache settings for a volume:

* After opening the Change Cache Settings dialog box, you might see an icon shown next to the selected cache properties. This icon indicates that the controller has temporarily suspended caching operations. This action might occur when a new battery is charging, when a controller has been removed, or if a mismatch in cache sizes has been detected by the controller. After the condition has cleared, the cache properties selected in the dialog box become active. If the selected cache properties do not become active, contact technical support.
* You can change the cache settings for a single volume or for multiple volumes on a storage  array. You can change the cache settings for all volumes at the same time.

.Steps

. From the *Manage* page, select the storage array that contains the volumes for which you want to change cache settings.
. Select menu:Provisioning[Manage Volumes].
. Select any volume, and then select menu:More[Change cache settings].
+
The Change Cache Settings dialog box appears. All volumes on the storage array appear in this dialog box.

. Select the *Basic* tab to change the settings for read caching and write caching.
+
.Field Details
[%collapsible]
====
[cols="1a,1a" options="header"]
|===
|Cache setting |Description

|Read Caching
|The read cache is a buffer that stores data that has been read from the drives. The data for a read operation might already be in the cache from a previous operation, which eliminates the need to access the drives. The data stays in the read cache until it is flushed.
|Write Caching
|The write cache is a buffer that stores data from the host that has not yet been written to the drives. The data stays in the write cache until it is written to the drives. Write caching can increase I/O performance.
Cache is automatically flushed after the Write caching is disabled for a volume.
|===
====
. Select the *Advanced* tab to change the advanced settings for thick volumes. The advanced cache settings are available only for thick volumes.
+
.Field Details
[%collapsible]
====
[cols="1a,1a" options="header"]
|===
|Setting |Description

|Dynamic Read Cache Prefetch
|Dynamic Cache Read Prefetch allows the controller to copy additional sequential data blocks into the cache while it is reading data blocks from a drive to the cache. This caching increases the chance that future requests for data can be filled from the cache. Dynamic cache read prefetch is important for multimedia applications that use sequential I/O. The rate and amount of data that is prefetched into cache is self- adjusting based on the rate and request size of the host reads. Random access does not cause data to be prefetched into cache. This feature does not apply when read caching is disabled.
|Write Caching without Batteries
|The Write Caching without Batteries setting enables write caching to continue even when the batteries are missing, failed, discharged completely, or not fully charged. Choosing write caching without batteries is not typically recommended, because data might be lost if power is lost. Typically, write caching is turned off temporarily by the controller until the batteries are charged or a failed battery is replaced.

CAUTION: Possible loss of data. If you select this option and do not have a universal power supply for protection, you could lose data. In addition, you could lose data if you do not have controller batteries and you enable the Write caching without batteries option.
|Write Caching with Mirroring
|Write Caching with Mirroring occurs when the data written to the cache memory of one controller is also written to the cache memory of the other controller. Therefore, if one controller fails, the other can complete all outstanding write operations. Write cache mirroring is available only if write caching is enabled and two controllers are present. Write caching with mirroring is the default setting at volume creation.
|===
====

. Click *Save* to change the cache settings.
