---
sidebar: sidebar
permalink: vc-olh-remove-storage-arrays.html
keywords:
summary:
---

= Remove storage arrays
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-03-25 16:38:47.997269
//

[.lead]
You can remove one or more storage arrays if you no longer want to manage it from the SANtricity Storage Plugin for vCenter.

*About this task*

You cannot access any of the storage arrays you remove. You can, however, establish a connection to any of the removed storage arrays by pointing a browser directly to its IP address or host name.

Removing a storage array does not affect the storage array or its data in any way. If a storage array is accidentally removed, it can be added again.

*Steps*

. From the *Manage* page, select one or more storage arrays that you want to remove.
. Select *Uncommon Tasks > Remove storage arrays*.The storage array is removed from all the views in the plugin interface.
