---
sidebar: sidebar
permalink: vcenter-plugin/vc-olh-create-ssd-cache.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: To dynamically accelerate system performance, you can use the SSD Cache feature to cache the most frequently accessed data ("hot" data) onto lower latency Solid State Drives (SSDs).
---

= Create SSD Cache
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
To dynamically accelerate system performance, you can use the SSD Cache feature to cache the most frequently accessed data ("hot" data) onto lower latency Solid State Drives (SSDs). SSD Cache is used exclusively for host reads.

.Before you begin

Your storage array must contain some SSD drives.

[NOTE]
SSD Cache is not available on the EF600 or EF300 storage system.

.About this task

When you create SSD Cache, you can use a single drive or multiple drives. Because the read cache is in the storage array, caching is shared across all applications using the storage array. You select the volumes that you want to cache, and then caching is automatic and dynamic.

Follow these guidelines when you create SSD Cache.

* You can enable security on the SSD Cache only when you are creating it, not later.
* Only one SSD Cache is supported per storage array.
* The maximum usable SSD Cache capacity on a storage array is dependent on the controller’s primary cache capacity.
* SSD Cache is not supported on snapshot images.
* If you import or export volumes that are SSD Cache enabled or disabled, the cached data is not imported or exported.
* Any volume assigned to use a controller's SSD Cache is not eligible for an automatic load balance transfer.
* If the associated volumes are secure-enabled, create a secure-enabled SSD Cache.

.Steps

. From the Manage page, select the storage array for the cache.
. Select menu:Provisioning[Configure Pools and Volume Groups].
. Click menu:Create[SSD Cache].
+
The Create SSD Cache dialog box appears.

. Type a name for the SSD Cache.
. Select the SSD Cache candidate that you want to use based on the following characteristics.

+
.Field Details
[%collapsible]
====
[cols="25h,~",options="header"]
|===
|Characteristic |Use
|Capacity
|Shows the available capacity in GiB. Select the capacity for your application’s storage needs.
The maximum capacity for SSD Cache depends on the controller’s primary cache capacity. If you allocate more than the maximum amount to SSD Cache, then any extra capacity is unusable.
SSD Cache capacity counts towards your overall allocated capacity.
|Total drives
|Shows the number of drives available for this SSD cache. Select the SSD candidate with the number of drives that you want
|Secure-capable
|Indicates whether the SSD Cache candidate is comprised entirely of secure-capable drives, which can be either Full Disk Encryption (FDE) drives or Federal Information Processing Standard (FIPS) drives.
If you want to create a secure-enabled SSD Cache, look for "Yes - FDE" or "Yes - FIPS" in the Secure-capable column.
|Enable security?
|Provides the option for enabling the Drive Security feature with secure-capable drives. If you want to create a secure-enabled SSD Cache, select the *Enable Security* check box.

NOTE: Once enabled, security cannot be disabled. You can enable security on the SSD Cache only when you are creating it, not later.
|DA capable
|Indicates if Data Assurance (DA) is available for this SSD Cache candidate. Data Assurance (DA) checks for and corrects errors that might occur as data is transferred through the controllers down to the drives.
If you want to use DA, select an SSD Cache candidate that is DA capable. This option is available only when the DA feature has been enabled.
SSD Cache can contain both DA-capable and non-DA-capable drives, but all drives must be DA-capable for you to use DA.
|===
====

. Associate the SSD Cache with the volumes for which you want to implement SSD read caching. To enable SSD Cache on compatible volumes immediately, select the *Enable SSD Cache on existing compatible volumes that are mapped to hosts* check box.
+
Volumes are compatible if they share the same Drive Security and DA capabilities.

. Click *Create*.
