---
sidebar: sidebar
permalink: vc-olh-import-storage-configuration-settings.html
keywords:
summary:
---

= Import storage configuration settings
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
You can import the storage configuration from one storage array to other storage arrays. This batch operation saves time when you need to configure multiple arrays in the network.

.Before you begin

Make sure that:

* Storage is configured in System Manager for the storage array you want to use as the source.
* The existing configuration for the target storage arrays are backed up in System Manager (menu:Settings[System > Save Storage Array Configuration]).
* You have reviewed link:vc-olh-import-settings-overview.html[Import settings overview: Requirements for replicating storage configurations].
* The source and target arrays must meet these requirements:
** The shelves where the controllers reside must be identical.
** Shelf IDs must be identical.
** Expansion shelves must be populated in the same slots with the same drive types.
** The RBOD enclosure type must be identical.
** The HICs, including the Data Assurance capabilities of the host, must be identical.
** The target arrays must be in Optimal status.
** The volume capacity on the target array is larger than the source array's capacity.
* You understand the following restrictions:
** Importing from a duplex to simplex configuration is not supported; however, importing from simplex to duplex is allowed.
** Disk pool volumes 64 TB or larger on the source array will prevent the import process on the targets.

.About this task

Imported settings include configured volumes (thick and non-repository volumes only), volume groups, pools, and hot spare drive assignments.

.Steps

. From the *Manage* page, click menu:Actions[Import Settings].
+
The Import Settings wizard opens.

. In the *Select Settings* dialog, select *Storage configuration* and then click *Next*.
+
A dialog box opens for selecting the source array.

. In the Select Source dialog, select the array with the settings you want to import, and then click *Next*.
. In the Select Targets dialog, select one or more arrays to receive the new settings.
+
[NOTE]
Storage arrays with firmware below 8.50 are not available for selection. In addition, an array does not appear in this dialog if the plugin cannot communicate with that array (for example, if it is offline or if it has certificate, password, or networking problems).

. Click *Finish*.
+
The Operations page displays the results of the import operation. If the operation fails, you can click on its row to see more information.

.Result

The target storage arrays are now configured with the same storage configuration as the source array.
