---
sidebar: sidebar
permalink: vc-olh-delete-pool-or-volume-group.html
keywords:
summary:
---

= Delete pool or volume group
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-03-25 16:38:48.394927
//

[.lead]
You can delete a pool or volume group to create more unassigned capacity, which you can reconfigure to meet your application storage needs.

*Before you begin*

* You must have backed up the data on all of the volumes in the pool or volume group.
* You must have stopped all input/output (I/O).
* You must unmount any file systems on the volumes.
* You must have deleted any mirror relationships in the pool or volume group.
* You must have stopped any volume copy operation in progress for the pool or volume group.
* The pool or volume group must not be participating in an asynchronous mirroring operation.
* The drives in the volume group must not have a persistent reservation.*Steps*

. From the *Manage* page, select the storage array with the pool or volume group.
. Select *Provisioning > Configure Pools and Volume Groups*.
. Select one pool or volume group from the list. 
+
You can select only one pool or volume group at a time. Scroll down the list to see additional pools or volume groups.

. Select *Uncommon Tasks > Delete* and confirm.*What happens next?*

The system performs the following actions:

* Deletes all of the data in the pool or volume group.
* Deletes all the drives associated with the pool or volume group.
* Unassigns the associated drives, which allows you to reuse them in new or existing pools or volume groups.
