---
sidebar: sidebar
permalink: vcenter-plugin/vc-olh-add-capacity-to-a-pool-or-volume-group.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: Add drives to expand the free capacity in an existing pool or volume group.
---

= Add capacity to a pool or volume group
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
You can add drives to expand the free capacity in an existing pool or volume group.

.Before you begin

* Drives must be in an Optimal status.
* Drives must have the same drive type (HDD or SSD).
* The pool or volume group must be in an Optimal status.
* If the pool or volume group contains all secure-capable drives, add only drives that are secure-capable to continue to use the encryption abilities of the secure-capable drives.

Secure-capable drives can be either Full Disk Encryption (FDE) drives or Federal Information Processing Standard (FIPS) drives.

.About this task

In this task, you can add free capacity to be included in the pool or volume group. You can use this free capacity to create additional volumes. The data in the volumes remains accessible during this operation.

For pools, you can add a maximum of 60 drives at a time. For volume groups, you can add a maximum of two drives at a time. If you need to add more than the maximum number of drives, repeat the procedure. (A pool cannot contain more drives than the maximum limit for a storage array.)

[NOTE]
With the addition of drives, your preservation capacity may need to be increased. You should consider increasing your reserved capacity after an expansion operation.

[NOTE]
Avoid using drives that are Data Assurance (DA) capable to add capacity to a pool or volume group that is not DA capable. The pool or volume group cannot take advantage of the capabilities of the DA-capable drive. Consider using drives that are not DA capable in this situation.

.Steps

. From the Manage page, select the storage array with the pool or volume group.
. Select menu:Provisioning[ Configure Pools and Volume Groups].
. Select the pool or volume group to which you want to add drives, and then click *Add Capacity*.
+
The Add Capacity dialog box appears. Only the unassigned drives that are compatible with the pool or volume group appear.

. Under *Select drives to add capacity...*, select one or more drives that you want to add to the existing pool or volume group.
+
The controller firmware arranges the unassigned drives with the best options listed at the top. The total free capacity that is added to the pool or volume group appears below the list in *Total capacity selected*.
+
.Field Details
[%collapsible]
====
[cols="25h,~",options="header"]
|===
|Field |Description
a|
Shelf
a|
Indicates the shelf location of the drive.
a|
Bay
a|
Indicates the bay location of the drive
a|
Capacity (GiB)
a|
Indicates the drive capacity.

* Whenever possible, select drives that have a capacity equal to the capacities of the current drives in the pool or volume group.
* If you must add unassigned drives with a smaller capacity, be aware that the usable capacity of each drive currently in the pool or volume group is reduced. Therefore, the drive capacity is the same across the pool or volume group.
* If you must add unassigned drives with a larger capacity, be aware that the usable capacity of the unassigned drives that you add is reduced so that they match the current capacities of the drives in the pool or volume group.

a|
Secure-Capable
a|
Indicates whether the drive is secure-capable.

* You can protect your pool or volume group with the Drive Security feature, but all drives must be secure-capable to use this feature.
* It is possible to create a pool or volume group with a mix of secure-capable and non-secure-capable drives, but the Drive Security feature cannot be enabled.
* A pool or volume group with all secure-capable drives cannot accept a non-secure-capable drive for sparing or expansion, even if the encryption capability is not in use.
* Secure-capable drives can be either Full Disk Encryption (FDE) drives or Federal Information Processing Standard (FIPS) drives. A FIPS drive can be level 140-2 or 140-3, with level 140-3 as the higher level of security. If you select a mixture of 140-2 and 140-3 level drives, the pool or volume group will then operate at the lower level of security (140-2).

a|
DA Capable
a|
Indicates whether the drive is Data Assurance (DA) capable.

* Using drives that are not Data Assurance (DA) capable to add capacity to a DA-capable pool or volume group is not recommended. The pool or volume group no longer has DA capabilities, and you no longer have the option to enable DA on newly created volumes within the pool or volume group.
* Using drives that are Data Assurance (DA) capable to add capacity to a pool or volume group that is non DA-capable is not recommended, because that pool or volume group cannot take advantage of the capabilities of the DA-capable drive (the drive attributes do not match). Consider using drives that are not DA-capable in this situation.

a|
DULBE Capable
a|
Indicates whether the drive has the option for Deallocated or Unwritten Logical Block Error (DULBE). DULBE is an option on NVMe drives that allows the EF300 or EF600 storage array to support resource-provisioned volumes.
|===
====

. Click *Add*.
+
If you are adding drives to a pool or volume group, a confirmation dialog box appears if you selected a drive that causes the pool or volume group to no longer have one or more of the following attributes:

** Shelf loss protection
** Drawer loss protection
** Full Disk Encryption capability
** Data Assurance capability
** DULBE capability

. To continue, click *Yes*; otherwise click *Cancel*.

.Result

After you add the unassigned drives to a pool or volume group, the data in each volume of the pool or volume group is redistributed to include the additional drives.
