---
sidebar: sidebar
permalink: vc-olh-why-do-i-not-see-all-my-volumes,-hosts,-or-host-clusters.html
keywords:
summary:
---

= Why do I not see all my volumes, hosts, or host clusters
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-03-25 16:38:48.225072
//

[.lead]
Snapshot volumes with a DA-enabled base volume are not eligible to be assigned to a host that is not Data Assurance (DA) capable. You must disable DA on the base volume before a snapshot volume can be assigned to a host that is not DA capable.

Consider the following guidelines for the host to which you are assigning the snapshot volume:

* A host is not DA capable if it is connected to the storage array through an I/O interface that is not DA capable.
* A host cluster is not DA capable if it has at least one host member that is not DA capable.

[NOTE]
You cannot disable DA on a volume that is associated with snapshots (consistency groups, snapshot groups, snapshot images, and snapshot volumes), volume copies, and mirrors. All associated reserved capacity and snapshot objects must be deleted before DA can be disabled on the base volume.
