---
sidebar: sidebar
permalink: vc-olh-why-can-i-not-increase-my-preservation-capacity.html
keywords:
summary:
---

= Why can I not increase my preservation capacity
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-03-25 16:38:48.442489
//

[.lead]
If you have created volumes on all available usable capacity, you might not be able to increase preservation capacity.

Preservation capacity is the amount of capacity (number of drives) that is reserved on a pool to support potential drive failures. When a pool is created, the system automatically reserves a default amount of preservation capacity depending on the number of drives in the pool. If you have created volumes on all available usable capacity, you cannot increase preservation capacity without adding capacity to the pool by either adding drives or deleting volumes.

You can change the preservation capacity from Pools & Volume Groups. Select the pool that you want to edit. Click *View/Edit Settings*, and then select the *Settings* tab.

[NOTE]
Preservation capacity is specified as a number of drives, even though the actual preservation capacity is distributed across the drives in the pool.
