---
sidebar: sidebar
permalink: vcenter-plugin/vc-olh-delete-host-or-host-cluster.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: You can remove a host or host cluster so that volumes are no longer associated with that host.
---

= Delete host or host cluster
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can remove a host or host cluster so that volumes are no longer associated with that host.

.About this task

Keep these guidelines in mind when you delete a host or a host cluster:

* Any specific volume assignments are deleted, and the associated volumes are available for a new assignment.
* If the host is part of a host cluster that has its own specific assignments, the host cluster is unaffected. However, if the host is part of a host cluster that does not have any other assignments, the host cluster and any other associated hosts or host port identifiers inherit any default assignments.
* Any host port identifiers that were associated with the host become undefined.

.Steps

. From the Manage page, select the storage array with the host connection.
. Select menu:Provisioning[Configure Hosts].
+
The Configure Hosts page opens.

. Select the host or host cluster that you want to delete, and then click *Delete*.
+
The confirmation dialog box appears.

. Confirm that you want to perform the operation, and then click *Delete*.

.Results

If you deleted a host, the system performs the following actions:

* Deletes the host and, if applicable, removes it from the host cluster.
* Removes access to any assigned volumes.
* Returns the associated volumes to an unassigned state.
* Returns any host port identifiers associated with the host to an unassociated state. If you deleted a host cluster, the system performs the following actions:

** Deletes the host cluster and its associated hosts (if any).
** Removes access to any assigned volumes.
** Returns the associated volumes to an unassigned state.
** Returns any host port identifiers associated with the hosts to an unassociated state.
