---
sidebar: sidebar
permalink: vcenter-plugin/vc-olh-manage-software-repository.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: You can view and manage a software repository, which lists all software files associated with the Storage Plugin for vCenter.
---

= Manage software repository
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/


[.lead]
You can view and manage a software repository, which lists all software files associated with the Storage Plugin for vCenter.

.Before you begin

If you are using the repository to add SANtricity OS files, make sure that the OS files are available on your local system.

.About this task

You can use the Manage SANtricity OS Software Repository option to import one or more OS files to the host system where the plugin is running. You can also choose to delete one or more OS files that are available in the software repository.

.Steps

. From the main view, select *Manage*, and then select menu:Upgrade Center[Manage SANtricity Software Repository].
+
The Manage SANtricity OS Software Repository dialog appears.

. Perform one of the following actions:

* *Import:*

.. Click *Import*.
.. Click *Browse*, and then navigate to the location where the OS files you want to add reside. OS files have a filename similar to `N2800-830000-000.dlp`.
.. Select one or more OS files that you want to add, and then click *Import*.

* *Delete:*

.. Select one or more OS files that you want to remove from the software repository.
.. Click *Delete*.

.Result

If you selected import, the file(s) are uploaded and validated. If you selected delete, the files are removed from the software repository.
