---
sidebar: sidebar
permalink: vcenter-plugin/vc-olh-clear-staged-os-software.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: You can remove staged OS software to ensure that a pending version is not inadvertently activated at a later time.
---

= Clear staged OS software
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
You can remove staged OS software to ensure that a pending version is not inadvertently activated at a later time. Removing the staged OS software does not affect the current version that is running on the storage arrays.

.Steps

. From the main view, select *Manage*, and then select menu:Upgrade Center[Clear Staged SANtricity Software].
+
The Clear Staged SANtricity Software dialog box opens and lists all the discovered storage systems with pending software or NVSRAM.

. If needed, filter or sort the storage systems in the list, so you can view all systems that have staged software.
. Select the check boxes for the storage systems with pending software that you want cleared.
. Click *Clear*.
+
The status of the operation is shown in the dialog box.
