---
sidebar: sidebar
permalink: vcenter-plugin/vc-olh-create-a-volume-group.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: You can create a volume group for one or more volumes that are accessible to the host.
---

= Create a volume group in SANtricity Storage Plugin for vCenter
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/


[.lead]
You can create a volume group for one or more volumes that are accessible to the host. A volume group is a container for volumes with shared characteristics such as RAID level and capacity.

.Before you begin

Review the following guidelines:

* You need at least one unassigned drive.
* Limits exist as to how much drive capacity you can have in a single volume group. These limits vary according to your host type.
* To enable shelf/drawer loss protection, you must create a volume group that uses drives located in at least three shelves or drawers, unless you are using RAID 1, where two shelves/drawers is the minimum.
* When configuring an EF600 or EF300 storage array, make sure each controller has access to an equal number of drives in the first 12 slots and an equal number of drives in the last 12 slots. This configuration helps the controllers use both drive-side PCIe buses more effectively. The system currently allows for drive selection under the Advanced feature when creating a volume group.

Review how your choice of RAID level affects the resulting capacity of the volume group.

* If you select RAID 1, you must add two drives at a time to make sure that a mirrored pair is selected. Mirroring and striping (known as RAID 10 or RAID 1+0) is achieved when four or more drives are selected.
* If you select RAID 5, you must add a minimum of three drives to create the volume group.
* If you select RAID 6, you must add a minimum of five drives to create the volume group.

.About this task

During volume group creation you determine the group characteristics, such as the number of drives, security capability, data assurance (DA) capability, shelf loss protection, and drawer loss protection.

For EF600 and EF300 storage arrays, settings also include resource provisioning, drive block sizes, and volume block sizes.

[NOTE]
With larger capacity drives and the ability to distribute volumes across controllers, creating more than one volume per volume group is a good way to make use of your storage capacity and to protect your data.

.Steps

. From the Manage page, select the storage array for the volume group.
. Select menu:Provisioning[Configure Pools and Volume Groups].
. Click menu:Create[Volume group].
+
The Create Volume Group dialog box appears.

. Type a name for the volume group.
. Select the RAID level that best meets your requirements for data storage and protection. The volume group candidate table appears and displays only the candidates that support the selected RAID level.
. (Optional) If you have more than one type of drive in your storage array, select the drive type that you want to use.
+
The volume group candidate table appears and displays only the candidates that support the selected drive type and RAID level.

. (Optional) You can select either the automatic method or manual method to define which drives to use in the volume group. The Automatic method is the default selection.
+
CAUTION: Do not use the Manual method unless you are an expert who understands drive redundancy and optimal drive configurations.
+
To select drives manually, click the *Manually select drives (advanced)* link. When clicked, it changes to *Automatically select drives (advanced)*.
+
The Manual method lets you select which specific drives comprise the volume group. You can select specific unassigned drives to obtain the capacity that you require. If the storage array contains drives with different media types or different interface types, you can choose only the unconfigured capacity for a single drive type to create the new volume group.

. Based on the displayed drive characteristics, select the drives you want to use in the volume group, and then click *Create*.

The drive characteristics displayed depend on whether you selected the automatic method or manual method. For more information, see the SANtricity System Manager documentation, https://docs.netapp.com/us-en/e-series-santricity/sm-storage/create-volume-group.html[Create a volume group^].
