---
sidebar: sidebar
permalink: vc-olh-resolve-untrusted-certificates.html
keywords:
summary:
---

= Resolve untrusted certificates
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-03-25 16:38:47.963153
//

[.lead]
From the Certificate page, you can resolve untrusted certificates by importing a self-signed certificate from the storage array or by importing a certificate authority (CA) certificate that has been issued by a trusted third party.

*Before you begin*

If you plan to import a CA-signed certificate, make sure that:

* You have generated a certificate signing request (.CSR file) for each controller in the storage array and sent it to the CA.
* The CA returned trusted certificate files.
* The certificate files are available on your local system.*About this task*

Untrusted certificates occur when a storage array attempts to establish a secure connection to the plugin, but the connection fails to confirm as secure. You might need to install additional trusted CA certificates if any of the following are true:

* You recently added a storage array.
* One or both certificates are expired or revoked.
* One or both certificates are missing a root or intermediate certificate.*Steps*

. Select *Certif*icate Management.
. Select the *Trusted* tab.
+
This page shows all certificates reported for the storage arrays.

. Select either *Import > Certificates *to import a CA certificate or *Import > Self-Signed storage array certificates *to import a self-signed certificate.
. To limit the view, you can use the *Show certificates that are...* filtering field or you can sort the certificate rows by clicking one of the column heads.
. In the dialog box, select the certificate, and then click *Import*. The certificate is uploaded and validated.
