---
sidebar: sidebar
permalink: vc-olh-import-certificates-for-arrays.html
keywords:
summary:
---

= Import certificates for arrays
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-03-25 16:38:47.947428
//

[.lead]
If necessary, you can import certificates for the storage arrays so they can authenticate with the system hosting the SANtricity Storage Plugin for vCenter. Certificates can be signed by a certificate authority (CA) or can be self-signed.

*Before you begin*

If you are importing trusted certificates, the certificates must be imported for the storage array controllers using System Manager.

*Steps*

. Select *Certificate Management*.
. Select the *Trusted* tab.
+
This page shows all certificates reported for the storage arrays.

. Select either Import > Certificates to import a CA certificate or *Import > Self-signed storage array certificates *to import a self-signed certificate.
. To limit the view, you can use the *Show certificates that are...* filtering field or you can sort the certificate rows by clicking one of the column heads.
. In the dialog box, select the certificate and then click *Import*.The certificate is uploaded and validated.
