---
sidebar: sidebar
permalink: vc-olh-rename-storage-array-group.html
keywords:
summary:
---

= Rename storage array group
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-03-25 16:38:48.079543
//

[.lead]
You can change the name of a storage array group when the current name is no longer meaningful or applicable.

*About this task*

Keep these guidelines in mind.

* A name can consist of letters, numbers, and the special characters underscore (_), hyphen (-), and pound (#). If you choose any other characters, an error message appears. You are prompted to choose another name.
* Limit the name to 30 characters. Any leading and trailing spaces in the name are deleted.
* Use a unique, meaningful name that is easy to understand and remember.
* Avoid arbitrary names or names that would quickly lose their meaning in the future.*Steps*

. From the main view, select *Manage*, and then select the storage array group you want to rename.
. Select *Manage Groups > Rename storage array group*.
. In the *Group Name* field, type a new name for the group.
. Click *Rename*.
