---
sidebar: sidebar
permalink: vc-olh-how-does-my-selected-workload-impact-volume-creation.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: During volume creation, you are prompted for information about a workload’s use.
---

= How does my selected workload impact volume creation?
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
During volume creation, you are prompted for information about a workload’s use. The system uses this information to create an optimal volume configuration for you, which can be edited as needed. Optionally, you can skip this step in the volume creation sequence.

A workload is a storage object that supports an application. You can define one or more workloads, or instances, per application. For some applications, the system configures the workload to contain volumes with similar underlying volume characteristics. These volume characteristics are optimized based on the type of application the workload supports. For example, if you create a workload that supports a Microsoft SQL Server application and then subsequently create volumes for that workload, the underlying volume characteristics are optimized to support Microsoft SQL Server.

* *Application-specific* -- When you are creating volumes using an application-specific workload, the system may recommend an optimized volume configuration to minimize contention between application workload I/O and other traffic from your application instance. Volume characteristics like I/O type, segment size, controller ownership, and read and write cache are automatically recommended and optimized for workloads that are created for the following application types.
** Microsoft SQL Server
** Microsoft Exchange Server
** Video surveillance applications
** VMware ESXi (for volumes to be used with Virtual Machine File System)
+
You can review the recommended volume configuration and edit, add, or delete the system- recommended volumes and characteristics using the Add/Edit Volumes dialog box.

* *Other (or applications without specific volume creation support)* -- Other workloads use a volume configuration that you must manually specify when you want to create a workload that is not associated with a specific application, or if there is no built-in optimization for the application you intend to use on the storage array. You must manually specify the volume configuration using the Add/Edit Volumes dialog box.
