---
sidebar: sidebar
permalink: vc-olh-perform-pre-upgrade-health-check.html
keywords:
summary:
---

= Perform pre-upgrade health check
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-03-25 16:38:48.100565
//

[.lead]
A health check runs as part of the upgrade process, but you also can run a health check separately before you begin. The health check assesses components of the storage array to make sure that the upgrade can proceed.

*Steps*

. From the main view, select *Manage*, and then select *Upgrade Center > Pre-Upgrade Health Check*.
+
The Pre-Upgrade Health Check dialog box opens and lists all the discovered storage systems.

. If needed, filter or sort the storage systems in the list, so you can view all systems that are not currently in the Optimal state.
. Select the check boxes for the storage systems that you want to run through the health check.
. Click *Start*.
+
The progress is shown in the dialog box while the health check is performed.

. When the health check completes, you can click on the ellipses (...) to the right of each row to view more information and perform other tasks.

[NOTE]
If any arrays fail the health check, you can skip that particular array and continue the upgrade for the others, or you can stop the entire process and troubleshoot the arrays that did not pass.
