---
sidebar: sidebar
permalink: vc-olh-change-controller-ownership-of-a-volume.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: Change the preferred controller ownership of a volume, so that I/O for host applications is directed through the new path.
---

= Change controller ownership of a volume
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
You can change the preferred controller ownership of a volume, so that I/O for host applications is directed through the new path.

.Before you begin

If you do not use a multipath driver, any host applications that are currently using the volume must be shut down. This action prevents application errors when the I/O path changes.

.About this task

You can change controller ownership for one or more volumes in a pool or volume group.

.Steps

. From the *Manage* page, select the storage array that contains the volumes for which you want to change the controller ownership.
. Select menu:Provisioning[Manage Volumes].
. Select any volume, and then select menu:More[Change ownership].
+
The Change Volume Ownership dialog box appears. All volumes on the storage array appear in this dialog box.

. Use the *Preferred Owner* drop-down list to change the preferred controller for each volume that you want to change, and confirm that you want to perform the operation.

.Results

* The system changes the controller ownership of the volume. I/O to the volume is now directed through this I/O path.
* The volume might not use the new I/O path until the multipath driver reconfigures to recognize the new path.

This action usually takes less than five minutes.
