---
sidebar: sidebar
permalink: vc-olh-clear-staged-os-software.html
keywords:
summary:
---

= Clear staged OS software
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-03-25 16:38:48.122104
//

[.lead]
You can remove staged OS software to ensure that a pending version is not inadvertently activated at a later time. Removing the staged OS software does not affect the current version that is running on the storage arrays.

*Steps*

. From the main view, select *Manage*, and then select *Upgrade Center > Clear Staged SANtricity Software*.
+
The Clear Staged SANtricity Software dialog box opens and lists all the discovered storage systems with pending software or NVSRAM.

. If needed, filter or sort the storage systems in the list, so you can view all systems that have staged software.
. Select the check boxes for the storage systems with pending software that you want cleared.
. Click *Clear*.The status of the operation is shown in the dialog box.
