---
sidebar: sidebar
permalink: vcenter-plugin/vc-olh-initialize-volumes.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: Manually initialize a volume to recover from certain failure conditions.
---

= Initialize volumes in SANtricity Storage Plugin for vCenter
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/


[.lead]
A volume is automatically initialized when it is first created. However, the Recovery Guru might advise that you manually initialize a volume to recover from certain failure conditions.

Use this option only under the guidance of technical support. You can select one or more volumes to initialize.

.Before you begin

* All I/O operations have been stopped.
* Any devices or file systems on the volumes you want to initialize must be unmounted.
* The volume is in Optimal status and no modification operations are in progress on the volume.*Attention: *You cannot cancel the operation after it starts. All volume data is erased. Do not try this operation unless the Recovery Guru advises you to do so. Contact technical support before you begin this procedure.

.About this task

When you initialize a volume, the volume keeps its WWN, host assignments, allocated capacity, and reserved capacity settings. It also keeps the same Data Assurance (DA) settings and security settings.

The following types of volumes cannot be initialized:

* Base volume of a snapshot volume
* Primary volume in a mirror relationship
* Secondary volume in a mirror relationship
* Source volume in a volume copy
* Target volume in a volume copy
* Volume that already has an initialization in progress

This procedure applies only to standard volumes created from pools or volume groups.

.Steps

. From the Manage page, select the storage array that contains the volumes you want to initialize.
. Select menu:Provisioning[Manage Volumes].
. Select any volume, and then select menu:More[Initialize volumes].
+
The Initialize Volumes dialog box appears. All volumes on the storage array appear in this dialog box.

. Select one or more volumes that you want to initialize and confirm that you want to perform the operation.

.Results

The system performs the following actions:

* Erases all data from the volumes that were initialized.
* Clears the block indices, which causes unwritten blocks to be read as if they are zero-filled (the volume appears to be completely empty).

This operation can be lengthy and could affect system performance.
