---
sidebar: sidebar
permalink: vc-olh-how-do-i-maintain-shelf-and-drawer-loss-protection.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: Maintain shelf and drawer loss protection for a pool or volume group
---

= How do I maintain shelf and drawer loss protection?
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
To maintain shelf and drawer loss protection for a pool or volume group, use the criteria specified in the following table.

|===
|Level |Criteria for shelf/drawer loss protection |Minimum number of shelves/ drawers required

|Pool
|For shelves, the pool must contain no more than two drives in a single shelf.
For drawers, the pool must include an equal number of drives from each drawer.
|6 for shelves
5 for drawers
|RAID 6
|The volume group contains no more than two drives in a single shelf or drawer.
|3
|RAID 3 or RAID 5
|Each drive in the volume group is located in a separate shelf or drawer.
|3
|RAID 1
|Each drive in a mirrored pair must be located in a separate shelf or drawer.
|2
|RAID 0
|Cannot achieve shelf/drawer loss protection.
|Not applicable
|===

[NOTE]
Shelf/drawer loss protection is not maintained if a drive has already failed in the pool or volume group. In this situation, losing access to a drive shelf or drawer, and consequently another drive in the pool or volume group, causes loss of data.
