---
sidebar: sidebar
permalink: vc-olh-enable-security-for-a-pool-or-volume-group.html
keywords:
summary:
---

= Enable security for a pool or volume group
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-03-25 16:38:48.413761
//

[.lead]
You can enable Drive Security for a pool or volume group to prevent unauthorized access to the data on the drives contained in the pool or volume group. Read and write access for the drives is only available through a controller that is configured with a security key.

*Before you begin*

* The Drive Security feature must be enabled.
* A security key must be created.
* The pool or volume group must be in an Optimal state.
* All of the drives in the pool or volume group must be secure-capable drives.*About this task*

If you want to use Drive Security, select a pool or volume group that is secure-capable. A pool or volume group can contain both secure-capable and non-secure-capable drives, but all drives must be secure-capable to use their encryption capabilities.

After enabling security, you can only remove it by deleting the pool or volume group, and then erasing the drives.

*Steps*

. From the *Manage* page, select the storage array with the pool or volume group.
. Select *Provisioning > Configure Pools and Volume Groups*.
. Select the pool or volume group on which you want to enable security, and then click *More > Enable security*.
+
The Confirm Enable Security dialog box appears.

. Confirm that you want to enable security for the selected pool or volume group, and then click *Enable*.
