---
sidebar: sidebar
permalink: vc-olh-create-pool-manually.html
keywords:
summary:
---

= Create pool manually
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-03-25 16:38:48.336546
//

[.lead]
You can create a pool manually if your setup does not meet the requirements for automatic pool configuration. A pool is a set of logically grouped drives.

*Before you begin*

* You must have a minimum of 11 drives with the same drive type (HDD or SSD).
* Shelf loss protection requires that the drives comprising the pool are located in at least six different drive shelves and there are no more than two drives in a single drive shelf.
* Drawer loss protection requires that the drives comprising the pool are located in at least five different drawers and the pool includes an equal number of drive shelves from each drawer.
* When configuring an EF600 or EF300 storage array, make sure each controller has access to an equal number of drives in the first 12 slots and an equal number of drives in the last 12 slots. This configuration helps the controllers use both drive-side PCIe buses more effectively. For pool creation, you should use all drives in the storage array.*About this task*

During pool creation you determine its characteristics, such as drive type, security capability, data assurance (DA) capability, shelf loss protection, and drawer loss protection. 

For EF600 and EF300 storage arrays, settings also include resource provisioning and volume block sizes.

*Steps*

. From the *Manage *page, select the storage array for the pool.
. Select Provisioning > Configure Pools and Volume Groups.
. Click *Create > Pool*.
+
The Create Pool dialog box appears.

. Type a name for the pool.
. (Optional) If you have more than one type of drive in your storage array, select the drive type that you want to use.
+
The results table lists all the possible pools that you can create.

. Select the pool candidate that you want to use based on the following characteristics, and then click Create.

|===
|Characteristic |Use

|Free Capacity
|Shows the free capacity of the pool candidate in GiB. Select a pool candidate with the capacity for your application’s storage needs.
Preservation (spare) capacity is also distributed throughout the pool and is not part of the free capacity amount.
|Total Drives
|Shows the number of drives available in the pool candidate.
The system automatically reserves as many drives as possible for preservation capacity (for every six drives in a pool, the system reserves one drive for preservation capacity).
When a drive failure occurs, the preservation capacity is used to hold the reconstructed data.
|Drive Block Size (EF300 and EF600 only)
|Shows the block size (sector size) that the drives in the pool can write. Values may include:
* 512. 512-byte sector size.
* 4K. 4,096-byte sector size.
|Secure-Capable
|Indicates whether this pool candidate is comprised entirely of secure-capable drives, which can be either Full Disk Encryption (FDE) drives or Federal Information Processing Standard (FIPS) drives.
You can protect your pool with Drive Security, but all drives must be secure- capable to use this feature.
If you want to create an FDE-only pool, look for Yes - FDE in the Secure- Capable column. If you want to create a FIPS-only pool, look for Yes - FIPS in the Secure-Capable column.
You can create a pool comprised of drives that may or may not be secure- capable or are a mix of security levels. If the drives in the pool include drives that are not secure-capable, you cannot make the pool secure.
|Enable Security?
|Provides the option for enabling the Drive Security feature with secure-capable drives. If the pool is secure-capable and you have created a security key, you can enable security by selecting the check box.
The only way to remove Drive Security after it is enabled is to delete the pool and erase the drives.
|DA Capable
|Indicates if Data Assurance (DA) is available for this pool candidate. DA checks for and corrects errors that might occur as data is transferred through the controllers down to the drives.
If you want to use DA, select a pool that is DA capable. This option is available only when the DA feature has been enabled.
A pool can contain drives that are DA-capable or not DA-capable, but all drives must be DA capable for you to use this feature.
|Resource Provisioning Capable (EF300 and EF600 only)
|Shows if Resource Provisioning is available for this pool candidate. Resource Provisioning is a feature available in the EF300 and EF600 storage arrays, which allows volumes to be put in use immediately with no background initialization process.
|Shelf Loss Protection
|Shows if shelf loss protection is available.
Shelf loss protection guarantees accessibility to the data on the volumes in a pool if a total loss of communication occurs with a single drive shelf.
|Drawer Loss Protection
|Shows if drawer loss protection is available, which is provided only if you are using a drive shelf that contains drawers.
Drawer loss protection guarantees accessibility to the data on the volumes in a pool if a total loss of communication occurs with a single drawer in a drive shelf.
|Volume Block Sizes Supported (EF300 and EF600 only)
|Shows the block sizes that can be created for the volumes in the pool:
* 512n. 512 bytes native.
* 512e. 512 bytes emulated.
* 4K. 4,096 bytes.
|===
