---
sidebar: sidebar
permalink: vcenter-plugin/vc-olh-import-alert-settings.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: Import alert configurations from one storage array to other storage arrays.
---

= Import alert settings
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can import alert configurations from one storage array to other storage arrays. This batch operation saves time when you need to configure multiple arrays in the network.

.Before you begin

Make sure that:

* Alerts are configured in System Manager (menu:Settings[Alerts]) for the storage array you want to use as the source.
* The existing configuration for the target storage arrays are backed up in System Manager (menu:Settings[System > Save Storage Array Configuration]).
* You have reviewed the requirements for replicating storage configurations in link:vc-olh-import-settings-overview.html[Import settings overview].

.About this task

You can select email, SNMP, or syslog alerts for the import operation:

* *Email alerts* -- A mail server address and the email addresses of the alert recipients.
* *Syslog alerts* -- A syslog server address and a UDP port.
* *SNMP alerts* -- A community name and IP address for the SNMP server.

.Steps

. From the Manage page, click menu:Actions[Import Settings].
+
The Import Settings wizard opens.

. In the Select Settings dialog, select either *Email alerts*, *SNMP alerts*, or *Syslog alerts*, and then click *Next*.
+
A dialog box opens for selecting the source array.

. In the Select Source dialog, select the array with the settings you want to import, and then click *Next*.
. In the Select Targets dialog, select one or more arrays to receive the new settings.
+
[NOTE]
Storage arrays with firmware below 8.50 are not available for selection. In addition, an array does not appear in this dialog if the plugin cannot communicate with that array (for example, if it is offline or if it has certificate, password, or networking problems).

. Click *Finish*.
+
The Operations page displays the results of the import operation. If the operation fails, you can click on its row to see more information.

.Result

The target storage arrays are now configured to send alerts to administrators through email, SNMP, or syslog.
