---
sidebar: sidebar
permalink: vc-olh-view-ssd-cache-statistics.html
keywords:
summary:
---

= View SSD Cache statistics
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-03-25 16:38:48.379034
//

[.lead]
You can view statistics for the SSD Cache, such as reads, writes, cache hits, cache allocation percentage, and cache utilization percentage.

*About this task*

[NOTE]
This feature is not available on the EF600 or EF300 storage system.

The nominal statistics, which are a subset of the detailed statistics, are shown on the View SSD Cache Statistics dialog box. You can view detailed statistics for the SSD Cache only when you export all SSD statistics to a .csv file.

As you review and interpret the statistics, keep in mind that some interpretations are derived by looking at a combination of statistics.

*Steps*

. From the *Manage* page, select the storage array with the SSD Cache.
. Select *Provisioning > Configure Pools and Volume Groups*.
. Select the SSD Cache for which you want to view statistics, and then click *More > View SSD Cache* statistics.
+
The View SSD Cache Statistics dialog box appears and displays the nominal statistics for the selected SSD cache.

|===
|Setting |Description

|Reads
|Shows the total number of host reads from the SSD Cache-enabled volumes.
The greater the ratio of Reads to Writes, the better is the operation of the cache.
|Writes
|The total number of host writes to the SSD Cache-enabled volumes.
The greater the ratio of Reads to Writes, the better is the operation of the cache.
|Cache hits
|Shows the number of cache hits.
|Cache hits %
|Shows the percentage of cache hits. This number is derived from Cache Hits / (reads + writes). The cache hit percentage should be greater than 50 percent for effective SSD Cache operation.
|Cache allocation %
|Shows the percentage of SSD Cache storage that is allocated, expressed as a percentage of the SSD Cache storage that is available to this controller and is derived from allocated bytes / available bytes.
|Cache utilization %
|Shows the percentage of SSD Cache storage that contains data from enabled volumes, expressed as a percentage of SSD Cache storage that is allocated. This amount represents the utilization or density of the SSD Cache. Derived from allocated bytes / available bytes.
|Export All
|Exports all SSD Cache statistics to a CSV format. The exported file contains all available statistics for the SSD Cache (both nominal and detailed).
|===

. Click *Cancel* to close the dialog box.
