---
sidebar: sidebar
permalink: vc-olh-delete-volume.html
keywords:
summary:
---

= Delete volume
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/



[.lead]
You can delete one or more volumes to increase the free capacity of a pool or volume group.

*Before you begin*

On the volumes that you plan to delete, make sure that:

* All data is backed up.
* All Input/Output (I/O) is stopped.
* Any devices and file systems are unmounted.

.About this task

Typically, you delete volumes if the volumes were created with the wrong parameters or capacity, or it no longer meets storage configuration needs. Deleting a volume increases the free capacity in the pool or volume group.

CAUTION: Deleting a volume causes loss of all data on those volumes.

Be aware that you *cannot* delete a volume that has one of these conditions:

* The volume is initializing.
* The volume is reconstructing.
* The volume is part of a volume group that contains a drive that is undergoing a copyback operation.
* The volume is undergoing a modification operation, such as a change of segment size, unless the volume is now in Failed status.
* The volume is holding any type of persistent reservation.
* The volume is a source volume or a target volume in a Copy Volume that has a status of Pending, In Progress, or Failed.

[NOTE]
When a volume exceeds a given size (currently 128 TB), the delete operation is performed in the background and the freed space might not be immediately available.

.Steps

. From the *Manage* page, select the storage array that contains the volumes you want to delete.
. Select menu:Provisioning[Manage Volumes].
. Click *Delete*.
+
The Delete Volumes dialog box appears.

. Select one or more volumes that you want to delete, and then confirm that you want to perform the operation.
. Click *Delete*.
