---
sidebar: sidebar
permalink: vc-olh-discover-storage-arrays.html
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter
summary: To display and manage storage resources in the Storage Plugin for vCenter, you must discover the IP addresses of arrays in your network.
---

= Discover storage arrays
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
To display and manage storage resources in the Storage Plugin for vCenter, you must discover the IP addresses of arrays in your network.

Array discovery is a multi-step procedure:

* <<Step 1: Enter network addresses for discovery>>
* <<Step 2: Resolve untrusted certificates during discovery>>
* <<Step 3: Provide passwords>>

== Step 1: Enter network addresses for discovery

As the first step to discovering storage arrays, you enter a single IP address or a range of IP addresses to search across the local sub-network.

.Before you begin

* You must know the network IP addresses (or range of addresses) of the array controllers.
* The storage arrays must be correctly set up and configured.

.About this task

The Add/Discover feature opens a wizard that guides you through the process of discovery.

.Steps

. From the *Manage* page, select *Add/Discover*.
+
The Enter Network Address Range dialog box appears.

. Do one of the following:

* To discover one array, select the *Discover a single storage array* radio button, and then enter the IP address for one of the controllers in the storage array.
* To discover multiple storage arrays, select the *Discover all storage arrays within a network range* radio button, and then enter the starting network address and ending network address to search across your local sub-network.

. Click *Start Discovery*.
+
As the discovery process begins, the dialog box displays the storage arrays as they are discovered. The discovery process might take several minutes to complete.
+
[NOTE]
If no manageable arrays are discovered, verify that the storage arrays are properly connected to your network and their assigned addresses are within range. Click *New Discovery Parameters* to return to the Add/Discover page.

. Select the checkbox next to any storage array that you want to add to your management domain.
+
The system performs a credential check on each array you are adding to the management domain. You might need to resolve any issues with untrusted certificates before proceeding.

. Click *Next* to proceed to the next step in the wizard.
. If the storage arrays have valid certificates, go to <<Step 3: Provide passwords>>. If any storage arrays do not have valid certificates, the Resolve Self-Signed Certificates dialog box appears; go to <<Step 2: Resolve untrusted certificates during discovery>>. If you want to import CA-signed certificates, cancel out of the discovery dialogs and go to link:vc-olh-import-certificates-for-arrays.html[Import certificates for arrays].

== Step 2: Resolve untrusted certificates during discovery

If necessary, you must resolve any certificate issues before proceeding with the discovery process.

.About this task

During discovery, if any storage arrays show an "Untrusted Certificates" status, the Resolve Self-Signed Certificates dialog box appears. You can resolve untrusted certificates in this dialog, or you can import CA certificates (see link:vc-olh-import-certificates-for-arrays.html[Import certificates for arrays]).

.Steps

. If the Resolve Self-Signed Certificates dialog box opens, review the information displayed for the untrusted certificates. For more information, you can also click the ellipses at the far end of the table and select *View* from the pop-up menu.
. Do one of the following:

** If you trust the connections to the discovered storage arrays, click *Next* and then click *Yes* to confirm and continue to the next card in the wizard. The self-signed certificates will be marked as trusted and the storage arrays will be added to the plugin.
** If you do not trust the connections to the storage arrays, select *Cancel* and validate each storage array's security certificate strategy before adding any of them to the plugin.

== Step 3: Provide passwords

As the last step for discovery, you must enter the passwords for the storage arrays that you want to add to your management domain.

.Before you begin

* The storage array must be correctly set up and configured.
* Storage array passwords must be set up using System Manager's Access Management tile.

.Steps

. Optionally, if you have previously configured groups for the arrays, you can use the drop-down to select a group for the discovered arrays.
. For each discovered array, enter its admin password in the fields.
. Click *Finish*.

[NOTE]
It can take several minutes for the system to connect to the specified storage arrays.

.Result

The storage arrays are added to your management domain and associated with the selected group (if specified).

NOTE: You can use the Launch option to open the browser-based System Manager for one or more storage arrays when you want to perform management operations.
