---
sidebar: sidebar
permalink: vc-olh-open-and-navigate-the-plug-in.html
keywords:
summary:
---

= Open and navigate the plug-in
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-03-25 16:38:47.921239
//

[.lead]
You can open the SANtricity Storage Plugin for vCenter from within a vSphere Client session.

Before you begin, make sure that you know the login credentials of the account that has read/configure privileges assigned for the plug- in.

Steps

. From the vSphere Client home page, click *SANtricity Storage Plugin for vCenter*.
+
The plugin opens within a vSphere Client window. In the top panel, the vSphere Client task bar is displayed. In the middle panel, the plug- in's main page opens to Manage-All. At the bottom, a panel for *Recent Tasks and Alarms* is displayed.

. Access storage management tasks from the navigation sidebar on the left:

** *Manage.* Discover storage arrays in your network, launch System Manager for an array, import settings from one array to multiple arrays, manage array groups, upgrade the OS software, and provision storage.
** *Certificate Management.* Manage certificates to authenticate between browsers and clients.
** *Operations.* View the progress of batch operations, such as importing settings from one array to another.

[NOTE]
Some operations are not available when a storage array has a non-optimal status.

** *Support.* View technical support options, resources, and contacts.
