---
sidebar: sidebar
permalink: vcenter-plugin/vc-olh--what-is-shelf-loss-protection-and-drawer-loss-protection.html
keywords:
summary:
---

=  What is shelf loss protection and drawer loss protection
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Shelf loss protection and drawer loss protection are attributes of pools and volume groups that allow you to maintain data access in the event of a single shelf or drawer failure.

=== Shelf loss protection

A shelf is the enclosure that contains either the drives or the drives and the controller. Shelf loss protection guarantees accessibility to the data on the volumes in a pool or volume group if a total loss of communication occurs with a single drive shelf. An example of total loss of communication might be loss of power to the drive shelf or failure of both I/O modules (IOMs).

[NOTE]
Shelf loss protection is not guaranteed if a drive has already failed in the pool or volume group. In this situation, losing access to a drive shelf and consequently another drive in the pool or volume group causes loss of data.

The criteria for shelf loss protection depends on the protection method, as described in the following table.

|===
|Level |Criteria for shelf loss protection |Minimum number of shelves required

|Pool
|The pool must include drives from at least five shelves and there must be an equal number of drives in each shelf. Shelf loss protection is not applicable to high-capacity shelves; if your system contains high-capacity shelves, refer to Drawer Loss Protection.
|5
|RAID 6
|The volume group contains no more than two drives in a single drawer.
|3
|RAID 3 or RAID 5
|Each drive in the volume group is located in a separate shelf.
|3
|RAID 1
|Each drive in a RAID 1 pair must be located in a separate shelf.
|2
|RAID 0
|Cannot achieve Shelf Loss Protection.
|Not applicable
|===

=== Drawer loss protection

A drawer is one of the compartments of a shelf that you pull out to access the drives. Only the high-capacity shelves have drawers. Drawer loss protection guarantees accessibility to the data on the volumes in a pool or volume group if a total loss of communication occurs with a single drawer. An example of total loss of communication might be loss of power to the drawer or failure of an internal component within the drawer.

CAUTION: Drawer loss protection is not guaranteed if a drive has already failed in the pool or volume group. In this situation, losing access to a drawer (and consequently another drive in the pool or volume group) causes loss of data.

The criteria for drawer loss protection depends on the protection method, as described in the following table:

|===
|Level |Criteria for drawer loss protection |Minimum number of drawers required

|Pool
|Pool candidates must include drives from all drawers, and there must be an equal number of drives in each drawer.
The pool must include drives from at least five drawers and there must be an equal number of drives in each drawer.
A 60-drive shelf can achieve Drawer Loss Protection when the pool contains 15, 20, 25, 30, 35, 40, 45, 50, 55, or 60 drives. Increments in multiples of 5 can be added to the pool after initial creation.
|5
|RAID 6
|The volume group contains no more than two drives in a single drawer.
|3
|RAID 3 or 5
|Each drive in the volume group is located in a separate drawer
|3
|RAID 1
|Each drive in a mirrored pair must be located in a separate drawer.
|2
|RAID 0
|Cannot achieve Drawer Loss Protection.
|Not applicable
|===
