---
sidebar: sidebar
permalink: vc-olh-import-system-settings.html
keywords:
summary:
---

= Import system settings
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-03-25 16:38:48.040063
//

[.lead]
You can import the system settings from one storage array to other storage arrays. This batch operation saves time when you need to configure multiple arrays in the network.

*Before you begin*

Make sure that:

* System settings are configured in System Manager for the storage array you want to use as the source.
* The existing configuration for the target storage arrays are backed up in System Manager (*Settings > System > Save Storage Array Configuration*).
* You have reviewed <Xref to Import Settings Overview: Requirements for replicating storage configurations>.*About this task*

Imported settings include media scan settings for a volume, SSD settings for controllers, and automatic load balancing (does not include host connectivity reporting).

*Steps*

. From the *Manage* page, click *Actions > Import Settings*. 
+
The Import Settings wizard opens.

. In the *Select Settings* dialog, select *System* and then click *Next*. 
+
A dialog box opens for selecting the source array.

. In the *Select Source* dialog, select the array with the settings you want to import, and then click *Next*.
. In the *Select Targets* dialog, select one or more arrays to receive the new settings.

[NOTE]
Storage arrays with firmware below 8.50 are not available for selection. In addition, an array does not appear in this dialog if the plugin cannot communicate with that array (for example, if it is offline or if it has certificate, password, or networking problems).

. Click *Finish*.The Operations page displays the results of the import operation. If the operation fails, you can click on its row to see more information.

*Result*

The target storage arrays are now configured with the same system settings as the source array.
