---
sidebar: sidebar
permalink: vc-olh-import-autosupport-settings.html
keywords:
summary:
---

= Import AutoSupport settings
:experimental:
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can import an AutoSupport configuration from one storage array to other storage arrays. This batch operation saves time when you need to configure multiple arrays in the network.

.Before you begin

Make sure that:

* AutoSupport is configured in System Manager (menu:Support[Support Center]) for the storage array you want to use as the source.
* The existing configuration for the target storage arrays are backed up in System Manager (menu:Settings[System > Save Storage Array Configuration]).
* You have reviewed link:vc-olh-import-settings-overview.html[Import settings overview: Requirements for replicating storage configurations].

.About this task

Imported settings include the separate features (Basic AutoSupport, AutoSupport OnDemand, and Remote Diagnostics), the maintenance window, delivery method, and dispatch schedule.

.Steps

. From the *Manage* page, click menu:Actions[Import Settings].
+
The Import Settings wizard opens.

. In the Select Settings dialog, select *AutoSupport* and then click *Next*.
+
A dialog box opens for selecting the source array.

. In the Select Source dialog, select the array with the settings you want to import, and then click *Next*.
. In the Select Targets dialog, select one or more arrays to receive the new settings.
+
[NOTE]
Storage arrays with firmware below 8.50 are not available for selection. In addition, an array does not appear in this dialog if the plugin cannot communicate with that array (for example, if it is offline or if it has certificate, password, or networking problems).

. Click *Finish*.
+
The Operations page displays the results of the import operation. If the operation fails, you can click on its row to see more information.

.Result

The target storage arrays are now configured with the same AutoSupport settings as the source array.
