---
permalink: maintenance-e4000/replace-controller-requirements-e4000.html
sidebar: sidebar
keywords: 
summary: 
---
= Requirements for E4000 controller replacement
:icons: font
:imagesdir: ../media/

[.lead]
Before you replace or add an E4000 controller, review the requirements and considerations.

Each controller canister contains a controller card and a battery. You can add a second controller to a simplex configuration or replace a failed controller.


== Requirements for adding second controller
You can add a second controller canister to the simplex version of the E4000 controller shelf. Before you add a second controller, you must have:

* A new controller canister with the same part number as the currently installed controller canister.
+
NOTE: This is not applicable for a StorageGRID appliance.
* All cables, transceivers, switches, and host bus adapters (HBAs) needed to connect the new controller ports.
+
For information about compatible hardware, refer to the https://mysupport.netapp.com/NOW/products/interoperability[NetApp Interoperability Matrix] or the http://hwu.netapp.com/home.aspx[NetApp Hardware Universe].
* Multipath driver installed on the host so that you can use both controllers. Refer to the https://docs.netapp.com/us-en/e-series/config-linux/index.html[Linux express configuration], https://docs.netapp.com/us-en/e-series/config-windows/index.html[Windows express configuration], or https://docs.netapp.com/us-en/e-series/config-vmware/index.html[VMware express configuration] for instructions.

* An ESD wristband, or you have taken other antistatic precautions.
* A #1 Phillips screwdriver.
* Labels to identify the new cables.
* A management station with a browser that can access SANtricity System Manager for the controller. (To open the System Manager interface, point the browser to the controller’s domain name or IP address.)
+
Optionally, you can use the command line interface (CLI) to perform some of the procedures. For SANtricity System Manager (version 11.60 and above), you can download the CLI package (zip file) from System Manager. Then, go to *Settings >System > Add-ons > Command Line Interface*. You can then issue CLI commands from an operating system prompt, such as the DOS C: prompt.


== Requirements for replacing controller

When you replace a failed controller canister, you must remove the battery, HIC, and DIMMs from the original controller canister and install them in the replacement controller canister.

You can determine if you have a failed controller canister in two ways:

* The Recovery Guru in SANtricity System Manager directs you to replace the controller canister.
* The amber Attention LED on the controller canister is on, indicating that the controller has a fault.

Before you replace a controller, you must have:

* A replacement controller canister with the same part number as the controller canister you are replacing.
* An ESD wristband, or you have taken other antistatic precautions.
* Labels to identify each cable that is connected to the controller canister.
* #1 Phillips screwdriver.
* A management station with a browser that can access SANtricity System Manager for the controller. (To open the System Manager interface, point the browser to the controller’s domain name or IP address.)
+
Optionally, you can use the command line interface (CLI) to perform some of the procedures. You can download the CLI package (zip file) from System Manager. Then, go to *Settings > System > Add-ons > Command Line Interface*. You can then issue CLI commands from an operating system prompt, such as the DOS C: prompt.


=== Duplex configuration requirements

If the controller shelf has two controllers (duplex configuration), you can replace a controller canister while your storage array is powered on and performing host I/O operations, as long as the following conditions are true:

* The second controller canister in the shelf has Optimal status.
* The *OK to remove* field in the Details area of the Recovery Guru in SANtricity System Manager displays *Yes*, indicating that it is safe to remove this component.

=== Simplex configuration requirements

If you have only one controller canister (simplex configuration), data on the storage array will not be accessible until you replace the controller canister. You must stop host I/O operations and power down the storage array.