---
permalink: maintenance-e4000/replace-drives-12-24.html
sidebar: sidebar
keywords: E4000 replace drive, replacing E4000 drive, E4000 replace drive, replacing E4000 drive, E4000, E-Series, eseries
summary: Replace a drive in an E4000 with a 12-drive or 24-drive shelf.
---
= Replace drive in E4000 (12-drive or 24-drive shelf)
:icons: font
:imagesdir: ../media/

[.lead]
You can replace a drive in an E4000 with a 12-drive or 24-drive shelf.

.About this task

The Recovery Guru in SANtricity System Manager monitors the drives in the storage array and can notify you of an impending drive failure or an actual drive failure. When a drive has failed, its amber Attention LED is on. You can hot-swap a failed drive while the storage array is receiving I/O.

.Before you begin

* Review the drive handling requirements
* Make sure you have the following:
** A replacement drive that is supported by NetApp for your controller shelf or drive shelf.
** An ESD wristband, or you have taken other antistatic precautions.
** A management station with a browser that can access SANtricity System Manager for the controller. (To open the System Manager interface, point the browser to the controller's domain name or IP address.)

== Step 1: Prepare to replace drive

Prepare to replace a drive by checking the Recovery Guru in SANtricity System Manager and completing any prerequisite steps. Then, you can locate the failed component.

.Steps

. If the Recovery Guru in SANtricity System Manager has notified you of an _impending drive failure_, but the drive has not yet failed, follow the instructions in the Recovery Guru to fail the drive.
. If needed, use SANtricity System Manager to confirm you have a suitable replacement drive.
 .. Select *Hardware*.
 .. Select the failed drive on the shelf graphic.
 .. Click the drive to display its context menu, and then select *View settings*.
 .. Confirm that the replacement drive has a capacity equal to or greater than the drive you are replacing and that it has the features you expect.
. If needed, use SANtricity System Manager to locate the drive within your storage array. From the drive's context menu on the Hardware page, select *Turn on locator light*.
+
The drive's Attention LED (amber) blinks so you can identify which drive to replace.
+
NOTE: If you are replacing a drive in a shelf that has a bezel, you must remove the bezel to see the drive LEDs.

== Step 2: Remove failed drive

Remove a failed drive to replace it with a new one.

.Steps

. Unpack the replacement drive, and set it on a flat, static-free surface near the shelf.
+
Save all packing materials.

. Press the release button on the failed drive.
. Open the cam handle, and slide out the drive slightly.
. Wait 60 seconds.
. Using both hands, remove the drive from the shelf.
. Place the drive on an antistatic, cushioned surface away from magnetic fields.
. Wait 30 seconds for the software to recognize that the drive has been removed before moving on to "Step 3: Install new drive."
+
NOTE: If you accidentally remove an active drive, wait at least 60 seconds, and then reinstall it. For the recovery procedure, refer to the storage management software.
NOTE: If you accidentally remove an active drive, wait at least 60 seconds, and then reinstall it. For the recovery procedure, refer to the storage management software.

== Step 3: Install new drive

Install a new drive to replace the failed one.

CAUTION: Install the replacement drive as soon as possible after removing the failed drive. Otherwise, there is a risk that the equipment might overheat.


.Steps

. Open the cam handle.
. Using two hands, insert the replacement drive into the open bay, firmly pushing until the drive stops.
. Slowly close the cam handle until the drive is fully seated in the midplane and the handle clicks into place.
+
The green LED on the drive comes on when the drive is inserted correctly.
+
NOTE: Depending on your configuration, the controller might automatically reconstruct data to the new drive. If the shelf uses hot spare drives, the controller might need to perform a complete reconstruction on the hot spare before it can copy the data to the replaced drive. This reconstruction process increases the time that is required to complete this procedure.

== Step 4: Complete drive replacement

Complete the drive replacement to confirm that the new drive is working correctly.

.Steps

. Check the Power LED and the Attention LED on the drive you replaced. (When you first insert a drive, its Attention LED might be on. However, the LED should go off within a minute.)
 ** Power LED is on or blinking, and the Attention LED is off: Indicates that the new drive is working correctly.
 ** Power LED is off: Indicates that the drive might not be installed correctly. Remove the drive, wait 60 seconds, and then reinstall it.
 ** Attention LED is on: Indicates that the new drive might be defective. Replace it with another new drive.
. If the Recovery Guru in SANtricity System Manager still shows an issue, select *Recheck* to ensure the problem has been resolved.
. If the Recovery Guru indicates that drive reconstruction did not start automatically, start reconstruction manually, as follows:
+
NOTE: Perform this operation only when instructed to do so by technical support or the Recovery Guru.

 .. Select *Hardware*.
 .. Click the drive that you replaced.
 .. From the drive's context menu, select *Reconstruct*.
 .. Confirm that you want to perform this operation.
+
When the drive reconstruction completes, the volume group is in an Optimal state.

. As required, reinstall the bezel.
. Return the failed part to NetApp, as described in the RMA instructions shipped with the kit.

.What's next?

Your drive replacement is complete. You can resume normal operations.
