---
permalink: maintenance-e5700/batteries-intro-concept.html
sidebar: sidebar
keywords: E5700 battery, repair E5700 battery, replace E5700 battery, failed E5700 battery
summary: Review E5700 battery replacement requirements and considerations.
---
= Requirements for E5700 battery replacement
:icons: font
:imagesdir: ../media/

[.lead]
Before you replace an E5700 battery, review the requirements and considerations.

Each controller canister includes a battery that preserves cached data if the AC power fails.

== Recovery Guru alerts

If the Recovery Guru in SANtricity System Manager reports one of following statuses, you must replace the affected battery:

* Battery Failed
* Battery Replacement Required

From SANtricity System Manager, review the details in the Recovery Guru to confirm that there is an issue with a battery and to ensure no other items must be addressed first.

== Procedure overview

To protect your data, you must replace a failed battery as soon as possible.

The following is an overview of the steps to replace a battery in E5700 controllers (E5724, EF570, or E5760):

. Take controller offline (duplex only).
. Remove the controller canister.
. Replace the battery.
. Replace the controller canister.
. Bring the controller online (duplex only).

== Requirements

If you plan to replace a failed battery, keep the following requirements in mind.

* You must install SANtricity Storage Manager on a management station, so you can use the storage array's command line interface (CLI).
+
If this software has not yet been installed, follow the instructions in the link:../config-linux/index.html[Linux express configuration], link:../config-windows/index.html[Windows express configuration], or link:../config-vmware/index.html[VMware express configuration] to download and install it.

* You must have a replacement battery.
* You must have an ESD wristband, or you have taken other antistatic precautions.
* You should use labels to identify each cable that is connected to the controller canister.
