---
permalink: maintenance-e5700/concept_overview_and_requirements_hics.html
sidebar: sidebar
keywords: 
summary: ''
---
= Overview and requirements
:icons: font
:imagesdir: ../media/

[.lead]
This topic provides an overview of the host interface card and describes the requirements you need to know about before adding, upgrading or replacing a HIC.

== Host interface card overview

[.lead]
You can add, upgrade, or replace a HIC in the E5724 controller shelf and the E5760 controller shelf:

The following is an overview of the steps to replace a HIC in an E5700 controllers (E5724 or E5760):

. Take the controller offline
. Remove the controller canister
. Replace the battery
. Replace the controller canister
. Bring the controller online

== Requirements for adding, upgrading or replacing a HIC

[.lead]
If you plan to add, upgrade, or replace a host interface card (HIC), you must keep in mind certain requirements.

* You have scheduled a downtime maintenance window for this procedure. The power must be off when you install HICs, so you cannot access data on the storage array until you have successfully completed this procedure. (In a duplex configuration, this is because both controllers must have the same HIC configuration when they are powered on.)
* You have two HICs must be compatible with your controllers.
+
For duplex configurations (two controllers), the HICs installed in the two controller canisters must be identical. The presence of mismatched HICs causes the controller with the replacement HIC to lock down when you bring it online.

* You have all cables, transceivers, switches, and host bus adapters (HBAs) needed to connect the new host ports.
+
For information about compatible hardware, refer to the https://mysupport.netapp.com/NOW/products/interoperability[NetApp Interoperability Matrix] or the http://hwu.netapp.com/home.aspx[NetApp Hardware Universe].

* You have an ESD wristband, or you have taken other antistatic precautions.
* You have a #1 Phillips screwdriver.
* You have labels to identify each cable that is connected to the controller canister.
* You have installed SANtricity Storage Manager on a management station, so you can use the storage array's command line interface (CLI).
+
If SANtricity Storage Manager has not yet been installed, follow the instructions in the link:../com.netapp.doc.ssm-exp-ic-lin/home.html[Linux express configuration], link:../com.netapp.doc.ssm-exp-ic-win/home.html[Windows express configuration], or link:../com.netapp.doc.ssm-exp-ic-vm/home.html[VMware express configuration] to download and install the software.
