---
permalink: maintenance-ef50-ef80/controller-replace-complete-replacement.html
sidebar: sidebar
keywords: ef50, ef80, how to complete the controller replacement process
summary: To complete the controller replacement for your EF50 or EF80 storage system, ensure storage system firmware is current, verify volumes are returned to their owners, collect system support data, and return the failed part to NetApp.
---
= Complete the controller replacement - EF50 and EF80
:icons: font
:imagesdir: ../media/

[.lead]
To complete the controller replacement for your EF50 or EF80 storage system, ensure the latest version of SANtricity OS is installed, verify volumes are returned to their owning controllers, collect system support data, and return the failed part to NetApp.

.Before you begin
* You must have met the link:controller-replace-requirements.html[requirements] for this procedure.
* You must have completed the link:controller-replace-prepare.html[preparation] for this procedure.
* You must have link:controller-replace-offline-controller.html[offlined the impaired controller].
* You must have link:controller-replace-move-hardware.html[replaced the impaired controller].
* You must have link:controller-replace-online-controller.html[onlined the replacement controller].

== Step 1: Ensure latest version of SANtricity OS, verify volume ownership, and collect support data

Using SANtricity System Manager, ensure the latest version of SANtricity OS is installed, verify that all volumes are returned to their owning controllers and collect support data so that you can resume operations.

include::../_include/ge_controller_replace_complete_replacement.adoc[]

//Is the include above the same content as Complete replace used for IO module upgrade and replace and other FRU replacements?

== Step 2: Return the failed part to NetApp
include::../_include/complete_rma.adoc[]

.What's next?
Your controller replacement is complete. You can resume normal operations.



