---
permalink: maintenance-ef50-ef80/controller-replace-requirements.html
sidebar: sidebar
keywords: ef50, ef50c, ef80, ef80c, prerequisite, replace the controller module
summary: Before replacing the controller in your EF50 or EF80 storage system, ensure you meet the necessary requirements for a successful replacement. This includes verifying all other components in the system are functioning properly, verifying that you have the correct replacement controller, and saving the controller's console output to a text log file.
---
= Controller replacement requirements - EF50, EF50C, EF80, and EF80C
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing the controller in your EF50 or EF80 storage system, ensure you meet the requirements for a successful replacement. This includes verifying you have a failed controller, verifying the state of your storage system, acquiring tools, and having a management station and browser to access SANtricity System Manager.
---
= Requirements to replace a controller - EF50, EF50C, EF80, and EF80C
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing the controller in your EF50, EF50C, EF80, or EF80C storage system, ensure you meet the requirements for a successful replacement. This includes verifying you have a failed controller, verifying the state of your storage system, acquiring tools, and having a management station and browser to access SANtricity System Manager.

include::../_include/ge_controller_replace_requirements.adoc[]

.What's next?

After you’ve the reviewed the requirements to replace the impaired controller, you need to link:controller-replace-prepare.html[prepare your storage system].