---
permalink: maintenance-ef50-ef80/dimm-replace.html
sidebar: sidebar
keywords: ef50, ef80, replace a dimm
summary: Replace a DIMM in your EF50 or EF80 storage system when a memory mismatch is present, or you have a failed DIMM. The replacement process involves shutting down the impaired controller, removing it, replacing the DIMM, reinstalling the controller, and then returning the failed part to NetApp.
---
= Replace a DIMM - EF50 and EF80
:icons: font
:imagesdir: ../media/

[.lead]
Replace a DIMM in your EF50 or EF80 storage system when a memory mismatch is present, or you have a failed DIMM. The replacement process involves shutting down the impaired controller, removing it, replacing the DIMM, reinstalling the controller, and then returning the failed part to NetApp.

.Before you begin

* All other components in the storage system must be working correctly; if not, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support^] before continuing.

* Verify the replacement DIMM is the correct size for your storage system configuration.

.About this task
If needed, you can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Log into the BMC using SSH and enter the `system location-led _on_` command.

A storage system has three location LEDs: one on the operator display panel and one on each controller. Location LEDs remain illuminated for 30 minutes. 

You can turn them off by entering the `system location-led _off_` command. If you are unsure if the LEDs are on or off, you can check their state by entering the `system location-led show` command.

== Step 1: Determine if you need to replace a DIMM

Verify the cache size of your controller before replacing the DIMMS.

//include::../_include/ge_internal_frus_controller_shutdown.adoc[]

--Make this an include from here down--

.Steps

. Access the Storage Array profile for the controller. From SANtricity System Manager, go to menu:Support[Support Center]. From the Support Resources page, select *Storage Array Profile*.
. Scroll down or use the Search field to locate the *Data Cache Module* information.
. If one of the following is present, note the DIMM's location and continue with remaining procedures in this section to replace the DIMMs on your controller:
** A failed DIMM, or a DIMM reporting *Data Cache Module* as not optimal.
** A DIMM with a mismatched *Data Cache Module* capacity.
 

== Step 2: Prepare to replace a DIMM

Prepare to replace a DIMM by saving the drive security key, backing up the configuration, and collecting support data. Then, you can stop host I/O operations and place the controller offline?

//include::../_include/ge_internal_frus_controller_shutdown.adoc[]

--Make an include from here down--

.Steps

. Make sure that no volumes are in use or that you have a multipath driver installed on all hosts using these volumes.
. Make sure you have the following:
* A replacement DIMM.
* An ESD wristband, or you have taken other antistatic precautions.
* A flat, static-free surface.
* Labels to identify each cable that is connected to the controller.
* A management station with a browser that can access SANtricity System Manager for the controller. (To open the System Manager interface, point the browser to the controller’s domain name or IP address.)
. From SANtricity System Manager, review the details in the Recovery Guru to confirm that there is an issue with a mismatched memory and to ensure no other items must be addressed first.
. From the Details area of the Recovery Guru, determine which DIMM to replace.
. Back up the storage array’s configuration database using SANtricity System Manager.
+
If a problem occurs when you remove a controller, you can use the saved file to restore your configuration. The system will save the current state of the RAID configuration database, which includes all data for volume groups and disk pools on the controller.

.. Select *Support › Support Center › Diagnostics*.
.. Select *Collect Configuration Data*.
.. Click *Collect*.
+
The file is saved in the Downloads folder for your browser with the name, *configurationData-
<arrayName>-<dateTime>.7z*.


== Step 3: Place the impaired controller offline
 
Place the impaired controller offline so you can safely remove and replace the DIMMs.
 
include::../_include/ge_internal_frus_controller_shutdown.adoc[]


== Step 4: Remove the controller

You must remove the impaired controller from the chassis to replace a DIMM.

include::../_include/ge_controller_remove.adoc[]

. Open the controller cover by turning the thumbscrew counterclockwise to loosen, and then open the cover. 


== Step 5: Replace a DIMM

To replace a DIMM, locate the faulty DIMM inside the controller and follow the specific sequence of steps.

include::../_include/ge_dimm_replace.adoc[]


== Step 6: Reinstall the controller

Reinstall the controller into the chassis and reboot it.

include::../_include/ge_controller_reinstall.adoc[]


== Step 7: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
