---
permalink: maintenance-ef50-ef80/dimm-replace.html
sidebar: sidebar
keywords: ef50, ef80, replace a dimm
summary: Replace a DIMM in your EF50 or EF80 storage system when a memory mismatch is present, or you have a failed DIMM. The replacement process involves shutting down the impaired controller, removing it, replacing the DIMM, reinstalling the controller, and then returning the failed part to NetApp.
---
= Replace a DIMM - EF50 and EF80
:icons: font
:imagesdir: ../media/

[.lead]
Replace a DIMM in your EF50 or EF80 storage system when a memory mismatch is present, or you have a failed DIMM. The replacement process involves shutting down the impaired controller, removing it, replacing the DIMM, reinstalling the controller, and then returning the failed part to NetApp.

.Before you begin

* All other components in the storage system must be working correctly; if not, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support^] before continuing.

* Verify the replacement DIMM is the correct size for your storage system configuration.

.About this task
* Prevent electrostatic discharge (ESD) during handling and installation of a DIMM:
** Keep the DIMM in the ESD bag until you are ready to install it.
** Open the ESD bag by hand or cut the top off with a pair of scissors. Do not insert a metal tool or knife into the ESD bag.
** Keep the ESD bag and any packing materials to return the failed DIMM.
** Always wear an ESD wrist strap grounded to an unpainted surface on your storage system chassis.
* Avoid magnetic fields. Keep DIMMs away from magnetic devices.
* You can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Using SANtricity System Manager, select *Hardware*, click the *Controller shelf* tab, and from the menu select *Turn on location light*. Location LEDs remain illuminated for 30 minutes.

== Step 1: Determine if you need to replace a DIMM

Verify the cache size of your controller before replacing a DIMM.

//include::../_include/ge_internal_frus_controller_shutdown.adoc[]

--Make this an include from here down--

.Steps

. Access the Storage Array profile for the controller. From SANtricity System Manager, go to menu:Support[Support Center]. From the Support Resources page, select *Storage Array Profile*.
. Scroll down or use the Search field to locate the *Data Cache Module* information.
. If one of the following is present, note the DIMM's location and continue with this procedure to replace the DIMMs on your controller:
** A failed DIMM, or a DIMM reporting *Data Cache Module* as not optimal.
** A DIMM with a mismatched *Data Cache Module* capacity.
 

== Step 2: Prepare to replace a DIMM

Prepare to replace a DIMM by saving the drive security key, backing up the configuration, and collecting support data. Then, you can stop host I/O operations and place the controller offline?

//include::../_include/ge_internal_frus_controller_shutdown.adoc[]

--Make an include from here down--

.Steps

. Make sure that no volumes are in use or that you have a multipath driver installed on all hosts using these volumes.
. Make sure you have the following:
* A replacement DIMM.
* An ESD wristband, or you have taken other antistatic precautions.
* A flat, static-free surface.
* Labels to identify each cable that is connected to the controller.
* A management station with a browser that can access SANtricity System Manager for the controller. (To open the System Manager interface, point the browser to the controller’s domain name or IP address.)
. From SANtricity System Manager, review the details in the Recovery Guru to confirm that there is an issue with a mismatched memory and to ensure no other items must be addressed first.
. From the Details area of the Recovery Guru, determine which DIMM to replace.


== Step 3: Place the impaired controller offline
 
Place the impaired controller offline so you can safely replace a DIMM.
 
include::../_include/ge_internal_frus_controller_offline.adoc[]


== Step 4: Remove the controller

Remove the impaired controller from the chassis to replace a DIMM.

include::../_include/ge_controller_remove.adoc[]

. Open the controller cover by turning the thumbscrew counterclockwise to loosen, and then open the cover. 


== Step 5: Replace a DIMM

Locate the faulty DIMM inside the controller and replace it.

include::../_include/ge_dimm_replace.adoc[]


== Step 6: Reinstall the controller

Reinstall the controller into the chassis and reboot it.

include::../_include/ge_controller_reinstall.adoc[]


== Step 7: Place the controller back online

Place the controller online, collect support data, and resume operations.

include::../_include/ge_internal_frus_controller_back_online.adoc[]


== Step 8: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
