---
permalink: maintenance-ef50-ef80/drive-replace.html
sidebar: sidebar
keywords: ef50, ef80, replace the drives
summary: Replace a drive in your EF50 or EF80 storage system when a drive fails or requires an upgrade. The replacement process involves identifying the faulty drive, safely removing it, and installing a new drive to ensure continued data access and system performance.
---
= Replace a drive - EF50 and EF80
:icons: font
:imagesdir: ../media/

[.lead]
Replace a drive in your EF50 or EF80 storage system when a drive fails or requires an upgrade. The replacement process involves identifying the faulty drive, safely removing it, and installing a new drive to ensure continued data access and system performance.

.Before you begin

* Review link:drives-overview-supertask-concept.html[Requirements for EF300 or EF600 drive replacement].
* Make sure you have the following:
** A replacement drive that is supported by NetApp for your controller shelf or drive shelf.
** An ESD wristband, or you have taken other antistatic precautions.
** A flat, static-free work surface.
** A management station with a browser that can access SANtricity System Manager for the controller. (To open the System Manager interface, point the browser to the controller's domain name or IP address.)

.About this task
* You can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Using SANtricity System Manager, select *Hardware*, click the *Controller shelf* tab, and from the menu select *Turn on location light*. Location LEDs remain illuminated for 30 minutes.

include::../_include/ge_replace_drive.adoc[]
