---
permalink: maintenance-ef50-ef80/fan-replace.html
sidebar: sidebar
keywords: ef50, ef80, swap, out, fan, module, interrupt, service, sequence, task, hot-swap, hot-swap a fan module
summary: Replace a fan module in your EF50 or EF80 storage system when a fan fails or is not operating efficiently, as this can affect system cooling and overall performance.
---
= Replace a fan module - EF50 and EF80
:icons: font
:imagesdir: ../media/

[.lead]
Replace a fan module in your EF50 or EF80 storage system when a fan fails or is not operating efficiently, as this can affect system cooling and overall performance. 


.About this task
* The replacement process involves preparing to replace a fan, placing the controller offline, removing the controller, replacing the fan, reinstalling the controller, placing the controller back online, completing the fan replacement, and then returning the failed part to NetApp.

* You must place the impaired controller offline before unplugging any of its cables.

* Each controller includes five fans. If a fan fails, you must replace it as soon as possible to ensure that the controller has adequate cooling.

* You can turn on the storage system location (blue) LEDs (on the front of the storage system and both controllers) to aid in physically locating the affected storage system. Using SANtricity System Manager, select *Hardware* > *Controllers and components*, select the *Controller shelf* tab, and from the context menu select *Turn on locator light*.

== Step 1: Prepare to replace a fan

Complete the preparation steps to ensure a smooth and successful fan replacement.

//Prepare to replace a fan by confirming it is okay to replace the faulty fan, gathering the necessary tools and equipment, and backing up the storage system's configuration database.

include::../_include/ge_fan_replace_prepare.adoc[]


== Step 2: Place the controller offline

Place the impaired controller offline so you can safely perform the rest of this procedure.
 
include::../_include/ge_most_fru_replacements_offline_controller.adoc[]
 

== Step 3: Remove the controller

include::../_include/ge_controller_remove.adoc[]


== Step 4: Replace a fan

Locate the faulty fan inside the impaired controller and replace it.

include::../_include/ge_fan_replace.adoc[]


== Step 5: Reinstall the controller

Reinstall the controller into the chassis, reconnect its power cord, and all of its cables.

include::../_include/ge_controller_reinstall.adoc[]


== Step 6: Place the controller online

include::../_include/ge_most_fru_replacements_online_controller.adoc[]


== Step 7: Complete the fan replacement

include::../_include/ge_most_fru_replacements_complete_replacement.adoc[]


== Step 8: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
