---
permalink: maintenance-ef50-ef80/fan-replace.html
sidebar: sidebar
keywords: ef50, ef50c, ef80, ef80c, swap, out, fan, module, interrupt, service, sequence, task, hot-swap, hot-swap a fan module
summary: Replace a fan module in your EF50 or EF80 storage system when a fan fails or is not operating efficiently, as this can affect system cooling and overall performance. The replacement process involves shutting down the controller, removing the controller, replacing the fan, reinstalling the controller, and returning the failed part to NetApp.
---
= Replace a fan module - EF50, EF50C, EF80, and EF80C
:icons: font
:imagesdir: ../media/

[.lead]
Replace a fan module in your EF50, EF50C, EF80, or EF80C storage system when a fan fails or is not operating efficiently, as this can affect system cooling and overall performance. The replacement process involves shutting down the controller, removing the controller, replacing the fan, reinstalling the controller, and returning the failed part to NetApp.

.About this task
If needed, you can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Log into the BMC using SSH and enter the `system location-led _on_` command.

A storage system has three location LEDs: one on the operator display panel and one on each controller. Location LEDs remain illuminated for 30 minutes. 

You can turn them off by entering the `system location-led _off_` command. If you are unsure if the LEDs are on or off, you can check their state by entering the `system location-led show` command.

== Step 1: Shut down the impaired controller
 
Shut down or take over the impaired controller using one of the following options.
 
== Step 1: Place the impaired controller offline
 
Place the impaired controller offline so you can safely remove and replace the DIMMs.
 
include::../_include/ge_internal_frus_controller_shutdown.adoc[]

== Step 2: Remove the controller

include::../_include/ge_controller_remove.adoc[]

. Open the controller cover by turning the thumbscrew counterclockwise to loosen, and then open the cover.


== Step 3: Replace fan

include::../_include/ge_fan_replace.adoc[]


== Step 4: Reinstall the controller module

Reinstall the controller into the chassis and reboot it.

include::../_include/ge_controller_reinstall.adoc[]


== Step 5: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
