---
permalink: maintenance-ef50-ef80/io-module-overview.html
sidebar: sidebar
keywords: ef50, ef80, replace io module, upgrade io module, io module overview
summary: The EF50 and EF80 storage systems offer flexibility in replacing or upgrading I/O modules to enhance network connectivity and performance, and increase storage capacity.
---
= Overview of I/O module maintenance - EF50 and EF80
:icons: font
:imagesdir: ../media/

[.lead]
The EF50 and EF80 storage systems offer flexibility in replacing or upgrading I/O modules to enhance network connectivity and performance, and increase storage capacity.

* link:io-module-replace.html[Replace an I/O module]
+
When an I/O module in your storage system fails, you can replace it with the same type of I/O module to restore the storage system to its optimal operating state.

* link:io-module-upgrade.html[Upgrade an I/O module]
+
You can upgrade I/O modules in your storage system to increase the number of host ports for enhanced network connectivity, expand your system’s ability to handle data traffic, and connect SAS expansion shelves.
+
NOTE: SAS expansion I/O modules are supported on storage systems running SANtricity 12.10 or later.

// Aug 2026: updated to add SAS expansion content for 12.10 release.
 
