---
permalink: maintenance-ef50-ef80/io-module-change-protocol.html
sidebar: sidebar
keywords: host protocol change, EF50, EF80
summary: You can change the protocol on the host I/O modules in your EF50 or EF80 storage system when you need to use a different protocol on your existing I/O modules, as part of an I/O module upgrade, or when the default protocol on new controllers part of a new storage system installation or controller upgrade on an existing storage system is not the protocol you want.
---
= Change the host protocol - EF50 and EF80
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
// You can change the host port protocol on I/O modules using either Infiniband (IB) or Fibre Channel (FC) in an EF50 or EF80 storage system.

You can change the protocol on the host I/O modules in your EF50 or EF80 storage system when you need to use a different protocol on your existing I/O modules, as part of an I/O module upgrade, or when the default protocol on new controllers part of a new storage system installation or controller upgrade on an existing storage system is not the protocol you want.

// I'm not addressing all these use cases here? Only the change on existing modules? For the other 3 use cases, I need to embed steps in the right place for each procedure and each version of steps would mostly be unique per the use case? I need to understand if I got the uses cases right. TK seemed to think upgrading a module had nothing to do with changing the protocol, but customer would upgrade 

.About this task

* Changing the host port protocol involves preparing for the protocol change, stopping the host I/O operations, changing the protocol, and then configuring the host to use the new protocol.

* Host I/O protocol is changed on all host I/O modules in your storage system.

* Changing the host port protocol temporarily disrupts host access to all volumes and causes the storage system to be unavailable during the reboot process (both controllers are rebooted), which can take a few minutes.

//* New storage system installations and new controllers being used in a controller upgrade ship with a default host protocol. You need to check if the default host protocol is what you want and if not, you need to change it.


== Step 1: Prepare for the protocol change

Prepare to change the protocol on the host I/O modules in your storage system by verifying the current protocol on the host I/O modules, determining if you need to change the protocol, and if yes, then stopping host I/O operations, and obtaining any necessary hardware.

.Steps

. If you do not know the current protocol on the host I/O modules in your storage system, verify it now using SANtricity System Manager.

.. Select *Settings* > *System*.
.. In the *Additional Settings* section, choose *Change host I/O protocol* to open that page.
.. See the default host I/O protocol used on the host I/O modules in your storage system displayed in the *Host I/O Protocol* field.

. The next step depends on whether the default protocol is the protocol you want or not:
+
[options="header" cols="1,2"]
|===
|If...| Then...
a| 
The default protocol is the protocol you want
a|
No action is needed. You can exit this procedure
a|
The default protocol is not the protocol you want
a|You need to change it using SANtricity System Manager:

.. On the *Change host I/O protocol* page, click on the drop-down menu in the *Host I/O Protocol* field to see the supported protocol options.
.. Click the protocol you want to use.
.. Type *CHANGE* in the open field to confirm your change. 
.. Click the *Change* button.

. If the current protocol is not the protocol you want, continue with the next step; otherwise, you are done with this procedure.
//+
//. The next step depends on whether you need to change the protocol or not:
//+
//[options="header" cols="1,2"]
//|===
//|If...| Then...
//a|
//If you need to change the protocol
//a|
//Continue to the next step and then complete this procedure.
//a| If you do not need to change the protocol...| Then you can skip to the next section.
//|===
//+
. Schedule a downtime maintenance window for this procedure.

. If needed, obtain the necessary hardware for the conversion, which might include a new set of I/O modules and/or SFPs. Your NetApp Sales Representative can help you determine what hardware you need and help you order the correct parts.


== Step 2: Stop host I/O operations

You must stop all I/O operations from the host before changing the protocol of the host ports.

NOTE: You cannot access data on the storage system until you successfully complete the protocol change.

// include::../_include/ge_io_module_upgrade_power_off_controllers.adoc[]

.Steps

. Ensure that no I/O operations are occurring between the storage system and all connected hosts. For example, you can perform these steps:
 ** Stop all processes that involve the LUNs mapped from the storage to the hosts.
 ** Ensure that no applications are writing data to any LUNs mapped from the storage to the hosts.
 ** Unmount all file systems associated with volumes on the storage system.
+
NOTE: The exact steps to stop host I/O operations depend on the host operating system and the configuration, which are beyond the scope of these instructions. If you are not sure how to stop host I/O operations in your environment, consider shutting down the host or contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support^].
+
CAUTION: *Possible data loss* -- If you continue this procedure while I/O operations are occurring, you might lose data.
. Wait for any data in cache memory to be written to the drives.
+
The green Cache Active LED on the back of each controller is on when cached data needs to be written to the drives. You must wait for this LED to turn off.

. From the Home page of SANtricity System Manager, select *View Operations in Progress*.
. Wait for all operations to complete before continuing with the next step.

== Step 3: Change the protocol

Change the protocol of the host ports to a supported protocol.

//Need to create includes
//syntax example:
// include::../_include/ge_io_module_upgrade_power_off_controllers.adoc[]

.Steps

. From the Home page of SANtricity System Manager: 
.. Select *Settings* > *System*.
.. Scroll down the page to the "Additional Settings" section and click "Change host I/O protocol".
.. Choose the host I/O protocol you want from the drop down menu.
+
The host protocol field shows you the protocol currently on the host I/O modules in your storage system and the drop down menu lists the supported protocol options to choose from.
.. Type "CHANGE" to confirm your choice.
.. Click the Change button.

== Step 4: Configure the host to use the new protocol

After changing the protocol of the host ports, you must configure the host to use the new protocol.

// include::../_include/ge_io_module_upgrade_power_off_controllers.adoc[]

For step-by-step instructions, see the guide appropriate for your storage system:

* link:../config-linux/index.html[Linux express configuration]
+
* link:../config-vmware/index.html[VMware express configuration]
+
* link:../config-windows/index.html[Windows express configuration]
+
Specific settings might vary. Check the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix^] for specific instructions and additional recommended settings for your solution.




