---
permalink: maintenance-ef50-ef80/io-module-upgrade.html
sidebar: sidebar
keywords: ef50, ef80, upgrade io module, upgrade hic, upgrade host interface card
summary: You can upgrade I/O modules in your EF50 or EF80 storage system to increase the number of host ports for enhanced network connectivity and expand your system’s ability to handle data traffic. 
---
= Upgrade I/O modules - EF50 and EF80
:icons: font
:imagesdir: ../media/

[.lead]
You can upgrade I/O modules in your EF50 or EF80 storage system to increase the number of host ports for enhanced network connectivity and expand your system’s ability to handle data traffic. 


.About this task

* The term _I/O module_ is used instead of host interface cards (HICs) in this procedure.

* You can upgrade I/O modules by replacing existing I/O modules or adding I/O modules to unused I/O slots.
+
Unused I/O slots should have blanking modules installed to prevent possible thermal issues and for EMC compliance.

* Upgrade I/O modules by preparing, powering off both controllers, upgrading I/O modules in both controllers, powering on both controllers, verifying that the upgrade was successful, and if needed, verifying and changing the host I/O module protocol.
+
Controllers do not need to be removed from the chassis because the I/O modules are accessible with the controllers in place.

* You must power off both controllers before unplugging any I/O module cables.

* You can turn on the storage system location (blue) LEDs (on the front of the storage system and both controllers) to aid in physically locating the affected storage system. Using SANtricity System Manager, select *Hardware* > *Controllers and components*, select the *Controller shelf* tab, and from the context menu select *Turn on locator light*.

== Step 1: Prepare to upgrade I/O modules

Prepare to upgrade I/O modules by scheduling a downtime maintenance window, gathering the necessary tools and equipment, and backing up the storage system's configuration database.

include::../_include/ge_io_module_upgrade_prepare.adoc[]


== Step 2: Power off both controllers

Power off both controllers in the storage system so you can safely upgrade the I/O modules in both controllers.

include::../_include/ge_io_module_upgrade_power_off_controllers.adoc[]


== Step 3: Upgrade the I/O modules

Unplug cabling from the I/O modules you want to upgrade (unless you have I/O blanking modules), replace the I/O modules or the I/O blanking modules with the new I/O modules, and then cable the new I/O modules.

include::../_include/ge_io_module_upgrade_install_additional_modules.adoc[]


== Step 4: Power on both controllers

Power on both controllers.

include::../_include/ge_io_module_upgrade_power_on_controllers.adoc[]


== Step 5: Complete the I/O module upgrade

Using SANtricity System Manager, make sure the latest version of SANtricity OS is installed, verify that all volumes are returned to their owning controllers, collect support data so that you can resume operations, and if needed, verify and change the host I/O module protocol.

include::../_include/ge_io_module_upgrade_complete.adoc[]





