---
permalink: maintenance-ef50-ef80/io-module-replace.html
sidebar: sidebar
keywords: ef50, ef80 replace io module, replace hic, replace host interface card
summary: Replace a failed I/O module in your EF50 or EF80 storage system with the same type of I/O module to restore the storage system to its optimal operating state.
---
= Replace an I/O module - EF50 and EF80
:icons: font
:imagesdir: ../media/

[.lead]
Replace a failed I/O module in your EF50 or EF80 storage system with the same type of I/O module to restore the storage system to its optimal operating state. 

The replacement process involves placing the impaired controller offline, replacing the failed I/O module, bringing the controller back online, and returning the failed part to NetApp.


.Before you begin

* Schedule a downtime maintenance window for this procedure. You cannot access data on the storage system until you have successfully completed this procedure.

* Make sure that you are replacing the failed I/O module with the same type of I/O module. You cannot install a different type of I/O module. 
+
You must have the same type and number of I/O modules in each controller in your storage system.
+
CAUTION: *Possible loss of data access* -- The presence of incompatible or mismatched I/O modules causes the controllers to lock down when you apply power.
+
If needed, you can confirm supported I/O modules for your storage system at https://hwu.netapp.com[NetApp Hardware Universe^].

* Make sure you have the following:
** An ESD wristband, or you have taken other antistatic precautions.
** A flat, static-free surface.
** A management station with a browser that can access SANtricity System Manager for the controller.
+
To open the System Manager interface, point the browser to the controller's domain name or IP address.

* Unpack the replacement I/O module, and set it on a flat, static-free surface.
+
Save the packing materials to use when returning the failed I/O module to NetApp.


.About this task

* The term _I/O module_ is used instead of host interface cards (HICs) in this procedure.

* You can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Using SANtricity System Manager, select *Hardware*, click the *Controller shelf* tab, and from the menu select *Turn on location light*. Location LEDs remain illuminated for 30 minutes.


== Step 1: Offline the controller

include::../_include/ge_io_module_replace_offline_impaired_controller.adoc[]


== Step 2: Replace the I/O module

include::../_include/ge_io_module_replace_replace_failed_module.adoc[]


== Step 3: Bring the controller online

include::../_include/ge_io_module_replace_online_impaired_controller.adoc[]


== Step 4: Complete the I/O module replacement

include::../_include/ge_io_module_replace_complete.adoc[]


== Step 5: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]

