---
permalink: maintenance-ef50-ef80/nvdimm-battery-replace.html
sidebar: sidebar
keywords: ef50, ef80, replace the NV battery, NV battery
summary: Replace the NV battery in your EF50 or EF80 storage system when the battery begins to lose charge or fails, as it is responsible for preserving critical system data during power outages. The replacement process involves shutting down the impaired controller, removing the controller module, replacing the NV battery, reinstalling the controller module, and returning the failed part to NetApp.
---
= Replace the NV battery - EF50 and EF80
:icons: font
:imagesdir: ../media/

[.lead]
Replace the NV battery in your EF50 or EF80 storage system when the battery begins to lose charge or fails, as it is responsible for preserving critical system data during power outages. The replacement process involves placing the impaired controller offline, removing the controller, replacing the NV battery, reinstalling the controller, placing the controller back online, and then returning the failed part to NetApp.

.Before you begin
A battery is included with a controller and preserves cached data if the AC power fails.
* Verify that no volumes are in use or that you have a multipath driver installed on all hosts using these volumes.
* Review the link:batteries-overview-requirements-concept.html[Requirements for EF300 or EF600 battery replacement].
* Make sure you have the following:
** The replacement battery.
** An ESD wristband, or other antistatic precautions.
** A flat, static free work area.
** Labels to identify each cable that is connected to the controller canister.
** A management station with a browser that can access SANtricity System Manager for the controller. (To open the System Manager interface, point the browser to the controller's domain name or IP address.)

== Recovery Guru alerts

If the Recovery Guru in SANtricity System Manager reports one of following statuses, you must replace the affected battery:

* Battery Failed
* Battery Replacement Required

From SANtricity System Manager, review the details in the Recovery Guru to confirm that there is an issue with a battery and to ensure no other items must be addressed first.

== Requirements

If you plan to replace a battery, you must have:

* A replacement battery.
* An ESD wristband, or you have taken other antistatic precautions.
* Labels to identify each cable that is connected to the controller canister.
* A management station with a browser that can access SANtricity System Manager for the controller. (To open the System Manager interface, point the browser to the controller's domain name or IP address.)
+
Optionally, you can use the command line interface (CLI) to perform some of the procedures. If you do not have access to the CLI, you can do one of the following:

** *For SANtricity System Manager (version 11.60 and above)* -- Download the CLI package (zip file) from System Manager. Go to menu:Settings[System > Add-ons > Command Line Interface]. You can then issue CLI commands from an operating system prompt, such as the DOS C: prompt.

.About this task
* Each controller canister includes a battery that preserves cached data if the AC power fails. If the Recovery Guru in SANtricity System Manager reports either a Battery Failed status or a Battery Replacement Required status, you must replace the affected battery.

* You can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Using SANtricity System Manager, select *Hardware*, click the *Controller shelf* tab, and from the menu select *Turn on location light*. Location LEDs remain illuminated for 30 minutes.

== Step 1: Place the impaired controller offline
 
Back up the storage system's configuration database, and then place the impaired controller offline so you can safely replace a NV battery.
 
include::../_include/ge_internal_frus_controller_offline.adoc[]


== Step 2: Remove the controller

Remove the controller with the faulty NV battery from the chassis.

include::../_include/ge_controller_remove.adoc[]


== Step 3: Replace the NV battery

Locate the faulty NV battery inside the controller and replace it.

include::../_include/ge_nvdimm_battery_replace.adoc[]


== Step 4: Reinstall the controller

Reinstall the controller into the chassis.

include::../_include/ge_controller_reinstall.adoc[]


== Step 5: Place the controller back online

Place the controller back online, collect support data, and resume operations.

include::../_include/ge_internal_frus_controller_back_online.adoc[]


== Step 6: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]

