---
permalink: maintenance-ef50-ef80/nvdimm-battery-replace.html
sidebar: sidebar
keywords: ef50, ef80, replace the NV battery, NV battery
summary: Replace the NV battery in your EF50 or EF80 storage system when the battery begins to lose charge or fails, as it is responsible for preserving critical system data during power outages. The replacement process involves shutting down the impaired controller, removing the controller module, replacing the NV battery, reinstalling the controller module, and returning the failed part to NetApp.
---
= Replace the NV battery - EF50 and EF80
:icons: font
:imagesdir: ../media/

[.lead]
Replace the NV battery in your EF50 or EF80 storage system when the battery begins to lose charge or fails, as it is responsible for preserving critical system data during power outages. The replacement process involves placing the impaired controller offline, removing the controller, replacing the NV battery, reinstalling the controller, placing the controller back online, and then returning the failed part to NetApp.

.About this task
You can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Using SANtricity System Manager, select *Hardware*, click the *Controller shelf* tab, and from the menu select *Turn on location light*. Location LEDs remain illuminated for 30 minutes.

== Step 1: Place the impaired controller offline
 
Back up the storage system's configuration database, and then place the impaired controller offline so you can safely replace a NV battery.
 
include::../_include/ge_internal_frus_controller_offline.adoc[]


== Step 2: Remove the controller

Remove the controller with the faulty NV battery from the chassis.

include::../_include/ge_controller_remove.adoc[]


== Step 3: Replace the NV battery

Locate the faulty NV battery inside the controller and replace it.

include::../_include/ge_nvdimm_battery_replace.adoc[]


== Step 4: Reinstall the controller

Reinstall the controller into the chassis.

include::../_include/ge_controller_reinstall.adoc[]


== Step 5: Place the controller back online

Place the controller back online, collect support data, and resume operations.

include::../_include/ge_internal_frus_controller_back_online.adoc[]


== Step 6: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]

