---
permalink: maintenance-ef50-ef80/nvdimm-battery-replace.html
sidebar: sidebar
keywords: ef50, ef80, replace the NV battery, NV battery
summary: Replace the NV battery in your EF50 or EF80 storage system when the battery begins to lose charge or fails, as it is responsible for preserving critical system data during power outages.
---
= Replace the NV battery - EF50 and EF80
:icons: font
:imagesdir: ../media/

[.lead]
Replace the NV battery in your EF50 or EF80 storage system when the battery begins to lose charge or fails, as it is responsible for preserving critical system data during power outages. 

.Before you begin

* Confirm that the Recovery Guru in SANtricity System Manager reports either a _Battery Failed_ status or a _Battery Replacement Required_ status. If either status is reported, you must replace the affected NV battery.

* Make sure you address any other storage system issues. Using SANtricity System Manager, review the details in the Recovery Guru to see if there are any other issues.

* Make sure that no volumes are in use or that you have a multipath driver installed on all hosts using these volumes.

* Make sure you have the following:

** The replacement NV battery.
** An ESD wristband or other antistatic precautions.
** A flat static-free work surface.
** Labels to identify each cable that is connected to the impaired controller.
** A management station with a browser that can access SANtricity System Manager for the impaired controller.
+
To open the System Manager interface, point the browser to the impaired controller's domain name or IP address.
+
Optionally, you can use the command line interface (CLI) to perform some of the steps. To access the CLI, download the CLI package (zip file) from System Manager and then go to *Settings System > Add-ons > Command Line Interface*. You can then issue CLI commands from an operating system prompt, such as the DOS C: prompt.

* Back up the storage system's configuration database using SANtricity System Manager.
+
If a problem occurs when you remove a controller, you can use the saved file to restore your configuration. The system saves the current state of the RAID configuration database, which includes all data for volume groups and disk pools on the impaired controller.
+
.. Select *Support* > *Support Center* > *Diagnostics*.
.. Select *Collect Configuration Data*.
.. Select *Collect*.
+
The file is saved in the Downloads folder for your browser with the name, *configurationData-<arrayName>-<dateTime>.7z*.

.About this task

* The replacement process involves meeting the Before you begin requirements, placing the impaired controller offline, removing the controller, replacing the NV battery, reinstalling the controller, placing the controller back online, completing the NV battery replacement, and then returning the failed part to NetApp.

* You must place the impaired controller offline before unplugging any of its cables.

* You can turn on the storage system location (blue) LEDs (on the front of the storage system and both controllers) to aid in physically locating the affected storage system. Using SANtricity System Manager, select *Hardware* > *Controllers and components*, select the *Controller shelf* tab, and from the context menu select *Turn on locator light*.

== Step 1: Place the controller offline

include::../_include/ge_internal_frus_controller_offline.adoc[]


== Step 2: Remove the controller

include::../_include/ge_controller_remove.adoc[]


== Step 3: Replace the NV battery

Locate the faulty NV battery inside the impaired controller and replace it.

include::../_include/ge_nvdimm_battery_replace.adoc[]


== Step 4: Reinstall the controller

Reinstall the controller into the chassis, reconnect its power cord, and all of its cables.

include::../_include/ge_controller_reinstall.adoc[]


== Step 5: Place the controller online

include::../_include/ge_internal_frus_controller_back_online.adoc[]


== Step 6: Complete the NV battery replacement

Using SANtricity System Manager, ensure the latest version of SANtricity OS is installed, verify that all volumes are returned to their owning controllers and collect support data so that you can resume operations. 

include::../_include/ge_io_module_upgrade_complete.adoc[]


== Step 7: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]

