---
permalink: maintenance-ef50-ef80/nvdimm-battery-replace.html
sidebar: sidebar
keywords: ef50, ef80, replace the NV battery, NV battery
summary: Replace the NV battery in your EF50 or EF80 storage system when the battery begins to lose charge or fails, as it is responsible for preserving critical system data during power outages.
---
= Replace the NV battery - EF50 and EF80
:icons: font
:imagesdir: ../media/

[.lead]
Replace the NV battery in your EF50 or EF80 storage system when the battery begins to lose charge or fails, as it is responsible for preserving critical system data during power outages. 


.About this task

* The replacement process involves preparing to replace the NV battery, placing the impaired controller offline, removing the controller, replacing the NV battery, reinstalling the controller, placing the controller back online, completing the NV battery replacement, and then returning the failed part to NetApp.

* You must place the impaired controller offline before unplugging any of its cables.

* You can turn on the storage system location (blue) LEDs (on the front of the storage system and both controllers) to aid in physically locating the affected storage system. Using SANtricity System Manager, select *Hardware* > *Controllers and components*, select the *Controller shelf* tab, and from the context menu select *Turn on locator light*.

== Step 1: Prepare to replace the NV battery

Prepare to replace the NV battery by confirming the NV battery needs to be replaced, making sure there are no other storage system issues you need to address, making sure the volumes are in the correct state, gathering the necessary tools and equipment, and backing up the storage system's configuration database.

include::../_include/ge_nvdimm_battery_replace_prepare.adoc[]

== Step 2: Place the controller offline

Place the impaired controller offline so you can safely perform the rest of this procedure.

include::../_include/ge_most_fru_replacements_offline_controller.adoc[]


== Step 3: Remove the controller

include::../_include/ge_controller_remove.adoc[]


== Step 4: Replace the NV battery

Locate the faulty NV battery inside the impaired controller and replace it.

include::../_include/ge_nvdimm_battery_replace.adoc[]


== Step 5: Reinstall the controller

Reinstall the controller into the chassis, reconnect its power cord, and all of its cables.

include::../_include/ge_controller_reinstall.adoc[]


== Step 6: Place the controller online

include::../_include/ge_most_fru_replacements_online_controller.adoc[]


== Step 7: Complete the NV battery replacement

include::../_include/ge_most_fru_replacements_complete_replacement.adoc[]


== Step 8: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]

