---
permalink: maintenance-ef50-ef80/rtc-battery-replace.html
sidebar: sidebar
keywords: ef50, ef80, replace the real-time clock battery
summary: Replace the real-time clock (RTC) battery, commonly known as a coin cell battery, in your EF50 or EF80 storage system to ensure that services and applications relying on accurate time synchronization remain operational. 
---
= Replace the real-time clock battery - EF50, EF50C, EF80, and EF80C
:icons: font
:imagesdir: ../media/

[.lead]
Replace the real-time clock (RTC) battery, commonly known as a coin cell battery, in your EF50 or EF80 storage system to ensure that services and applications relying on accurate time synchronization remain operational. 

.Before you begin
//FYI: There is no E600 RTC FRU procedure to work from.
Make sure you have the following:

* A replacement RTC battery.
* An ESD wristband, or you have taken other antistatic precautions.
* A flat, static-free work surface.
* Labels to identify each cable that is connected to the impaired controller.
* A management station with a browser that can access SANtricity System Manager for the impaired controller.
+
To open the System Manager interface, point the browser to the impaired controller's domain name or IP address.

.About this task

* The replacement process involves placing the impaired controller offline, removing the controller, replacing the RTC battery, reinstalling the controller, placing the controller back online, resetting the time and date on the controller, and then returning the failed part to NetApp.

* You can turn on the storage system location (blue) LEDs (on the front of the storage system and both controllers) to aid in physically locating the affected storage system. Using SANtricity System Manager, select *Hardware*, click the *Controller shelf* tab, and from the menu select *Turn on location light*.

== Step 1: Place the impaired controller offline
 
Back up the storage system's configuration database and then place the impaired controller offline so you can safely replace the faulty RTC battery.
 
include::../_include/ge_internal_frus_controller_offline.adoc[]


== Step 2: Remove the controller

Remove the controller with the faulty RTC battery from the chassis.

include::../_include/ge_controller_remove.adoc[]
 

== Step 3: Replace the RTC battery

Locate the faulty RTC battery inside the controller and replace it.

include::../_include/ge_rtc_battery_replace.adoc[]


== Step 4: Reinstall the controller

include::../_include/ge_controller_reinstall.adoc[]


== Step 5: Place the controller back online

include::../_include/ge_internal_frus_controller_back_online.adoc[]

== Step 6: Reset the time and date on the controller

NOTE: After replacing the RTC battery, inserting the controller and powering on first BIOS reset, you will see the following error messages: 
`RTC date/time error. Reset date/time to default`
`RTC power failure error`
These messages are expected and you can continue with this procedure.

. On the healthy controller, check the date and time:
+
`cluster date show`
+
NOTE: If your storage system stops at the boot menu, select the option for  `Reboot node` and respond _y_ when prompted, then boot to LOADER by pressing _Ctrl-C_.
+
. On the impaired controller, at the LOADER prompt, check the time and date: 
+
`cluster date show`

.. If necessary, modify the date: 
+
`set date _mm/dd/yyyy_`

.. If necessary, set the time, in GMT: 
+
`set time hh:mm:ss`

.. Confirm the date and time.
. At the LOADER prompt, enter `bye` to reinitialize the I/O modules, other components, and let the controller reboot.

== Step 7: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
