---
permalink: maintenance-ef50-ef80/rtc-battery-replace.html
sidebar: sidebar
keywords: ef50, ef80, replace the real-time clock battery
summary: Replace the real-time clock (RTC) battery, commonly known as a coin cell battery, in your EF50 or EF80 storage system to ensure that services and applications relying on accurate time synchronization remain operational.
---
= Replace the real-time clock battery - EF50, EF50C, EF80, and EF80C
:icons: font
:imagesdir: ../media/

[.lead]
Replace the real-time clock (RTC) battery, commonly known as a coin cell battery, in your EF50 or EF80 storage system to ensure that services and applications relying on accurate time synchronization remain operational.


.Before you begin
All other components in the storage system must be functioning properly; if not, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support] before continuing with this procedure.

.About this task
* You can use this procedure with all versions of ONTAP supported by your storage system.
* You can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Using SANtricity System Manager, select *Hardware*, click the *Controller shelf* tab, and from the menu select *Turn on location light*. Location LEDs remain illuminated for 30 minutes.

== Step 1: Place the impaired controller offline
 
Place the impaired controller offline so you can safely remove and replace the DIMMs.
 
include::../_include/ge_internal_frus_controller_shutdown.adoc[]

== Step 2: Remove the controller

include::../_include/ge_controller_remove.adoc[]

. Open the controller cover by turning the thumbscrew counterclockwise to loosen, and then open the cover.
 
== Step 3: Replace the RTC battery

include::../_include/ge_rtc_battery_replace.adoc[]


== Step 4: Reinstall the controller

Reinstall the controller into the chassis and reboot it.

include::../_include/ge_controller_reinstall.adoc[]

== Step 5: Reset the time and date on the controller

NOTE: After replacing the RTC battery, inserting the controller and powering on first BIOS reset, you will see the following error messages: 
`RTC date/time error. Reset date/time to default`
`RTC power failure error`
These messages are expected and you can continue with this procedure.

. On the healthy controller, check the date and time:
+
`cluster date show`
+
NOTE: If your storage system stops at the boot menu, select the option for  `Reboot node` and respond _y_ when prompted, then boot to LOADER by pressing _Ctrl-C_.
+
. On the impaired controller, at the LOADER prompt, check the time and date: 
+
`cluster date show`

.. If necessary, modify the date: 
+
`set date _mm/dd/yyyy_`

.. If necessary, set the time, in GMT: 
+
`set time hh:mm:ss`

.. Confirm the date and time.
. At the LOADER prompt, enter `bye` to reinitialize the I/O modules, other components, and let the controller reboot.

== Step 6: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
