---
permalink: install-hw-ef50-ef50c-ef80-ef80c/install-prepare.html
sidebar: sidebar
keywords: 
summary: Prepare to install your EF50, EF50C, EF80, or EF80C storage system by getting the site ready, unpacking the boxes and comparing the contents to the packing slip, and registering the storage system to access support benefits.
---
= Prepare to install - EF50, EF50C, EF80, and EF80C
:icons: font
:imagesdir: ../media/

[.lead]
Prepare to install your EF50, EF50C, EF80, or EF80C storage system by getting the site ready, understanding the lifting precautions for your storage system, unpacking the boxes and comparing the contents to the packing slip, and registering the storage system to access support benefits.

== Step 1: Prepare the site
Ensure that the site and the cabinet or rack that you plan to use meet specifications for your configuration.

.Steps

. Use https://hwu.netapp.com[NetApp Hardware Universe^] to confirm that your site meets the environmental and electrical requirements for your storage system.

. Make sure you have adequate cabinet or rack space for your storage system and any switches.
+
If needed, see https://hwu.netapp.com[NetApp Hardware Universe^] for the exact dimensions of your storage system.
+
** 2U for a storage system
** 1U for most switches

. Install any required network switches.
// +
// See the https://docs.netapp.com/us-en/ontap-systems-switches/index.html[Switch documentation^] for installation instructions and link:https://hwu.netapp.com[NetApp Hardware Universe^] for compatibility information.

. Make sure you have a supported browser for the management software:

*** Google Chrome (version 89 and later)
*** Microsoft Edge (version 90 and later)
*** Mozilla Firefox (version 80 and later)
*** Safari (version 14 and later)

. Obtain the following equipment and tools needed for installation:

** Electrostatic discharge (ESD) strap
** Philips #2 screwdriver
** Flashlight

== Step 2: Understand the lifting precautions
Before you unpack the boxes (and later when you install your storage system) you should understand the weight of your storage system so that you can take the necessary precautions when lifting and moving it.

An EF50, EF50C, EF80, or EF80C storage system can weigh up to 61.5 lbs (27.9 kg). To lift the storage system, use two people or a hydraulic lift.

image::../media/drw_g_lifting_weight_ieops-1831.svg[AFF A20 A30 A50 and C30 and C60 weight caution icon]

== Step 3: Unpack the boxes
After you've ensured that the site and the cabinet or rack that you plan to use meet the specifications for your storage system, and you understand the lifting precautions, unpack all boxes and compare the contents to the items on the packing slip.

.Steps

. Carefully open all the boxes and lay out the contents in an organized manner.

. Compare the contents you’ve unpacked with the packing slip.
+
You can get your packing slip by scanning the QR code on the side of the shipping box.
+
NOTE: If there are any discrepancies, note them down for further action.

+
The following items are some of the contents you might see in the boxes. 
+
If needed, see https://hwu.netapp.com/[NetApp Hardware Universe] for other supported cables and identify their use.
+
[%rotate, grid="none", frame="none", cols="9,9,5"]
|===
|*Hardware*
|*Cables* |
a|* Bezel
* Storage system with drives
* Rack-mount hardware with instructions 
a|
* RJ-45 Ethernet cables for the Management port connections

* I/O cables for the mirroring and data host connections

* Power cables for the power supply connections|
|===


== Step 4: Register your storage system
After you've ensured that your site meets the specifications for your storage system, and you've verified that you have all the parts you ordered, you should register your storage system.

. Create an account and register your hardware at http://mysupport.netapp.com/[NetApp Support^].

.What's next?
After you’ve prepared to install your storage system, you link:install-hardware.html[install the hardware].


=================================================
OR use ONTAP-side content as a base and update with above E-Series content as needed

== Step 3: Register your storage system
After you've ensured that your site meets the requirements for your storage system specifications, and you've verified that you have all the parts you ordered, you should register your storage system.

.Steps

. Locate the System Serial Numbers (SSN) for each controller in your storage system.
+
image::../media/drw_ssn_label.svg[Example of the system serial number label,width=200]
+
You can find the serial numbers in the following locations:

- On each controller
- On the packing slip
- In your confirmation email

. Go to the http://mysupport.netapp.com/[NetApp Support Site^].
. Determine whether you need to register your storage system:
+
[cols="1a,2a" options="header"]
|===
| If you are a...| Follow these steps...
a|
Existing NetApp customer
a|

 .. Sign in with your username and password.
 .. Select *Systems* > *My Systems*.
 .. Confirm that the new serial numbers are listed.
 .. If it is not, follow the instructions for new NetApp customers.

a|
New NetApp customer
a|

 .. Click *Register Now*, and create an account.
 .. Select *Systems* > *Register Systems*.
 .. Enter the storage system's serial numbers and requested details.

After your registration is approved, you can download any required software. The approval process might take up to 24 hours.
|===

.What's next?
After you’ve prepared to install your storage system, you link:install-hardware.html[install the hardware].