== Step 1: Prepare to replace the controller

Prepare to replace a controller canister by saving the drive security key, backing up the configuration, and collecting support data. Then, you can stop host I/O operations and take the controller offline.


.Steps

. Unpack the new controller canister, and set it on a flat, static-free surface.
+
Save the packing materials to use when shipping the failed controller canister.
. Locate the MAC address and FRU part number labels on the back of the controller canister.
. From SANtricity System Manager, locate the replacement part number for the controller canister you are replacing.
+
When a controller has a fault and needs to be replaced, the replacement part number is displayed in the Details area of the Recovery Guru. If you need to find this number manually, follow these steps:

.. Select *Hardware*.
.. Locate the controller shelf, which is marked with the controller icon.
.. Click the controller icon.
.. Select the controller, and click *Next*.
.. On the *Base* tab, make a note of the *Replacement Part Number* for the controller.
. Confirm that the replacement part number for the failed controller is the same as the FRU part number for the replacement controller.
+
CAUTION: *Possible loss of data access* — If the two part numbers are not the same, do not attempt this procedure. The presence of mismatched controllers will cause the new controller to lock down when you bring it online.
. Back up the storage array's configuration database using SANtricity System Manager.
+
If a problem occurs when you remove a controller, you can use the saved file to restore your configuration. The system will save the current state of the RAID configuration database, which includes all data for volume groups and disk pools on the controller.

** From System Manager:
.. Select *Support › Support Center › Diagnostics*.
.. Select *Collect Configuration Data*.
.. Click *Collect*.
+
The file is saved in the Downloads folder for your browser with the name, *configurationData-<arrayName>-<dateTime>.7z*.

** Alternatively, you can back up the configuration database by using the following CLI command:
+
----
save storageArray dbmDatabase sourceLocation=onboard contentType=all file="filename";
----

. Collect support data for your storage system using SANtricity System Manager.

If a problem occurs when you remove a controller, you can use the saved file to troubleshoot the issue. The system will save inventory, status, and performance data about your storage system in a single file.

.. *Select Support › Support Center › Diagnostics*.
.. Select *Collect Support Data*.
.. Click *Collect*.
+
The file is saved in the Downloads folder for your browser with the name, *support-data.7z*.

== Step 1: Take the controller offline

If the impaired controller is not already offline, take it offline using SANtricity System Manager.

.Steps

. If the impaired controller is not already offline, take it offline now using SANtricity System Manager.

** From SANtricity System Manager:
.. Select *Hardware*.
.. If the graphic shows the drives, select *Show back of shelf* to show the controllers.
.. Select the controller that you want to place offline.
.. From the context menu, select *Place offline*, and confirm that you want to perform the operation.
+
NOTE: If you are accessing SANtricity System Manager using the controller you are attempting to take offline, a SANtricity System Manager Unavailable message is displayed. Select Connect to an alternate network connection to automatically access SANtricity System Manager using the other controller.

** Alternatively, you can take the controllers offline by using the following CLI commands:
+
*For controller A*: `set controller [a] availability=offline`
+
*For controller B*: `set controller [b] availability=offline`
. Wait for SANtricity System Manager to update the controller's status to offline.
+
CAUTION: Do not begin any other operations until after the status has been updated.
. Select *Recheck* from the Recovery Guru, and confirm that the *OK to remove* field in the Details area displays *Yes*, indicating that it is safe to remove this component.
