---
permalink: maintenance-ef600/batteries-overview-requirements-concept.html
sidebar: sidebar
keywords: replace battery,battery fail, EF300C, EF600C, EF300, EF600
summary: Requirements and considerations for EF300 or EF600 battery replacement.
---
= Requirements to replace the battery - EF300 or EF600
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
Before you replace an EF300, EF600, EF300C, or EF600C battery, review the requirements and considerations.

A battery is included with a controller and preserves cached data if the AC power fails.

== Recovery Guru alerts

If the Recovery Guru in SANtricity System Manager reports one of following statuses, you must replace the affected battery:

* Battery Failed
* Battery Replacement Required

From SANtricity System Manager, review the details in the Recovery Guru to confirm that there is an issue with a battery and to ensure no other items must be addressed first.

== Procedure overview

To protect your data, you must replace a failed battery as soon as possible.

The following is an overview of the steps to replace a battery in EF300 or EF600  controllers:

. Take controller offline.
. Remove the controller canister.
. Replace the battery.
. Replace the controller canister.
. Bring the controller online.

== Requirements

If you plan to replace a battery, you must have:

* A replacement battery.
* An ESD wristband, or you have taken other antistatic precautions.
* Labels to identify each cable that is connected to the controller canister.
* A management station with a browser that can access SANtricity System Manager for the controller. (To open the System Manager interface, point the browser to the controller's domain name or IP address.)
+
Optionally, you can use the command line interface (CLI) to perform some of the procedures. If you do not have access to the CLI, you can do one of the following:

** *For SANtricity System Manager (version 11.60 and above)* -- Download the CLI package (zip file) from System Manager. Go to menu:Settings[System > Add-ons > Command Line Interface]. You can then issue CLI commands from an operating system prompt, such as the DOS C: prompt.
