---
permalink: maintenance-ef600/batteries-overview-requirements-concept.html
sidebar: sidebar
keywords: replace EF300 battery, replace EF600 battery, EF300 battery fail, EF600 battery fail
summary: Requirements and considerations for EF300 or EF600 battery replacement.
---
= Requirements for EF300 or EF600 battery replacement
:icons: font
:imagesdir: ../media/

[.lead]
Before you replace an EF300 or EF600 battery, review the requirements and considerations.

A battery is included with a controller and preserves cached data if the AC power fails.

== Recovery Guru alerts

If the Recovery Guru in SANtricity System Manager reports one of following statuses, you must replace the affected battery:

* Battery Failed
* Battery Replacement Required

From SANtricity System Manager, review the details in the Recovery Guru to confirm that there is an issue with a battery and to ensure no other items must be addressed first.

== Procedure overview

To protect your data, you must replace a failed battery as soon as possible.

The following is an overview of the steps to replace a battery in EF300 or EF600  controllers:

. Take controller offline.
. Remove the controller canister.
. Replace the battery.
. Replace the controller canister.
. Bring the controller online.

== Requirements

If you plan to replace a battery, keep the following requirements in mind.

* You must install SANtricity Storage Manager on a management station, so you can use the storage array's command line interface (CLI).
+
If this software has not yet been installed, follow the instructions in the link:../config-linux/index.html[Linux express configuration], link:../config-windows/index.html[Windows express configuration], or link:../config-vmware/index.html[VMware express configuration] to download and install it.

* You must have a replacement battery.
* You must have an ESD wristband, or you have taken other antistatic precautions.
* You must use labels to identify each cable that is connected to the controller canister.
