---
permalink: maintenance-ef600/concept_overview_and_requirements_hics.html
sidebar: sidebar
keywords: 
summary: ''
---
= Overview and Requirements
:icons: font
:imagesdir: ../media/

[.lead]
If you plan to upgrade or replace a host interface card (HIC), keep the following requirements in mind.

* You have scheduled a downtime maintenance window for this procedure. You cannot access data on the storage array until you have successfully completed this procedure. Because both controllers must have the same HIC configuration when they are powered on, the power must be off when you change HIC configuration. The presence of mismatched HICs causes the controller with the replacement HIC to lock down when you bring it online.
* You have all cables, transceivers, switches, and host bus adapters (HBAs) needed to connect the new host ports.
+
For information about compatible hardware, refer to the https://mysupport.netapp.com/NOW/products/interoperability[NetApp Interoperability Matrix] or the http://hwu.netapp.com/home.aspx[NetApp Hardware Universe].

* You have an ESD wristband, or you have taken other antistatic precautions.
* You have a #1 Phillips screwdriver.
* You have labels to identify each cable that is connected to the controller canister.
* You have installed SANtricity Storage Manager on a management station, so you can use the storage array's command line interface (CLI).
+
If SANtricity Storage Manager has not yet been installed, follow the instructions in the link:../com.netapp.doc.ssm-exp-ic-lin/home.html[Linux express configuration], link:../com.netapp.doc.ssm-exp-ic-win/home.html[Windows express configuration], or link:../com.netapp.doc.ssm-exp-ic-vm/home.html[VMware express configuration] to download and install the software.

* Some HIC replacements or upgrades may require a host port protocol conversion. Follow the instructions in the xref:concept_host_port_protocol_conversion_wombat.adoc[Host port protocol] section for this requirement.
* EF300 controllers must have HIC port 2 filled with a HIC for host connectivity.

This section describes how to prepare to add a host interface card in the following controller shelves:

* EF600 controller shelf

This section describes how to prepare to replace or upgrade a host interface card in the following controller shelves:

* EF300 controller shelf
* EF600 controller shelf
