---
permalink: maintenance-ef600/concept_requirements_for_replacing_a_battery.html
sidebar: sidebar
keywords: 
summary: ''
---
= Overview and requirements
:icons: font
:imagesdir: ../media/

[.lead]
Before you replace a battery, you need to be aware of certain requirements and considerations.

== Requirements for replacing a battery

[.lead]
If you plan to replace a failed battery, keep the following requirements in mind.

=== Recovery Guru alerts

If the Recovery Guru in SANtricity System Manager reports one of following statuses, you must replace the affected battery:

* Battery Failed
* Battery Replacement Required

From SANtricity System Manager, review the details in the Recovery Guru to confirm that there is an issue with a battery and to ensure no other items must be addressed first.

=== Requirements for replacing a battery

If you plan to replace a battery, keep the following requirements in mind.

* You must have installed SANtricity Storage Manager on a management station, so you can use the storage array's command line interface (CLI).
+
If this software has not yet been installed, follow the instructions in the link:../com.netapp.doc.ssm-exp-ic-lin/home.html[Linux express configuration], link:../com.netapp.doc.ssm-exp-ic-win/home.html[Windows express configuration], or link:../com.netapp.doc.ssm-exp-ic-vm/home.html[VMware express configuration] to download and install it.

* You must have a replacement battery.
* You have an ESD wristband, or you have taken other antistatic precautions.
* You must use labels to identify each cable that is connected to the controller canister.

This section describes how to replace a battery in the following controller shelves:

* EF300 controller shelf
* EF600 controller shelf
