---
permalink: maintenance-ef600/controllers-overview-supertask-concept.html
sidebar: sidebar
keywords: replace controller, EF300, EF600, EF300C, EF600C
summary:  Requirements and considerations for EF300 or EF600 controller replacement
---
= Requirements to replace the controller - EF300 or EF600
:icons: font
:imagesdir: ../media/

[.lead]
Before you replace an EF300, EF600. EF300C, or EF600C controller, review the requirements and considerations.

A controller consists of a board, firmware, and software. It controls the drives and implements the SANtricity System Manager functions.

== Controller replacement requirements

Before you replace a controller, you must have:

* A replacement controller canister with the same part number as the controller canister you are replacing.
* An ESD wristband, or you have taken other antistatic precautions.
* Labels to identify each cable that is connected to the controller canister.
* A #1 Phillips screwdriver.
* A management station with a browser that can access SANtricity System Manager for the controller. (To open the System Manager interface, point the browser to the controller's domain name or IP address.)

== Replacement while powered on

You can replace a controller canister while your storage array is powered on and performing host I/O operations, if the following conditions are true:

* The second controller canister in the shelf has Optimal status.
* The *OK to remove* field in the Details area of the Recovery Guru in SANtricity System Manager displays *Yes*, indicating that it is safe to remove this component.
