---
permalink: maintenance-ef600/controllers-overview-supertask-concept.html
sidebar: sidebar
keywords: replace EF300 controller, replace EF600 controller,
summary:  Requirements and considerations for EF300 or EF600 controller replacement
---
= Requirements for EF300 or EF600 controller replacement
:icons: font
:imagesdir: ../media/

[.lead]
Before you replace an EF300 or EF600 controller, review the requirements and considerations.

A controller consists of a board, firmware, and software. It controls the drives and implements the SANtricity System Manager functions.

== Controller replacement requirements

* You must have a replacement controller canister with the same part number as the controller canister you are replacing.
* You have an ESD wristband, or you have taken other antistatic precautions.
* You must use labels to identify each cable that is connected to the controller canister.
* You must have a #1 Phillips screwdriver.
* You must have installed SANtricity Storage Manager on a management station, so you can use the storage array's command line interface (CLI).
+
If this software has not yet been installed, follow the instructions in the link:../config-linux/index.html[Linux express configuration], link:../config-windows/index.html[Windows express configuration], or link:../config-vmware/index.html[VMware express configuration] to download and install it.

== Replacement while powered on

You can replace a controller canister while your storage array is powered on and performing host I/O operations, if the following conditions are true:

* The second controller canister in the shelf has Optimal status.
* The *OK to remove* field in the Details area of the Recovery Guru in SANtricity System Manager displays *Yes*, indicating that it is safe to remove this component.
