---
permalink: maintenance-ef600/controllers_overview_supertask_concept.html
sidebar: sidebar
keywords: 
summary: ''
---
= Overview and requirements
:icons: font
:imagesdir: ../media/

[.lead]
Before you replace a controller, you need to be aware of certain requirements and considerations.

== Requirements for replacing a controller

[.lead]
If you plan to replace a controller, keep the following requirements in mind.

=== Requirements for replacing a failed controller

* You must have a replacement controller canister with the same part number as the controller canister you are replacing.
* You have an ESD wristband, or you have taken other antistatic precautions.
* You must use labels to identify each cable that is connected to the controller canister.
* You must have a #1 Phillips screwdriver.
* You must have installed SANtricity Storage Manager on a management station, so you can use the storage array's command line interface (CLI).
+
If this software has not yet been installed, follow the instructions in the link:../com.netapp.doc.ssm-exp-ic-lin/home.html[Linux express configuration], link:../com.netapp.doc.ssm-exp-ic-win/home.html[Windows express configuration], or link:../com.netapp.doc.ssm-exp-ic-vm/home.html[VMware express configuration] to download and install it.

You can replace a controller canister while your storage array is powered on and performing host I/O operations, if the following conditions are true:

* The second controller canister in the shelf has Optimal status.
* The *OK to remove* field in the Details area of the Recovery Guru in SANtricity System Manager displays *Yes*, indicating that it is safe to remove this component.

This section describes how to replace a controller canister in the following controller shelves:

* EF300 controller shelf
* EF600 controller shelf
