---
permalink: maintenance-ef600/task_complete_protocol_conversion.html
sidebar: sidebar
keywords: 
summary: ''
---
= Complete host protocol conversion
:icons: font
:imagesdir: ../media/

[.lead]
After converting the protocol of the host ports, you need to perform additional steps before you can use the new protocol.

== Complete protocol conversion

[.lead]
After you apply the feature pack key to convert the protocol you must configure the host to use the appropriate protocol.

. Configure the host to use the appropriate protocol.
+
For step-by-step instructions on how to configure the host, see the guide appropriate for your system:
+
link:../com.netapp.doc.ssm-exp-ic-lin/home.html[Linux express configuration]
+
link:../com.netapp.doc.ssm-exp-ic-vm/home.html[VMware express configuration]
+
link:../com.netapp.doc.ssm-exp-ic-win/home.html[Windows express configuration]
+
Specific settings might vary. Check the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix] for specific instructions and additional recommended settings for your solution.

Your host protocol conversion is complete. You can resume normal operations.
