---
permalink: maintenance-ef50-ef50c-ef80-ef80c/dimm-replace.html
sidebar: sidebar
keywords: ef50, ef50c, ef80, ef80c, replace a dimm
summary: Replace a DIMM in your EF50, EF50C, EF80, or EF80C storage system if excessive correctable or uncorrectable memory errors are detected. Such errors can prevent the storage system from booting ONTAP. The replacement process involves shutting down the impaired controller, removing it, replacing the DIMM, reinstalling the controller, and then returning the failed part to NetApp.
---
= Replace a DIMM - EF50, EF50C, EF80, and EF80C
:icons: font
:imagesdir: ../media/

[.lead]
Replace a DIMM in your EF50, EF50C, EF80, or EF80C storage system if excessive correctable or uncorrectable memory errors are detected. Such errors can prevent the storage system from booting ONTAP. The replacement process involves shutting down the impaired controller, removing it, replacing the DIMM, reinstalling the controller, and then returning the failed part to NetApp.


.Before you begin

* All other components in the storage system must be working correctly; if not, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support] before continuing.

* You must replace the failed FRU component with a replacement FRU component you received from your provider.

.About this task
If needed, you can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Log into the BMC using SSH and enter the `system location-led _on_` command.

A storage system has three location LEDs: one on the operator display panel and one on each controller. Location LEDs remain illuminated for 30 minutes. 

You can turn them off by entering the `system location-led _off_` command. If you are unsure if the LEDs are on or off, you can check their state by entering the `system location-led show` command.

== Step 1: Place the impaired controller offline
 
Place the impaired controller offline so you can safely remove and replace the DIMMs.
 
include::../_include/ge_offline_controller.adoc[]



== Step 2: Remove the controller

include::../_include/ge_controller_remove.adoc[]

. Open the controller cover by turning the thumbscrew counterclockwise to loosen, and then open the cover. 


== Step 3: Replace a DIMM

To replace a DIMM, locate the faulty DIMM inside the controller and follow the specific sequence of steps.

include::../_include/ge_dimm_replace.adoc[]


== Step 4: Reinstall the controller

Reinstall the controller into the chassis and reboot it.

include::../_include/g_controller_reinstall.adoc[]

== Step 5: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
