---
permalink: maintenance-ef50-ef50c-ef80-ef80c/io-module-replace.html
sidebar: sidebar
keywords: ef50, ef50c, ef80, ef80c, replace a pcie card
summary: Replace an I/O module in your EF50, EF50C, EF80, or EF80C storage system when the module fails or requires an upgrade to support higher performance or additional features. The replacement process involves shutting down the controller, replacing the failed I/O module, rebooting the controller, and returning the failed part to NetApp.
---
= Replace an I/O module - EF50, EF50C, EF80, and EF80C
:icons: font
:imagesdir: ../media/

[.lead]
Replace an I/O module in your EF50, EF50C, EF80, or EF80C storage system when the module fails or requires an upgrade to support higher performance or additional features. The replacement process involves shutting down the controller, replacing the failed I/O module, rebooting the controller, and returning the failed part to NetApp.

.Before you begin
All other components in the storage system must be functioning properly; if not, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support] before continuing with this procedure.

.About this task

If needed, you can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Log into the BMC using SSH and enter the `system location-led _on_` command.

A storage system has three location LEDs: one on the operator display panel and one on each controller. Location LEDs remain illuminated for 30 minutes. 

You can turn them off by entering the `system location-led _off_` command. If you are unsure if the LEDs are on or off, you can check their state by entering the `system location-led show` command.


== Step 1: Place the impaired controller offline
 
Place the impaired controller offline so you can safely remove and replace the DIMMs.
 
include::../_include/ge_offline_controller.adoc[]


== Step 2: Replace a failed I/O module

include::../_include/ge_io_module_replace.adoc[]


== Step 3: Reboot the controller

include::../_include/io_module_replace_reboot.adoc[]


== Step 4: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
