---
permalink: maintenance-ef50-ef50c-ef80-ef80c/nvdimm-battery-replace.html
sidebar: sidebar
keywords: ef50, ef50c, ef80, ef80c, replace the NV battery, NV battery
summary: Replace the NV battery in your EF50, EF50C, EF80, or EF80C storage system when the battery begins to lose charge or fails, as it is responsible for preserving critical system data during power outages. The replacement process involves shutting down the impaired controller, removing the controller module, replacing the NV battery, reinstalling the controller module, and returning the failed part to NetApp.
---
= Replace the NV battery - EF50, EF50C, EF80, and EF80C
:icons: font
:imagesdir: ../media/

[.lead]
Replace the NV battery in your EF50, EF50C, EF80, or EF80C storage system when the battery begins to lose charge or fails, as it is responsible for preserving critical system data during power outages. The replacement process involves shutting down the impaired controller, removing the controller module, replacing the NV battery, reinstalling the controller module, and returning the failed part to NetApp.


.Before you begin
All other components in the storage system must be functioning properly; if not, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support] before continuing with this procedure.

.About this task
If needed, you can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Log into the BMC using SSH and enter the `system location-led _on_` command.

A storage system has three location LEDs: one on the operator display panel and one on each controller. Location LEDs remain illuminated for 30 minutes. 

You can turn them off by entering the `system location-led _off_` command. If you are unsure if the LEDs are on or off, you can check their state by entering the `system location-led show` command.

== Step 1: Place the impaired controller offline
 
Place the impaired controller offline so you can safely remove and replace the DIMMs.
 
include::../_include/ge_offline_controller.adoc[]

== Step 2: Remove the controller

include::../_include/ge_controller_remove.adoc[]

. Open the controller cover by turning the thumbscrew counterclockwise to loosen, and then open the cover.

== Step 3: Replace the NV battery

include::../_include/ge_nvdimm_battery_replace.adoc[]


== Step 4: Reinstall the controller

Reinstall the controller into the chassis and reboot it.

include::../_include/ge_controller_reinstall.adoc[]


== Step 5: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]

