---
permalink: config-windows/configure_multipath_software_task.html
sidebar: sidebar
keywords: multipath software for Windows, express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: Install DSM package, which contains multipath software for Windows.
---
= Configure the multipath software
:icons: font
:imagesdir: ../media/

[.lead]
Multipath software provides a redundant path to the storage array in case one of the physical paths is disrupted. Before you can use multipathing, you need to install the SANtricity Windows DSM package. This package contains the multipath software for Windows.

Windows installations use the native MPIO Device Specific Module (DSM) driver for failover. When you install and enable the `SANtricity Windows DSM` package, you do not need to take further action to use multipath.

== Installing SANtricity Windows DSM package

[.lead]
Perform the following steps to install the `SANtricity Windows DSM` package and use the multipath package for Windows.

===== Before you begin

* You must have the correct administrator or superuser privileges.

You will install the `SANtricity Windows DSM` package on the management station.

===== Steps

. Download the `SANtricity Windows DSM` package from the SANtricity OS software page (https://mysupport.netapp.com/products/p/eseries_santricityos.html).
. Run the `SANtricity Windows DSM` installer. Double-click the install package to execute.
. Use the installation wizard to install the package on the management station.
