---
permalink: config-windows/index.html
sidebar: sidebar
keywords: express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: Use the express configuration for a Windows host with an E-Series system.
---
= Windows express configuration overview
:icons: font
:imagesdir: ../media/

[.lead]
The Windows express method for installing your storage array and accessing SANtricity System Manager is appropriate for setting up a standalone Windows host to an E-Series system. It is designed to get the storage system up and running as quickly as possible with minimal decision points.

=== Procedure overview

The express method includes the following steps, which are also outlined in the link:understand-windows-concept.html[Windows workflow].

. Set up one of the following communication environments:

* link:fc-perform-specific-task.html[Fibre Channel (FC)]
* link:iscsi-perform-specific-task.html[iSCSI]
* link:sas-perform-specific-task.html[SAS]

. Create logical volumes on the storage array.

. Make the volumes available to the data host.

=== Find more information

* Online help -- Describes how to use SANtricity System Manager to complete configuration and storage management tasks. It is available within the product.
* https://kb.netapp.com/[NetApp Knowledgebase^] (a database of articles) -- Provides troubleshooting information, FAQs, and instructions for a wide range of NetApp products and technologies.
* http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^] -- Enables you to search for configurations of NetApp products and components that meet the standards and requirements specified by NetApp.
* http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61343[NetApp Documentation: Host Utilities^] -- Provides documentation for the current Windows Unified Host Utilities version.
