---
permalink: config-windows/index.html
sidebar: sidebar
keywords: express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries
summary: Use the express configuration for a Windows host with an E-Series system.
---
= Windows express configuration overview
:icons: font
:imagesdir: ../media/

[.lead]
The Windows express method for installing your storage array and accessing SANtricity System Manager is appropriate for setting up a standalone Windows host to an E-Series system. It is designed to get the storage system up and running as quickly as possible with minimal decision points.

=== Procedure overview

The express method includes the following steps.

. Setting up one of the following communication environments:
 ** Fibre Channel (FC)
 ** iSCSI
 ** SAS
. Creating logical volumes on the storage array.
. Making the volumes available to the data host.

=== Find more information

* Online help -- Describes how to use SANtricity System Manager to complete configuration and storage management tasks. It is available within the product.
* https://kb.netapp.com/app/[NetApp Knowledgebase] (a database of articles) -- Provides troubleshooting information, FAQs, and instructions for a wide range of NetApp products and technologies.
* Windows Unified Host Utilities 7.0 Installation Guide under the NetApp Documentation -- Host Utilities (current releases) describes how to install and use the Windows Unified Host Utilities 7.0.
