---
permalink: config-windows/install-configure-host-utilities-task.html
sidebar: sidebar
keywords: Windows Unified Host Utilities, express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries, SMcli, SMdevices
summary: Install Windows Unified Host Utilities for Windows express method.
---
= Install and configure Linux Unified Host Utilities in E-Series - Windows
:icons: font
:imagesdir: ../media/

[.lead]
The Windows Unified Host Utilities tools help you to connect host computers to NetApp storage systems and set required parameters on host computers. You can also set appropriate disk timeouts for best read/write performance with NetApp storage.

NOTE: For more information, see the _Windows Host Utilities Installation Guide,_ found under http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61343[NetApp Documentation: Host Utilities^].

.Steps

. Use the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^] to determine the appropriate version of Unified Host Utilities to install.
+
The versions are listed in a column within each supported configuration.

. Download the Unified Host Utilities from http://mysupport.netapp.com[NetApp Support^].
+
NOTE: This utilities package cannot be installed using the SANtricity Storage Manager installer.
+
NOTE: Alternatively, you can use the SMcli command `-identifyDevices` to perform the same functions as the Unified Host Utility tool. The SMcli is included in the SANtricity OS and downloadable through the SANtricity System Manager. For more information on how to download the SMcli through the SANtricity System Manager, refer to the https://docs.netapp.com/us-en/e-series-santricity/sm-settings/download-cli.html[Download command line interface (CLI) topic under the SANtricity System Manager Online Help^].
