---
permalink: upgrade-controllers/complete-upgrade-controllers-task.html
sidebar: sidebar
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, vendor ID, upgrade status, upgrade validate
summary: Complete the controller upgrade by powering on the controller shelf and validating the controller software version. Then, you can collect support data and resume operations.
---
= Complete controller upgrade
:icons: font
:imagesdir: ../media/

[.lead]
Follow this procedure to complete the controller upgrade by powering on the controller shelf and validating the controller software version. Then, you can collect support data and resume operations.

If you are upgrading controllers in a duplex controller-drive tray, repeat all steps to complete the upgrade for the second controller.

== Step 1: Power on controller

You must power on the controller shelf to confirm that it is working correctly.

===== Steps

. Turn on the power switch on the rear of each drive tray that is connected to the controller-drive tray.
. Wait two minutes for the drives to spin up.
. Turn on the power switch on the rear of the controller-drive tray.
. Wait three minutes for the power-up process to complete.
. If you are performing a complete controller replacement for either E2800 or E5700 controllers, proceed to one of the following procedures based on your drive security scenario.
+
[options="header"]
|===
| Complete controller replacement type| Procedure and prerequisites
a|
All unsecured drives, neither External or Internal Key Management
a|
Proceed to the next step.
a|
Mix of secured and unsecured drives, Internal Key Management
a|
You first must create an internal security key and then import the security key manually to unlock the secured drives. After the drives are unlocked, you can access the drives.

 .. Create internal security key
 .. Controller swap with internal key management and one or more drives secured

a|
All secured drives, Internal Key Management
a|
Controller swap with internal key management and one or more drives secured
a|
Mix of secured and unsecured drives, External Key Management
a|
Proceed to the next step.

*Attention:* After performing the controller replacement, the controllers will automatically resynchronize with the External Key Management Server and the drives will unlock and be accessible.

NOTE: If you receive a seven-segment display lock-down code of `L5` after performing a controller replacement of mixed secured drives with internal key management, contact technical support.
a|
All secured drives, External Key Management, you have temporarily switched back to Internal Key Management for the controller replacement procedure
a|
You must first unlock the secured drives using the Internal Key Management procedure. After the drives are unlocked, then you transition back to External Key Management by creating a new external security key for the storage array.

 .. Controller swap with internal key management and one or more drives secured
 .. Create external security key

a|
All secured drives, External Key Management, you have not temporarily switched to Internal Key Management for the controller replacement procedure
a|
Controller swap with external key management and all drives secured
|===

== Step 2: Check status of controllers and trays

You can use the LEDs and the storage management software to check the status of your controllers and trays.

===== Steps

. Look at the LEDs on controller A to make sure that it is booting correctly.
+
The Host Link Service Action Required LEDs turn green during the reboot. The seven-segment display shows the sequence OS+ Sd+ blank- to indicate that the controller is performing Start-of-day (SOD) processing.
+
After the controller successfully completes rebooting, the seven-segment display shows the tray ID matching the seven-segment display on the second controller. You can then discover the new controller canister by using the storage management software.

. If any of the controller-drive tray's Service Action Required LEDs are _on_, or if the Controller Service Action Required LED is _on_:
 .. Check that the controller canister has been installed correctly and that all of the cables are correctly seated. Reinstall the controller canister, if necessary.
 .. Check the controller-drive tray's Service Action Required LEDs and the Controller Service Action Required LED again. If the problem is not corrected, contact technical support.
. For a duplex configuration, repeat step 1 through step 2 for controller B.
. Using the LEDs and the storage management software, check the status of all of the trays in the storage array. If any component has a Needs Attention status, use the Recovery Guru to troubleshoot. If the problem is not resolved, contact technical support.

== Step 3: Validate controller software version

You must ensure that your new controllers are running with the correct operating system (controller firmware) level and NVSRAM.

===== Steps

. Do one of the following:
 ** If you are upgrading to controllers that do not support SANtricity 11.30 and controller firmware 8.30, make sure that the version running on the new controllers matches the version that was last running on the original controllers. Normally, this will be the most recent release supported by the old controllers. If necessary, install the appropriate version on the new controllers.
 ** If you are upgrading to controllers that run SANtricity 11.30 and controller firmware 8.30, download and install the latest NVSRAM after you power on the new controllers.
. If your controller upgrade involves a protocol change (for example, Fibre Channel to iSCSI), and you already have hosts defined for your storage array, associate the new host ports with your hosts:
 .. From System Manager, select *Storage* > *Host*.
 .. Select the host to which the ports will be associated, and then click *View/Edit Settings*.
+
A dialog box appears that shows the current host settings.

 .. Click the *Host Ports* tab.
+
The dialog box shows the current host port identifiers.

 .. To update the host port identifier information associated with each host, replace the host port IDs from the old host adapters with the new host port IDs for the new host adapter.
 .. Repeat step d for each host.
 .. Click *Save*.

+
For information about compatible hardware, refer to the https://mysupport.netapp.com/NOW/products/interoperability[NetApp Interoperability Matrix] and the http://hwu.netapp.com/home.aspx[NetApp Hardware Universe].
. Enable Write Back Caching for all thin volumes if it had been disabled in preparing for the headswap.
. Enable SAML for the controller replacements if disabled in preparing for the headswap.
 .. From System Manager, select the *SAML* tab, and then select the *Enable SAML* link.
+
The *Confirm Enable SAML* dialog opens.

 .. Type `enable`, and then click *Enable*.
 .. Enter user credentials for an SSO login test.
. Gather support data about your storage array by using either the GUI or the CLI:
 ** Use either System Manager or the Array Management Window to collect and save a support bundle of your storage array.
  *** From System Manager, first select *Support* > *Support Center* > *Diagnostics* tab. Then select **Collect Support Data* and click *Collect*.
  *** From the Array Management Window toolbar, select *Monitor* > *Health* > *Collect Support Data Manually*. Then name and specify a location on your system where you want to store the support bundle.
The file is saved in the Downloads folder for your browser with the name `support-data.7z`.

+
If your shelf contains drawers, the diagnostics data for that shelf is archived in a separate zipped file named `tray-componet-state-capture.7z`
 ** Use the CLI to run the `save storageArray supportDatacommand` to gather comprehensive support data about the storage array.
+
NOTE: Gathering support data can temporarily impact performance on your storage array.

. Alert NetApp Technical Support to the changes that you made to the configuration of your storage array.
 .. Get the serial number of the controller-drive tray that you recorded in xref:prepare-upgrade-controllers-task.adoc[Prepare to upgrade controllers].
 .. Log in to the NetApp support site at http://mysupport.netapp.com/eservice/assistant[mysupport.netapp.com/eservice/assistant].
 .. Select *Product Registration* from the drop-down list under *Category 1*.
 .. Enter the following text in the **Comments** text box, substituting the serial number of your controller-drive tray for serial number:
+
`Please create alert against Serial Number: serial number. The alert name should be “E-Series Upgrade”. The alert text should read as follows:`
+
`“Attention: The controllers in this system have been upgraded from the original configuration. Verify the controller configuration before ordering replacement controllers and notify dispatch that the system has been upgraded.”`

 .. Click the *Submit* button at the bottom of the form.

== Result

If your controller upgrade results in changing the vendor ID from LSI to NETAPP, go to link:remount-volumes-lsi-task.html[Remount volumes after changing the vendor from LSI to NETAPP]; otherwise your controller upgrade is complete and you can resume normal operations.
