---
permalink: upgrade-controllers/index.html
sidebar: sidebar
keywords: E-Series, eseries, E4000, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, upgrade controller, upgrade DIMMs
summary: Overview of upgrading an E-Series array by replacing controllers.
---
= Upgrade controllers overview
:icons: font
:imagesdir: ../media/

[.lead]
You can upgrade your storage array through the replacement of existing controllers.

== Controller components

A controller consists of a board, firmware, and software. It controls the drives, and also implements the management software functions.

== When to use this procedure

You typically use this procedure when you want to upgrade all controllers to a different model or platform. This procedure involves replacing all controllers in a controller-drive tray.

You might also use this procedure in the following situations:

* When all controllers in a controller-drive tray encounter hardware failures and are no longer functional.
* To upgrade the dual inline memory modules (DIMMs) in your controller-drive tray by replacing both controllers with the same model of controllers, but with different DIMMs.

NOTE: The HIC upgrade scenarios are not covered within this procedure. Instead, refer to the HIC add, upgrade and replacement procedures for your E-Series system.
