---
permalink: upgrade-controllers/overview_requirements_concept.html
sidebar: sidebar
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, upgrade controller requirements, upgrade compatibility, upgrade SAS shelf, upgrade SAS shelves, upgrade SAS enclosures, SAS-2 to SAS-3
summary: Review requirements for upgrading and replacing E-Series controllers.
---
= Upgrade considerations
:icons: font
:imagesdir: ../media/

[.lead]
Before you upgrade controllers, review the following considerations.

== Hardware and firmware requirements

* *Duplex and simplex controller upgrades*
+
For duplex controller-drive trays, you replace both controllers. For simplex controller-drive trays, you replace the one controller. In both cases, you must power off the controller-drive tray. As a result, you cannot access data on the storage array until you successfully complete the replacement.

* *Trays and shelves*
+
Storage arrays with an E2800 or E5700 controller shelf typically use SANtricity System Manager. You might also use the Enterprise Management Window (EMW) from SANtricity Storage Manager to manage E2800 or E5700 controller shelves. All other controller-drive trays referenced in this procedure use SANtricity Storage Manager.

* *Controller batteries*
+
A new controller is shipped without a battery installed. When possible, you should remove the battery from your old controller and then install that battery in the new controller. However, for some controller upgrades, the battery from the old controller is not compatible with the new controller. In those cases, you must order a battery along with your new controller, and have that battery available before you begin these tasks.

* *Vendor Identification*
+
Some controller upgrades result in the Vendor ID in SCSI Inquiry Data changing from `LSI` to `NETAPP`. When the Vendor ID changes from `LSI` to `NETAPP`, additional steps are required on the Windows, VMware, and AIX operating systems to reclaim devices. Steps for these operating systems are included in this upgrade procedure.

* *Synchronous Mirroring and Asynchronous Mirroring*
+
If your storage array participates in Synchronous Mirroring, only iSCSI or Fibre Channel connections are supported between the primary site and the remote site. If the host interface card (HIC) configuration in your new controllers does not include iSCSI or Fibre Channel connections, Synchronous Mirroring will not be supported.
+
For Asynchronous Mirroring, the local storage array and remote storage array can run different versions of firmware. The minimum firmware version supported is SANtricity firmware version 7.84.

* *Storage object limits*
+
If you change your controllers from 5x00 models to 2x00 models, your new storage array configuration will support lower numbers of some storage objects (for example, volumes) in the storage management software than your old configuration. You must make sure that your old configuration does not exceed the storage object limits. See http://hwu.netapp.com/home.aspx[Netapp Hardware Universe] for more information.

== Upgrade to newer models

If you are replacing the controllers to upgrade to a new model, keep in mind that your current storage array might have premium features installed that the new model cannot support. For example, E2700 controllers do not support the legacy Snapshots premium feature.

If you replace E2600 controllers with E2700 controllers, and your storage array was using the legacy Snapshots feature, you must disable that feature and delete or convert all volumes (that is, snapshots, repositories) associated with that feature before you replace the controllers. You can convert legacy Snapshots to the updated Snapshots feature. Before you upgrade a controller-drive tray, you should disable any premium features used on your storage array that are not supported on the new controllers.

== Upgrade compatibility

[.lead]
Review the supported upgrade paths for each storage array model.

=== From E2x00 to E2x00

* *Battery*: Reuse the old battery.
* *Vendor ID*: Additional steps required.
* *Feature support*: Legacy snapshots are not supported on the E2700.
* *SAS-2 shelves*: E2800 controllers must not be placed into SAS-2 shelves.

=== From E2x00 to E5x00

* *Battery*: Order a new battery.
* *Vendor ID*: Additional steps are required when upgrading from E2600 to E5500 or E5600, or when upgrading from E2700 to E5400.
* *Feature support*: Legacy snapshots are not supported on the E5500 or E5600.
+
Legacy remote volume mirroring (RVM) is not supported on the E5500 or E5600 with iSCSI HICs.
+
Data Assurance is not supported on the E5500 or E5600 with iSCSI HICs.
+
E5700 controllers must not be placed into SAS-2 shelves.

* *SAS-3 shelves*: E5400, E5500, and E5600 controllers must not be placed into SAS-3 shelves.

=== From E5x00 to E2x00

* *Battery*: Order a new battery.
* *Vendor ID*: Additional steps are required when upgrading from E5500 or E5600 to E2600, or when upgrading from E5400 to E2700.
* *Feature support*: Legacy snapshots are not supported on the E2700.
* *SAS-3 shelves*: E5400, E5500, and E5600 controllers must not be placed into SAS-3 shelves.

=== From E5x00 to o E5x00

* *Battery*: Reuse the old battery.
* *Vendor ID*: Additional steps required when upgrading from E5400 to E5500 or E5600.
* *Feature support*: Legacy snapshots are not supported on the E5500 or E5600.
+
Legacy remote volume mirroring (RVM) is not supported on the E5400 or E5500 with iSCSI HICs.
+
Data Assurance is not supported on the E5400 or E5500 with iSCSI HICs.
+
E5700 controllers must not be placed into SAS-2 shelves.

* *SAS-3 shelves*: E5400, E5500, and E5600 controllers must not be placed into SAS-3 shelves.

=== From EF5x0 to EF5x0

* *Battery*: Reuse the old battery.
* *Vendor ID*: Additional steps required when upgrading from EF540 to EF550 or EF560.
* *Feature support*: No Legacy Snapshots for EF550/EF560.
+
No Data Assurance for EF550/EF560 with iSCSI.
+
EF570 controllers must not be placed into SAS-3 shelves.

* *SAS-3 shelves*: EF540, EF550, and EF560 controllers must not be placed into SAS-3 shelves.

=== SAS enclosures

The E5700 supports DE5600 and DE6600 SAS-2 enclosures via head upgrade. When a E5700 controller is installed in SAS-2 enclosures, support for base host ports is disabled.

[options="header"]
|===
| SAS-2 shelves| SAS-3 shelves
a|
SAS-2 shelves include the following models:

* DE1600, DE5600, and DE6600 drive trays
* E5400, E5500, and E5600 controller-drive trays
* EF540, EF550 and EF560 flash arrays
* E2600 and E2700 controller-drive trays

a|
SAS-3 shelves include the following models:

* E2800 controller shelves
* E5700 controller shelves
* DE212C, DE224C, DE460C drive shelves

|===

=== SAS-2 to SAS-3 investment protection

You can reconfigure your SAS-2 system to be used behind a new SAS-3 controller shelf (E57XX/EF570/E28XX).

IMPORTANT: This procedure requires an FPVR. To file an FPVR, contact your sales team.
