---
permalink: upgrade-controllers/prepare-upgrade-controllers-task.html
sidebar: sidebar
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, upgrade controller requirements, upgrade controller key management, prepare upgrade controller, upgrade controller preparation, preparing controller upgrade
summary: Prepare to upgrade controllers by saving the drive security key, gathering support data, and taking the controller offline.
---
= Prepare to upgrade controllers
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
Prepare to upgrade controllers by saving the Drive Security key (if used), recording the serial number, gathering support data, disabling certain features (if used), and taking the controller offline.

NOTE: Gathering support data can temporarily impact performance on your storage array.

.Steps

. Make sure that the existing storage array is updated to the latest released operating system (controller firmware) version available for your current controllers. From SANtricity System Manager, go to menu:Support[Upgrade Center] to view your software and firmware inventory.
+
NOTE: If you are upgrading to controllers that support SANtricity OS version 8.50, you must install the latest versions of SANtricity OS and the latest NVSRAM after you install and power on the new controllers. If you do not perform this upgrade, you might not be able to configure the storage array for Automatic Load Balancing (ALB).

. If you are performing a complete controller replacement and are also using the Drive Security feature, complete the appropriate steps for your security type (internal or external) and drive state in the following table.
+
NOTE: Drive Security is a storage array feature that provides an extra layer of security with either Full Disk Encryption (FDE) drives or Federal Information Processing Standard (FIPS) drives. When these drives are used with the Drive Security feature, they require a security key for access to their data.
+
[options="header"]
|===
| Security type and context| Steps
a|
Internal key management, one or more drives locked
a|

 .. Export the internal security key file to a known location on the management client (the system with a browser used for accessing System Manager). Use the `export storageArray securityKey` CLI command. You must provide the pass phrase associated with the security key and specify the location where you want to save the command. For information about using this command, see the _Command Line Reference_.
 .. Know the pass phrase associated with the internal security key.

a|
External key management, all drives locked, you are able to transition to internal key management temporarily for the controller replacement (recommended).
a|
Perform the following steps, in order:

 .. Record the External KMS server address and port number. From System Manager, go to menu:Settings[System > Security Key Management > View/Edit Key Management Server Settings].
 .. Ensure that the client and server certificates are available on your local host so the storage array and key management server can authenticate each other after the controller replacement is finished. Use the `save storageArray keyManagementCertificate` CLI command to save the certificates. Be sure to run the command twice, once with the `certificateType` parameter set to `client`, and the other with the parameter set to `server`. For information about using this command, see the _Command Line Reference_.
 .. Transition to internal key management by running the `disable storageArray externalKeyManagement` CLI command.
 .. Export the internal security key file to a known location on the management client (the system with a browser used for accessing System Manager). Use the `export storageArray securityKey` CLI command. You must provide the pass phrase associated with the security key and specify the location where you want to save the command. For information about using this command, see the _Command Line Reference_.
 .. Know the pass phrase associated with the internal security key.

a|
External key management, all drives locked, you are not able to transition to internal key management temporarily for the controller replacement.
a|
Perform the following steps, in order:

 .. Record the External KMS server address and port number. From System Manager, go to menu:Settings[System > Security Key Management > View/Edit Key Management Server Settings].
 .. Ensure that the client and server certificates are available on your local host so the storage array and key management server can authenticate each other after the controller replacement is finished. Use the `save storageArray keyManagementCertificate` CLI command to save the certificates. Be sure to run the command twice, once with the `certificateType` parameter set to `client`, and the other with the parameter set to `server`. For information about using this command, see the _Command Line Reference_.

a|
External key management, partial drives locked
a|
No additional steps are necessary.
|===

. Record the serial number for your storage array:
  .. From System Manager, select menu:Support[Support Center > Support Resources tab].
 .. Scroll down to *Launch detailed storage array information*, and then select *Storage Array Profile*.
+
The Report appears on your screen.

 .. To locate the chassis serial number under the storage array profile, type *serial number* in the *Find* text box, and then click *Find*.
+
All matching terms are highlighted. To scroll through all the results one at a time, continue to click *Find*.

 .. Make a record of the `Chassis Serial Number`.
+
You need this serial number to perform the steps in link:complete-upgrade-controllers-task.html[Complete controller upgrade].
. Gather support data about your storage array by using either the GUI or the CLI:
 ** Use either System Manager or the Array Management Window in Storage Manager to collect and save a support bundle of your storage array.
  *** From System Manager, select menu:Support[Support Center > Diagnostics tab]. Then select *Collect Support Data* and click *Collect*.
  *** From the Array Management Window toolbar, select menu:Monitor[Health > Collect Support Data Manually]. Then enter a name and specify a location on your system where you want to store the support bundle.
+
The file is saved in the Downloads folder for your browser with the name `support-data.7z`.
+
If your shelf contains drawers, the diagnostics data for that shelf is archived in a separate zipped file named `tray-component-state-capture.7z`.
 ** Use the CLI to run the `save storageArray supportData` command to gather comprehensive support data about the storage array.

. Ensure that no I/O operations are occurring between the storage array and all connected hosts:
 .. Stop all processes that involve the LUNs mapped from the storage to the hosts.
 .. Ensure that no applications are writing data to any LUNs mapped from the storage to the hosts.
 .. Unmount all file systems associated with volumes on the array.
+
NOTE: The exact steps to stop host I/O operations depend on the host operating system and the configuration, which are beyond the scope of these instructions. If you are not sure how to stop host I/O operations in your environment, consider shutting down the host.
+
CAUTION: *Possible data loss* -- If you continue this procedure while I/O operations are occurring, you might lose data.
. If the storage array participates in a mirroring relationship, stop all host I/O operations on the secondary storage array.
. If you are using asynchronous or synchronous mirroring, delete any mirrored pairs and deactivate any mirroring relationships through the System Manager or the Array Management window.
. If there is a thin provisioned volume that is reported to the host as a thin volume and the old array is running firmware (8.25 firmware or above) that supports the UNMAP feature, disable Write Back Caching for all thin volumes:
 .. From System Manager, select menu:Storage[Volumes].
 .. Select any volume, and then select menu:More[Change cache settings].
+
The Change Cache Setting dialog box appears. All volumes on the storage array appear in this dialog box.

 .. Select the *Basic* tab and change the settings for read caching and write caching.
 .. Click *Save*.
 .. Wait five minutes to allow any data in cache memory to be flushed to disk.
. If the Security Assertion Markup Language (SAML) is enabled on the controller, contact technical support to disable the SAML authentication.
+
NOTE: After SAML is enabled, you cannot disable it through the SANtricity System Manager interface. To disable the SAML configuration, contact technical support for assistance.

. Wait for all operations in progress to complete before continuing to the next step.
 .. From System Manager's *Home* page, select *View Operations in Progress*.
 .. Make sure all operations shown on the *Operations in Progress* window are complete before continuing.
. Turn off power to the controller-drive tray.
+
Wait for all of the LEDs on the controller-drive tray to go dark.

. Turn off power to each drive tray that is connected to the controller-drive tray.
+
Wait two minutes for all of the drives to spin down.

.What's next?

Go to link:remove-controllers-task.html[Remove controllers].
