---
permalink: upgrade-controllers/reconfigure_sas_task.html
sidebar: sidebar
keywords: 
summary: ''
---
= Reconfigure a SAS-2 system behind a new SAS-3 controller shelf without data preservation
:icons: font
:imagesdir: ../media/

[.lead]
You can convert the controller shelf in an approved SAS-2 array (E2700, E550/EF5500, E5600/EF560) to a drive shelf and then place that shelf and any associated approved SAS-2 drive shelves (DE1600, DE5600, DE6600) behind a new approved SAS-3 array (E2800, E5700/EF570) and approved SAS-3 drive shelves (DE212C, DE224C, DE460C) without data preservation.

Due to the complexity of this procedure, the following is required:

* This procedure requires an FPVR. To file an FPVR contact NetApp Professional Services.
+
NOTE: Failure to aquire an FPVR before attempting this procedure can result in drive failure and controller lock down.

* If you are able to back up your data, you can perform this procedure without assistance from NetApp Professional Services.
* If you cannot back up your data, contact NetApp Professional Services for assistance with this procedure.
* Make sure both of your arrays are prepared for the procedure:
 ** *Existing array*: Existing array with SANtricity OS 8.25 or later that is powered up.
 ** *New array*: New array unpacked and powered down.
* Record the serial number from the SAS-2 controller shelf that you will be converting to a drive shelf.

== Step 1: Power down the controllers (non-data preservation)

[.lead]
All operations must be shut down before you can power down the controllers.

. If the existing SAS-2 array is still accessible, delete all volume groups, power down both controllers, and remove all cables.
. Record the serial number from the SAS-2 controller shelf that you will be converting to a drive shelf.
. If drive security is in use for the existing array, ensure that the security key is available.

== Step 2: Install the controllers (non-data preservation)

[.lead]
Upon successful shut down, you can replace the controllers in the array.

. Replace both controllers in the existing array with IOMs or ESMs.
. If possible, use the host cables and network cables from the existing array and connect them to the controllers in the new array.
+
NOTE: Depending on the host connections of your new array, different cables may be required.

. Cable the drive shelves behind the controllers in the new array.
+
The existing controller-drive tray and any attached drive trays become drive shelves and can be cabled to the controllers in the new array.
+
NOTE: Connecting SAS-2 to SAS-3 requires SAS HD to miniSAS cables. For more detailed cabling information for your particular controller and expansion shelf configuration, refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP2588749[E-Series Hardware Cabling Guide].

== Step 3: Power on the controllers (non-data preservation)

[.lead]
After installation is complete, power on the controllers and submit your configuration changes to NetApp Technical Support.

. Power up the new array including any attached drive shelves.
. Configure the management port and the IP addresses by installing the https://mysupport.netapp.com/tools/info/ECMLP2563821I.html[SANtricity Quick Connect] utility.
. If drive security was in use on the existing array, import the security key.
. If you were unable to delete the volume groups from your existing array before performing this procedure, you must set all foreign drives to appear as native. For detailed information on how to set drives to native, refer to the SANtricity Online Help.
. Send your configuration changes to NetApp Technical Support.
 .. Get the serial number of the old controller-drive tray that you recorded in Step 2.
 .. Log in to the NetApp Support Site: `+[mysupport.netapp.com/eservice/assistant](http://mysupport.netapp.com/eservice/assistant)+`.
 .. From the drop-down list under *Category 1* on the *Give Us Feedback* page, select *Installed products*.
 .. From the drop-down list under *Category 2* on the *Give Us Feedback* page, select *Decommission request*.
 .. Enter the following text in the **Comments**text box, substituting the serial number of your controller-drive tray for serial number:
+
`Please decommission this serial number as the entitlement has been moved to another serial number in the system. Please reference this in the SN notes.`

 .. Select *Submit*.

The completed SAS-2 to SAS-3 configuration changes are submitted to NetApp Technical Support.
