---
permalink: remote-storage-volumes/index.html
sidebar: sidebar
keywords: Remote Storage Volumes, RTV, remote volumes, remote storage E-Series
summary: Use the Remote Storage Volumes feature to import data from a remote storage device directly to a local E-Series volume.
---
= Remote Storage Volumes overview
:icons: font
:imagesdir: ../media/

[.lead]
Use the SANtricity® Remote Storage Volumes feature to import data from a remote storage device directly to a local E-Series volume. This feature helps streamline the process for equipment upgrades and provides data migration capabilities to move data from non-E-Series devices to E-Series systems.

== Configuration Overview

The Remote Storage Volumes feature comes with SANtricity System Manager on selected submodel IDs that allows data to be moved between a remote storage system and an E-Series storage system. The systems need to be prepared for communication between each other. Each of the E-Series controllers needs to have at least one or more connections to the remote storage system.

When the local E-Series storage system and the remote storage system are configured to communicate via the supported I/O protocol, the remote storage device must be mapped to the local E-Series storage system. The SANtricity System Manager or SANtricity REST APIs can then be used to initiate and manage the import operation.

During the import operation, the target volume can be set up to handle I/Os that were previously being sent to the remote storage device. Any I/Os going to the target volume will then be propagated back to the remote storage device until the import operation has completed and the import has been disconnected.

== Find more information

* Online help, avaiable in the System Manager user interface.
* For additional technical information on the Remote Storage Volumes feature, see the https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf[Remote Storage Volumes Technical Report].
