---
permalink: remote-storage-volumes/index.html
sidebar: sidebar
keywords: Remote Storage Volumes, RTV, remote volumes, remote storage E-Series
summary: Use the Remote Storage Volumes feature to import data from a remote storage device directly to a local E-Series volume.
---
= Learn about SANtricity Remote Storage Volumes
:icons: font
:imagesdir: ../media/

[.lead]
Use the SANtricity® Remote Storage Volumes feature to import data from a remote storage device directly to a local E-Series volume.
This feature helps streamline the process for equipment upgrades and provides data migration capabilities to move data from non-E-Series devices to E-Series systems.

== Configuration overview

The Remote Storage Volumes feature is available with SANtricity System Manager on selected submodel IDs. To use this feature, you must configure a remote storage system and an E-Series storage system to communicate with each other.

Use the following workflow:

. link:system-reqs-concept.html[Review requirements and restrictions].
. link:setup-remote-volumes-concept.html[Configure hardware].
. link:import-remote-storage-task.html[Import remote storage].

NOTE: SANtricity Remote Storage Volumes is currently not supported on E4000 systems.

== Find more information

* Online help, available in the System Manager user interface or in the https://docs.netapp.com/us-en/e-series-santricity/index.html[SANtricity software doc site^].
* For additional technical information on the Remote Storage Volumes feature, see the https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf[Remote Storage Volumes Technical Report^].
