---
permalink: remote-storage-volumes/modify_remote_storage_task.html
sidebar: sidebar
keywords: 
summary: 'You can modify the connection settings for any configured Remote Storage import through the View/Edit Settings option under the Remote Storage screen of the SANtricity System Manager.'
---
= Modify remote storage connection settings
:icons: font
:imagesdir: ../media/

[.lead]
You can modify the connection settings for any configured Remote Storage import through the View/Edit Settings option under the Remote Storage screen of the SANtricity System Manager.

Changes made to connection properties will affect any in-progress imports. To avoid disruptions, only make changes to connection properties when no in-progress imports exist.

. From the Remote Storage screen of the SANtricity System Manager, select the desired Remote Storage object under the result list section.
. Click *View/Edit Settings*.
+
The Remote Storage Settings screen is displayed.

. Click the *Connection Properties* tab.
+
The configured IP address and port settings for the remote storage import are displayed.

. To add a new connection for the remote storage object, click *Add*.
+
The Add iSCSI Connection window is displayed.

. Enter the new IP address and port information in the fields provided.
. Click *Add*.
+
The new connection is added to the remote storage object IP connections table.

. To modify an existing IP address and port settings for the configured remote storage object, click *Edit* next to the corresponding line item.
. Enter the revised IP address and/or port information under the provided fields.
. To remove an existing connection for the remote storage object, select the desired connection under the result list section of the Connection tab and click *Delete*.
+
The Confirm Delete iSCSI Connection window is displayed.

. Enter *Delete* under the provided field and click *Delete*.
+
The connection is removed from the remote storage object IP connections table.

. Click *Save*.
+
The modified connection settings are applied to the remote storage object.
