---
permalink: remote-storage-volumes/system-reqs-concept.html
sidebar: sidebar
keywords: Remote Storage Volumes requirements, RTV requirements, RTV restrictions, remote volumes, remote storage E-Series
summary: Your system must meet compatibility requirements for Remote Storage Volumes.
---
= Requirements and restrictions for remote storage
:icons: font
:imagesdir: ../media/

[.lead]
Before configuring the Remote Storage Volumes feature, review the following requirements and restrictions.

== Hardware requirements

=== Supported protocols

For the initial release of the Remote Storage Volumes feature, support is only available for iSCSI and IPv4 protocols.

Refer to the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^] for up-to-date support and configuration information between the host and E-Series (destination) array used for the Remote Storage Volumes feature.

=== Storage system requirements

The E-Series storage system must include:

* Two controllers (duplex mode)
* iSCSI connections for both E-Series controllers to communicate with the remote storage system through one or more iSCSI connections
* SANtricity OS 11.71 or greater
* Remote Storage feature enabled in the Submodel ID (SMID)

The remote system can be either an E-Series storage system or a system from another vendor. It must include iSCSI-capable interfaces.

== Volume requirements

Volumes used for imports must meet the requirements for size, status, and other criteria.

=== Remote storage volume

The source volume of an import is called a "remote storage volume." This volume must meet the following criteria:

* Cannot be part of another import
* Must have an online status

After the import begins, the controller firmware creates a remote storage volume in the background. Due to that background process, the remote storage volume is not manageable in System Manager and can only be used for the import operation.

After it is created, the remote storage volume is treated like any other standard volume on the E-Series system with the following exceptions:

* Can be used as proxies to the remote storage device.
* Cannot be used as candidates for other volume copies or snapshots.
* Cannot have the Data Assurance setting changed while the import is in progress.
* Cannot be mapped to any hosts, because they are reserved strictly for the import operation.

Each remote storage volume is associated with only one remote storage object; however, one remote storage object can be associated with multiple remote storage volumes. The remote storage volume is uniquely identified using a combination of the following:

* Remote storage object identifier
* Remote storage device LUN number

=== Target volume candidates

The target volume is the destination volume on the local E-Series system.

The destination volume must meet the following criteria:

* Must be a RAID/DDP volume.
* Must have a capacity that is equal to or larger than the remote storage volume.
* Must have a block size that is the same as the remote storage volume.
* Must have a valid state (optimal).
* Cannot have any of the following relationships: volume copy, snapshot copies, asynchronous or synchronous mirroring.
* Cannot be undergoing any reconfiguration operations: Dynamic Volume Expansion, Dynamic Capacity Expansion, Dynamic Segment Size, Dynamic RAID Migration, Dynamic Capacity Reduction, or Defragmentation.
* Cannot be mapped to a host before the import starts (however, it can be mapped after import completes).
* Cannot have Flash Read Cached (FRC) enabled.

System Manager automatically checks these requirements as part of the Import Remote Storage wizard. Only volumes that meet all the requirements are displayed for destination volume selection.

== Restrictions

The Remote Storage feature has the following restrictions:

* Mirroring must be disabled.
* Destination volume on the E-Series system must not have snapshots.
* Destination volume on the E-Series system must not be mapped to any hosts before the import is started.
* Destination volume on the E-Series system must have resource-provisioning disabled.
* Direct mappings of the remote storage volume to a host or multiple hosts is not supported.
* Web Services Proxy is not supported.
* iSCSI CHAP secrets are not supported.
* SMcli is not supported.
* VMware Datastore is not supported.
* Only one storage system in the relationship/import pair can be upgraded at a time when there is an import pair present.

== Preparation for production imports

You should perform a test or "dry run" import before production imports to verify proper storage and fabric configuration.

Many variables can impact the import operation and completion time. To ensure a production import is successful and to get a duration  estimate, you can use these test imports to ensure all connections are working as expected and the import operation is completing in an appropriate amount of time. You can then make adjustments to achieve the desired results before the production import is initiated.
