---
permalink: remote-storage-volumes/system-reqs-concept.html
sidebar: sidebar
keywords: Remote Storage Volumes requirements, RTV requirements, RTV restrictions, remote volumes, remote storage E-Series
summary: Your system must meet compatibility requirements for Remote Storage Volumes.
---
= Requirements and restrictions for remote storage
:icons: font
:imagesdir: ../media/

[.lead]
Before using Remote Storage Volumes, review the following requirements and restrictions.

== Supported protocols

[.lead]
For the initial release of the Remote Storage Volumes feature, support is only available for iSCSI and IPv4 protocols.

Refer to the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool] for up-to-date support and configuration information between the host and E-Series (destination) array used for the Remote Storage Volumes feature.

== Supported E-Series systems

[.lead]
Your E-Series system must meet compatibility requirements for Remote Storage Volumes.

E-Series storage systems must meet the following requirements for the initial release of the Remote Storage Volumes feature:

* The E-Series storage system must support iSCSI connections.
* The system must be running in duplex mode (both controllers present).
* Both E-Series controllers must be able to communicate with the remote storage through one or more iSCSI connections.

== Hardware requirements

[.lead]
The appropriate connections and hardware must be set up before SANtricity System Manager, or the REST API can be used to initiate a remote storage volume import operation.

The minimum hardware required includes the following:

* E-Series storage system (both controllers must be present)
 ** SANtricity OS (11.71 or greater)
 ** iSCSI interfaces
*Note:* The Remote Target Volumes feature is only available on iSCSI supported submodel IDs.
* Remote storage system / device
 ** iSCSI capable interfaces
* Both E-Series controllers must be able to communicate with the remote storage through one or more iSCSI connections

== Restrictions

The Remote Storage feature has the following restrictions:

* Mirroring must be disabled.
* Destination volume on the E-Series system must not have snapshots.
* Destination volume on the E-Series system must not be mapped to any hosts before the import is started.
* Destination volume on the E-Series system must have resource-provisioning disabled.
* Direct mappings of the remote storage volume to a host or multiple hosts is not supported.
* Web Services Proxy is not supported.
* iSCSI CHAP secrets are not supported.
* SMcli is not supported.
* VMware Datastore is not supported.
* Only one storage system in the relationship/import pair can be upgraded at a time when there is an import pair present.

== Preparation for production imports

You should perform a test or "dry run" import before production imports to verify proper storage and fabric configuration.

Many variables can impact the import operation and completion time. To ensure a production import is successful and to get a duration  estimate, you should first perform multiple smaller "`test`" imports. Use these test imports to ensure all connections are working as expected and the import operation is completing in an appropriate amount of time. You can then make adjustments to achieve the desired results before the production import is initiated.
