---
permalink: remote-storage-volumes/view_import_progress_task.html
sidebar: sidebar
keywords: status, remote, storage, import, result, list, section, screen, santricity, system, manager
summary: You can view the status of each remote storage import from the result list section of the Remote Storage screen of the SANtricity System Manager.
---
= View import progress
:icons: font
:imagesdir: ../media/

[.lead]
You can view the status of each remote storage import from the result list section of the Remote Storage screen of the SANtricity System Manager.

The status of each remote storage import is viewable from the result list section of the Remote Storage screen of SANtricity System Manager. Various actions can be performed on each import based on its status.

. From the Remote Storage screen of the SANtricity System Manager, click on *View Operations*.
+
The Operations in Progress screen is displayed.

== Change import priority

[.lead]
For remote storage imports with a status of Pending or In progress, you can change the import priority directly from the SANtricity System Manager.

Import priority can be changed directly from the Operations in Progress window on imports that have either an in-progress or pending status using the following steps.

. Under the result list section of the Operations in Progress screen, click *Change Priority* under the Actions column for the corresponding remote storage import with a status of Pending or In progress.
+
The Change Import Priority dialog is displayed.

. Under the Import Priority field, select one of the following priority options:
 ** Lowest
 ** Low
 ** Medium (Default)
 ** High
 ** Highest
. Click *OK*.
+
The selected priority is applied to the remote storage import.

== Stop remote storage import

[.lead]
For remote storage imports with a status of Pending or In progress, you can stop an import directly from the SANtricity System Manager.

An import can be stopped directly from the Operations In Progress window on imports that have either an in-progress or pending status using the following steps.

NOTE: This operation halts the copying of data from the remote storage device but the relationship between the import pair is still intact.

. Under the result list section of the Operations in Progress screen, click *Stop* in the Actions menu.
+
The Stop Remote Storage Import dialog is displayed.

. Under the Type stop field, enter *Stop* in the provided field.
. Click *Stop*.
+
The Remote Storage Import process is stopped.

== Resume import

[.lead]
For remote storage imports with a status of failed or stopped, you can resume the remote storage import from the SANtricity System Manager.

An import can be resumed directly from the Operation In Progress window on imports that have either a Failed or Stopped status using the following steps.

NOTE: The resume operation only resumes an existing import and does not restart the import from the beginning of the process. If the import needs to be restarted from the beginning, it must be disconnected and then re-created through the Import Remote Storage wizard.

. Under the result list section of the Operations in Progress screen, click *Resume* in the Actions column for the corresponding remote storage import with a status of Failed or Stopped.
+
The Resume Remote Storage Import dialog is displayed.

. Under the Import Priority field, select one of the following import priority options:
 ** Lowest
 ** Low
 ** Medium (Default)
 ** High
 ** Highest
. Click *OK*.
+
The selected priority is applied to the remote storage import.

== Disconnect remote storage operation

[.lead]
For remote storage imports with a status of completed, stopped, or failed, you can disconnect the volume on the destination E-Series system from the remote storage device through the SANtricity System Manager.

. Under the result list section of the Operations in Progress screen, click *Disconnect* in the Actions column for the corresponding remote storage import with a status of completed, failed, or stopped.
+
The Disconnect Remote Storage Import Operation dialog is displayed.

. Enter *Disconnect* in the provided field.
. Click *Disconnect*.
+
Communication for the selected remote storage import is disconnected.
