---
permalink: upgrade-santricity/task_upgrade_software_and_firmware_for_a_single_controller.html
sidebar: sidebar
keywords: 
summary: ''
---
= Upgrade software and firmware for a single controller
:icons: font
:imagesdir: ../media/

[.lead]
You upgrade your storage array's software and, optionally, the IOM firmware and the nonvolatile static random access memory (NVSRAM) to make sure you have all the latest features and bug fixes.

== Download software files from support site

[.lead]
You download the new downloadable package (DLP) software files from the NetApp Support Site to your management client.

The time it takes to upgrade depends on your storage array configuration and the components that you are upgrading.

. If your storage array contains only one controller or you do not have a multipath driver installed, stop I/O activity to the storage array to prevent application errors. If your storage array has two controllers and you have a multipath driver installed, you do not need to stop I/O activity.
+
CAUTION:
+
If you are upgrading SANtricity OS on a StorageGRID appliance (for example, SG5612 or SG5760), you need to stop I/O activity by placing the appliance into maintenance mode before continuing with this procedure, or data could be lost. For detailed steps, see the installation and maintenance instructions for your StorageGRID appliance.

. Select *Support* > *Upgrade Center*.
. In the area labeled SANtricity OS Controller Software upgrade, click *NetApp Support*.
. On the Support web site, click the *Downloads* tab, and then select *Software*.
. Select *SANtricity OS Controller Software*.
+
NOTE: Digitally signed firmware is required in version 8.42 and above. If you attempt to download unsigned firmware, an error is displayed and the download is aborted.

. Follow the remaining instructions.
+
The file to download has a filename similar to E28xx_1140 with a .zip or .tar.gz extension.

. If you do NOT want to upgrade the IOM firmware at this time, click *Suspend IOM Auto-Synchronization*.
+
If you have a storage array with a single controller, the IOM firmware is not upgraded.

== Transfer software files to the controllers

[.lead]
You transfer the software files to your controllers so you can begin the upgrade process. The components are copied from the management client to the controllers and placed in a staging area in flash memory.

IMPORTANT: *Risk of data loss or risk of damage to the storage array* - Do not make changes to the storage array while the upgrade is occurring. Maintain power to the storage array.

. Under SANtricity OS Software upgrade, click *Begin Upgrade*.
+
The Upgrade SANtricity OS Software dialog appears.

. Select one or more files to begin the upgrade process:
 .. Select the SANtricity OS Software file by clicking *Browse* and navigating to the OS software file you downloaded from the Support web site.
 .. Select the Controller NVSRAM file by clicking *Browse* and navigating to the NVSRAM file that you downloaded from the Support site. Controller NVSRAM files have a filename similar to N2800-830000-000.dlp.

+
These actions occur:
 ** By default, only the files that are compatible with the current storage array configuration appear.
 ** When you select a file for upgrade, the file's name and size appear.
. (Optional) If you selected a SANtricity OS Software file to upgrade, you can transfer the files to the controller without activating them by selecting the *Transfer files now, but do not upgrade (activate upgrade later)* check box.
. Click *Start*, and confirm that you want to perform the operation.
+
You can cancel the operation during the pre-upgrade health check, but not during transferring or activating.

. (Optional) To see a list of what was upgraded, click *Save Log*.
+
The file is saved in the Downloads folder for your browser with the namedrive_upgrade_log-timestamp.txt.

If you have already activated your software files, go to link:task_upgrade_software_and_firmware_for_a_single_controller.md#[Complete software and firmware upgrade]; otherwise go to link:task_upgrade_software_and_firmware_for_a_single_controller.md#[Activate software files].

== Activate software files

[.lead]
You activate the software files only if you have software or firmware that has been transferred but not activated. When you perform the activation operation, the current software and firmware is replaced with the new software and firmware. You cannot stop the activation process after it starts.

When you have software or firmware that has been transferred but not activated, you see a notification in the Notifications area of the System Manager Home page and also on the Upgrade Center page.

. Select *Support* > *Upgrade Center*.
. In the area labeled SANtricity OS Controller Software upgrade, click *Activate*, and confirm that you want to perform the operation.
. (Optional) To see a list of what was upgraded, click *Save Log*.
+
The file is saved in the Downloads folder for your browser with the namedrive_upgrade_log-timestamp.txt.

== Complete software and firmware upgrade

[.lead]
You can complete the software and firmware upgrade by verifying the versions in SANtricity System Manager's Software and Firmware Inventory dialog box.

* You must have activated your software or firmware.

. Verify that all components appear on the Hardware page.
. Verify the new software and firmware versions by checking the Software and Firmware Inventory dialog box (go to *Support* > *Upgrade Center*, and then click the link for *Software and Firmware Inventory*).
. If you upgraded controller NVSRAM, any custom settings that you have applied to the existing NVSRAM are lost during the process of activation. You need to apply the custom settings to the NVSRAM again after the process of activation is complete.
. If any of the following errors occur during the upgrade procedure, take the appropriate recommended action.
+
|===
| If you encounter this firmware download error...| Then do the following...
a|
**    Failed assigned drives

**
    a|
        One reason for the failure might be that the drive does not have the appropriate signature. Make sure that the affected drive is an authorized drive. Contact technical support for more information.

....
 When replacing a drive, make sure that the replacement drive has a capacity equal to or greater than the failed drive you are replacing.

 You can replace the failed drive while the storage array is receiving I/O.


a|
**    Check storage array
....

**
    a|

....
-   Make sure that an IP address has been assigned to each controller.
-   Make sure that all cables connected to the controller are not damaged.
-   Make sure that all cables are tightly connected.

a|
**    Integrated hot spare drives
....

**
    a|
        This error condition must be corrected before you can upgrade the firmware. Launch System Manager and use the Recovery Guru to resolve the problem.

 a|
 **    Incomplete volume groups

**
    a|
        If one or more volume groups or disk pools are incomplete, you must correct this error condition before you can upgrade the firmware. Launch System Manager and use the Recovery Guru to resolve the problem.

 a|
 **    Exclusive operations \(other than background media/parity scan\) currently running on any volume groups

**
    a|
        If one or more exclusive operations are in progress, the operations must complete before the firmware can be upgraded. Use System Manager to monitor the progress of the operations.

 a|
 **    Missing volumes

**
    a|
        You must correct the missing volume condition before the firmware can be upgraded. Launch System Manager and use the Recovery Guru to resolve the problem.

 a|
 **    Either controller in a state other than Optimal

**
    a|
        One of the storage array controllers needs attention. This condition must be corrected before the firmware can be upgraded. Launch System Manager and use the Recovery Guru to resolve the problem.

 a|
 **    Mismatched Storage Partition information between Controller Object Graphs

**
    a|
        An error occurred while validating the data on the controllers. Contact technical support to resolve this issue.

 a|
 **    SPM Verify Database Controller check fails

**
    a|
        A storage partitions mapping database error occurred on a controller. Contact technical support to resolve this issue.

 a|
 **    Configuration Database Validation \(If supported by the storage array’s controller version\)

**
    a|
        A configuration database error occurred on a controller. Contact technical support to resolve this issue.

 a|
 **    MEL Related Checks

**
    a|
        Contact technical support to resolve this issue.

 a|
 **    More than 10 DDE Informational or Critical MEL events were reported in the last 7 days

**
    a|
        Contact technical support to resolve this issue.

 a|
 **    More than 2 Page 2C Critical MEL Events were reported in the last 7 days

**
    a|
        Contact technical support to resolve this issue.

 a|
 **    More than 2 Degraded Drive Channel Critical MEL events were reported in the last 7 days

**
    a|
        Contact technical support to resolve this issue.

 a|
 **    More than 4 critical MEL entries in the last 7 days

**
    a|
        Contact technical support to resolve this issue.

 |===

Your controller software upgrade is complete. You can resume normal operations.
