---
permalink: upgrade-santricity/upgrade-drive-firmware-task.html
sidebar: sidebar
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, drive firmware, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller
summary: You upgrade your drives' firmware to make sure you have all the latest features and bug fixes.
---
= Upgrade E-Series and EF-Series drive firmware
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
Follow this procedure to upgrade your drives' firmware, which ensures you have all the latest features and fixes.

== Step 1: Download drive firmware files

In this step, you go to the NetApp Support site to download the drive firmware files to your management client.

.Steps

. In SANtricity System Manager, select menu:Support[Upgrade Center].
. Under Drive Firmware upgrade, click *NetApp Support* and log in to the NetApp Support site.
. From the Support site, click the *Downloads* tab, and then select *Disk Drive & Firmware Matrix*.
. Select *E-Series and EF-Series Disk Firmware.*
. Follow the on-screen instructions to download the files.

== Step 2: Begin drive firmware upgrade

In this step, you upgrade the drives' firmware.

.Before you begin

* Back up your data using disk-to-disk backup, volume copy (to a volume group not affected by the planned firmware upgrade), or a remote mirror.
* Make sure the storage array has an Optimal status.
* Make sure all drives have an Optimal status.
* Make sure no configuration changes are running on the storage array.
* Understand that if the drives are capable of only an offline upgrade, I/O activity to all volumes associated with the drives is stopped.

.Steps

. From the System Manager Upgrade Center (menu:Support[Upgrade Center]), click *Begin Upgrade* from the "Drive Firmware upgrade" section.
+
A dialog box appears, which lists the drive firmware files currently in use.

. Extract (unzip) the files you downloaded from the Support site.
. Click *Browse*, and select the new drive firmware files that you downloaded from the Support site.
+
Drive firmware files have a filename similar to `D_HUC101212CSS600_30602291_MS01_2800_0002` with the extension of `.dlp`.
+
You can select up to four drive firmware files, one at a time. If more than one drive firmware file is compatible with the same drive, you get a file conflict error. Decide which drive firmware file you want to use for the upgrade and remove the other one.

. Click *Next*.
+
The Select Drives dialog box appears, which lists the drives that you can upgrade with the selected files.
+
Only drives that are compatible appear.
+
The selected firmware for the drive appears in the *Proposed Firmware* information area. If you must change the firmware, click *Back* to return to the previous dialog.

. Select the type of upgrade you want to perform:
 ** *Online (default)* -- Shows the drives that can support a firmware download _while the storage array is processing I/O_. You do not have to stop I/O to the associated volumes using these drives when you select this upgrade method. These drives are upgraded one at a time while the storage array is processing I/O to those drives.
 ** *Offline (parallel)* -- Shows the drives that can support a firmware download _only while all I/O activity is stopped_ on any volumes that use the drives. You must stop all I/O activity on any volumes that use the drives you are upgrading when you select this upgrade method. Drives that do not have redundancy must be processed as an offline operation. This requirement includes any drive associated with SSD cache, a RAID 0 volume group, or any pool or volume group that is degraded. The offline (parallel) upgrade is typically faster than the online (default) method.
. In the first column of the table, select the drive or drives you want to upgrade.
. Click *Start*, and confirm that you want to perform the operation.
+
If you need to stop the upgrade, click *Stop*. Any firmware downloads currently in progress complete. Any firmware downloads that have not started are canceled.
+
CAUTION: Stopping the drive firmware upgrade might result in data loss or unavailable drives.

. (Optional) To see a list of what was upgraded, click *Save Log*.
+
The file is saved in the Downloads folder for your browser with the name `drive_upgrade_log-timestamp.txt`.

. If any of the following errors occur during the upgrade procedure, take the appropriate recommended action.
+
[options="header"]
|===
| If you encounter this firmware download error...| Then do the following...
a|
** Failed assigned drives
a|
One reason for the failure might be that the drive does not have the appropriate signature. Make sure that the affected drive is an authorized drive. Contact technical support for more information.

When replacing a drive, make sure that the replacement drive has a capacity equal to or greater than the failed drive you are replacing.

You can replace the failed drive while the storage array is receiving I/O.


a|
Check storage array
    a|

-   Make sure that an IP address has been assigned to each controller.
-   Make sure that all cables connected to the controller are not damaged.
-   Make sure that all cables are tightly connected.

a|
Integrated hot spare drives
a|
This error condition must be corrected before you can upgrade the firmware. Launch System Manager and use the Recovery Guru to resolve the problem.

a|
Incomplete volume groups
a|
If one or more volume groups or disk pools are incomplete, you must correct this error condition before you can upgrade the firmware. Launch System Manager and use the Recovery Guru to resolve the problem.

a|
Exclusive operations (other than background media/parity scan) currently running on any volume groups
a|
If one or more exclusive operations are in progress, the operations must complete before the firmware can be upgraded. Use System Manager to monitor the progress of the operations.

a|
Missing volumes
a|
You must correct the missing volume condition before the firmware can be upgraded. Launch System Manager and use the Recovery Guru to resolve the problem.

a|
Either controller in a state other than Optimal
a|
One of the storage array controllers needs attention. This condition must be corrected before the firmware can be upgraded. Launch System Manager and use the Recovery Guru to resolve the problem.

a|
Mismatched Storage Partition information between Controller Object Graphs
a|
An error occurred while validating the data on the controllers. Contact technical support to resolve this issue.

a|
SPM Verify Database Controller check fails
a|
A storage partitions mapping database error occurred on a controller. Contact technical support to resolve this issue.

a|
Configuration Database Validation (if supported by the storage array’s controller version)
a|
A configuration database error occurred on a controller. Contact technical support to resolve this issue.

a|
MEL Related Checks
a|
Contact technical support to resolve this issue.

a|
More than 10 DDE Informational or Critical MEL events were reported in the last 7 days
a|
Contact technical support to resolve this issue.

a|
More than 2 Page 2C Critical MEL Events were reported in the last 7 days
a|
Contact technical support to resolve this issue.

a|
More than 2 Degraded Drive Channel Critical MEL events were reported in the last 7 days
a|
Contact technical support to resolve this issue.

a|
More than 4 critical MEL entries in the last 7 days
a|
Contact technical support to resolve this issue.

|===

.What's next?

Your drive firmware upgrade is complete. You can resume normal operations.
