---
permalink: web-services-proxy/index.html
sidebar: sidebar
keywords: Web Services Proxy, WSP,
summary: Overview of the SANtricity® Web Services Proxy, Web Services API, REST API,
---
= SANtricity Web Services Proxy overview
:icons: font
:imagesdir: ../media/

[.lead]
The SANtricity Web Services Proxy is a RESTful API server installed separately on a host system to manage hundreds of new and legacy NetApp E-Series storage systems. The proxy includes SANtricity Unified Manager, which is a web-based interface that provides similar functions.

== Installation overview

Installing and configuring the Web Services Proxy involves the following steps:

. link:install-reqs-task.html[Review installation and upgrade requirements].
. link:install-wsp-task.html[Download and install Web Services Proxy file].
. link:install-login-task.html[Log in to API and Unified Manager].
. link:install-config-task.html[Configure Web Services Proxy].


== Find more information

* The proxy installation includes SANtricity Unified Manager, a web-based interface that provides configuration access to newer E-Series and EF-Series storage systems. For more information, see the Unified Manager online help, which is available from its user interface.
* GitHub contains a repository for the collection and organization of sample scripts illustrating the use of the NetApp SANtricity Web Services API. To access the repository, see: https://github.com/NetApp/webservices-samples.
* Representational state transfer (REST) -- Web Services is a RESTful API that provides access to virtually all the SANtricity management capabilities, so you should be familiar with REST concepts. For more information, see http://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm
* Programming language concepts -- Java and Python are the most common programming languages used with the Web Services API, but any programming language that can make HTTP requests is sufficient for API interaction.
* JavaScript Object Notation (JSON) -- Because data within Web Services is encoded through JSON, you should be familiar with JSON programming concepts. For more information, see http://www.json.org
